import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import { createServer } from 'vite';
import react from '@vitejs/plugin-react';
import { chromium } from 'playwright';
const root = fileURLToPath(new URL('..', import.meta.url));
const output = resolve(root, 'test/artifacts/governance'); mkdirSync(output, { recursive: true });
const server = await createServer({ root: resolve(root, 'examples/starter'), configFile: false, plugins: [react()], server: { host: '127.0.0.1', port: 7100 + Math.floor(Math.random() * 600), hmr: false, watch: null } });
await server.listen();
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || chromium.executablePath(), headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(server.resolvedUrls.local[0]);
  const nav = name => page.getByRole('navigation', { name: '主导航' }).getByRole('button', { name, exact: true }).click();
  const dialog = page.getByRole('dialog');
  await page.getByRole('button', { name: '新增用户', exact: true }).click();
  await dialog.getByRole('textbox', { name: '昵称' }).fill('审计测试');
  await dialog.getByRole('textbox', { name: '手机号' }).fill('13812345678');
  await dialog.getByRole('button', { name: '保存', exact: true }).click(); await dialog.waitFor({ state: 'hidden' });
  assert.equal(await page.evaluate(() => localStorage.getItem('adminui:starter:demo:governance:v1').includes('13812345678')), false);
  await nav('角色与权限');
  await page.getByRole('button', { name: '新增角色', exact: true }).click();
  await dialog.getByRole('textbox', { name: '角色名称' }).fill('测试运营');
  await dialog.getByRole('checkbox', { name: '查看日志 (audit:read)', exact: true }).click();
  await dialog.getByRole('button', { name: '保存', exact: true }).click();
  await dialog.waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: '编辑 测试运营', exact: true }).waitFor();
  await page.getByRole('button', { name: '授权 演示审计员', exact: true }).click();
  await dialog.getByRole('checkbox', { name: '测试运营', exact: true }).click();
  await dialog.getByRole('button', { name: '保存', exact: true }).click(); await dialog.waitFor({ state: 'hidden' });
  assert.equal(await page.getByRole('button', { name: '删除 测试运营', exact: true }).isDisabled(), true);
  await page.getByRole('button', { name: '授权 演示管理员', exact: true }).click();
  await dialog.getByRole('checkbox', { name: '管理员', exact: true }).click();
  await dialog.getByRole('button', { name: '保存', exact: true }).click();
  await dialog.getByText('不能移除最后一个管理员', { exact: true }).waitFor();
  assert.equal(await dialog.getByRole('checkbox', { name: '管理员', exact: true }).isChecked(), false);
  await dialog.getByRole('checkbox', { name: '管理员', exact: true }).click();
  await dialog.getByRole('button', { name: '取消', exact: true }).click();
  await page.screenshot({ path: resolve(output, 'access-desktop.png'), fullPage: true });
  await nav('审计日志');
  const area = page.locator('#aui-page-audit');
  await area.getByRole('cell', { name: '失败', exact: true }).waitFor();
  await area.getByRole('button', { name: /^查看日志 / }).first().click();
  await dialog.getByText(/请求 ID/).waitFor();
  await dialog.getByRole('button', { name: '关闭弹窗', exact: true }).click();
  await area.getByLabel('操作结果', { exact: true }).click(); await page.getByRole('option', { name: '失败', exact: true }).click();
  await area.getByText('共 1 条', { exact: false }).waitFor();
  await area.getByRole('button', { name: '清空日志筛选' }).click();
  const download = page.waitForEvent('download'); await area.getByRole('button', { name: '导出当前页日志' }).click(); await download;
  await page.reload(); await nav('审计日志');
  await area.getByRole('cell', { name: '导出审计日志', exact: true }).waitFor();
  await area.getByLabel('检索日志', { exact: true }).fill('不会存在的日志');
  await area.getByText('暂无数据', { exact: false }).waitFor();
  await area.getByRole('button', { name: '清空日志筛选' }).click();
  await area.getByRole('cell', { name: '保存角色', exact: true }).waitFor();
  await page.screenshot({ path: resolve(output, 'audit-desktop.png'), fullPage: true });
  await page.getByRole('button', { name: '切换到深色模式' }).click();
  for (const width of [390, 360]) {
    await page.setViewportSize({ width, height: 844 });
    await page.waitForTimeout(300); // Wait for the mobile drawer resize transition.
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
    await page.screenshot({ path: resolve(output, `audit-dark-${width}.png`), fullPage: true });
  }
  await page.setViewportSize({ width: 1440, height: 1000 }); await page.waitForTimeout(300);
  await nav('角色与权限');
  await page.getByRole('button', { name: '编辑 测试运营', exact: true }).click();
  await dialog.getByRole('textbox', { name: '角色名称' }).fill('测试运营更新');
  await dialog.getByRole('button', { name: '保存', exact: true }).click(); await dialog.waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: '编辑 测试运营更新', exact: true }).waitFor();
  await page.getByRole('button', { name: '新增角色', exact: true }).click();
  await dialog.getByRole('textbox', { name: '角色名称' }).fill('临时角色');
  await page.setViewportSize({ width: 360, height: 844 }); await page.waitForTimeout(300);
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  await page.screenshot({ path: resolve(output, 'role-dialog-dark-360.png'), fullPage: true });
  await dialog.getByRole('button', { name: '保存', exact: true }).click(); await dialog.waitFor({ state: 'hidden' });
  await page.setViewportSize({ width: 1440, height: 1000 }); await page.waitForTimeout(300);
  await page.getByRole('button', { name: '删除 临时角色', exact: true }).click();
  await dialog.getByRole('button', { name: '确认删除角色', exact: true }).click(); await dialog.waitFor({ state: 'hidden' });
  assert.equal(await page.getByRole('button', { name: '删除 临时角色', exact: true }).count(), 0);
  assert.deepEqual(errors, []);
  console.log('governance UI passed', output);
} finally { await browser.close(); await server.close(); }
