// 浏览器验收：外壳（侧栏 232 / 折叠 64 / 顶栏 48、左上切换公司、左下头像菜单、菜单数量、真面包屑、胶囊工作标签 +「N ⌄」+ 右键、
// 外观弹层 浅 / 深 / 跟随系统 + 色卡、手机：抽屉 × + 页签数按钮）和 starter「外壳与布局」页（面包屑、页内下划线标签 +「更多 ⌄」、
// 表设置抽屉 SettingsSheet、设置侧导航、列表 → 详情两步、步骤条、加载更多、登录按钮一直能点 / 点了再校验、公开页外框）。
// 截图 test/artifacts/navigation/（1440 浅 / 深色 + 390），和已审定的样稿截图并排看。
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer } from 'vite';
import react from '@vitejs/plugin-react';
import { chromium } from 'playwright';

const root = fileURLToPath(new URL('..', import.meta.url));
const output = resolve(root, 'test/artifacts/navigation');
mkdirSync(output, { recursive: true });
const server = await createServer({ root: resolve(root, 'examples/starter'), configFile: false, plugins: [react()], server: { host: '127.0.0.1', port: 6151, hmr: false, watch: null }, logLevel: 'error' });
await server.listen();
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH || chromium.executablePath() });
const url = server.resolvedUrls.local[0];
const step = (name) => console.log(`  · ${name}`);
const shot = (page, name, fullPage = false) => page.screenshot({ path: resolve(output, `${name}.png`), fullPage });
const box = async (loc) => { const b = await loc.boundingBox(); assert.ok(b, 'element has a box'); return b; };
const errors = [];
const open = async (width, height, dark = false) => {
  const page = await browser.newPage({ viewport: { width, height } });
  page.on('pageerror', (e) => errors.push(e.message));
  await page.goto(url);
  await page.locator('.aui-sidebar').waitFor();
  if (dark) await page.getByRole('button', { name: '切换到深色模式' }).click();
  return page;
};
const nav = async (page, name) => {
  if ((page.viewportSize()?.width ?? 1440) <= 760) await page.getByRole('button', { name: '打开菜单' }).click();
  await page.getByRole('navigation', { name: '主导航' }).getByRole('button', { name, exact: true }).click();
  await page.waitForTimeout(250);
};
try {
  // ───────── 1440 外壳 ─────────
  const p = await open(1440, 900);
  step('尺寸：侧栏 232、顶栏 48、菜单行 34、工作标签 30');
  assert.equal(Math.round((await box(p.locator('.aui-sidebar'))).width), 232);
  assert.equal(Math.round((await box(p.locator('.aui-topbar'))).height), 48);
  assert.equal(Math.round((await box(p.getByRole('navigation', { name: '主导航' }).getByRole('button', { name: '公告编辑', exact: true }))).height), 34);
  assert.equal(Math.round((await box(p.locator('.aui-tab').first())).height), 30);
  step('左上：标志方块 + 品牌，下面「当前公司」；左下：头像一行');
  assert.equal(await p.locator('.aui-brand-mark').innerText(), 'A');
  const company = p.locator('.aui-company');
  assert.ok((await box(company)).y < (await box(p.getByRole('navigation', { name: '主导航' }))).y, '切换公司在菜单上面（品牌下）');
  assert.equal(await p.locator('.aui-profile').count(), 0, '新账号区：没有底部散按钮');
  assert.match(await p.locator('.aui-acct-row').innerText(), /陈组长[\s\S]*共享组件/);
  step('菜单数量：灰胶囊 / 要处理的异常色实心；按钮名不含数字');
  const assets = p.getByRole('navigation', { name: '主导航' }).getByRole('button', { name: '素材管理', exact: true });
  assert.equal(await assets.locator('.aui-nav-badge').innerText(), '1,284');
  assert.equal(await p.getByRole('navigation', { name: '主导航' }).getByRole('button', { name: '资金账本', exact: true }).locator('.aui-nav-badge').getAttribute('data-tone'), 'danger');
  step('顶栏真面包屑：分组 › 当前页（深色加粗），没有「工作空间 /」');
  const crumbs = p.locator('.aui-topbar-crumbs');
  assert.deepEqual(await crumbs.locator('span, strong').allInnerTexts(), ['用户与内容', '用户管理']);
  assert.equal(await crumbs.locator('strong').evaluate((el) => getComputedStyle(el).fontWeight), '600');
  assert.equal(await p.getByText('工作空间', { exact: true }).count(), 0);
  step('切换公司：列表 + 当前打勾 + 公司设置');
  await company.click();
  const companyPop = p.locator('.aui-company-pop');
  await companyPop.waitFor();
  assert.match(await companyPop.innerText(), /切换公司[\s\S]*华南子公司（演示）[\s\S]*集团总部（演示）[\s\S]*公司设置/);
  assert.equal(await companyPop.locator('[aria-current]').innerText().then((t) => t.includes('华南子公司')), true);
  await companyPop.getByRole('button', { name: /集团总部/ }).click();
  await p.getByText('切换到集团总部（演示）').waitFor();
  step('账号菜单：我的资料 / API 令牌 / 管理后台 ↗ / 外观 / 退出登录');
  await p.locator('.aui-acct-row').click();
  const acct = p.locator('.aui-acct-pop');
  await acct.waitFor();
  await p.waitForTimeout(150);
  assert.match(await acct.innerText(), /我的资料[\s\S]*API 令牌[\s\S]*管理后台[\s\S]*外观[\s\S]*浅色[\s\S]*深色[\s\S]*跟随系统[\s\S]*退出登录/);
  const admin = acct.getByRole('link', { name: '管理后台（新标签页打开）' });
  assert.equal(await admin.getAttribute('target'), '_blank');
  assert.ok((await box(acct)).y + (await box(acct)).height <= (await box(p.locator('.aui-acct-row'))).y + 1, '菜单在头像行上方');
  await shot(p, 'shell-account-menu');
  await acct.getByRole('button', { name: '深色', exact: true }).click();
  assert.equal(await p.locator('.adminui').first().getAttribute('data-aui-mode'), 'dark', '账号菜单里切深色');
  await acct.getByRole('button', { name: '浅色', exact: true }).click();
  await p.keyboard.press('Escape');
  await acct.waitFor({ state: 'detached' });
  assert.equal(await p.evaluate(() => document.activeElement?.classList.contains('aui-acct-row')), true, 'Esc 焦点回头像行');
  step('外观弹层：浅 / 深 / 跟随系统 + 6 个色卡 + 字号 + 自定义品牌色');
  await p.getByRole('button', { name: '外观', exact: true }).click();
  const appear = p.locator('.aui-appearance-pop');
  await appear.waitFor();
  assert.equal(await appear.locator('.aui-appearance-swatch').count(), 6);
  assert.match(await appear.innerText(), /外观[\s\S]*跟随系统[\s\S]*色卡[\s\S]*字号[\s\S]*自定义品牌色/);
  await appear.getByRole('button', { name: '跟随系统', exact: true }).click();
  assert.equal(await appear.getByRole('button', { name: '跟随系统', exact: true }).getAttribute('aria-pressed'), 'true');
  await appear.getByRole('button', { name: '浅色', exact: true }).click();
  await p.keyboard.press('Escape');
  step('工作标签：胶囊、当前白底细边加粗、× 只在当前、「N ⌄」列表、右键、中键');
  await nav(p, '系统设置');
  await nav(p, '公告编辑');
  await nav(p, '素材管理');
  const tabs = p.locator('.aui-tab');
  assert.equal(await tabs.count(), 4);
  const activeTab = p.locator('.aui-tab.aui-active');
  assert.equal(await activeTab.evaluate((el) => getComputedStyle(el).fontWeight), '600');
  assert.notEqual(await activeTab.evaluate((el) => getComputedStyle(el).borderTopWidth), '0px');
  assert.equal(await p.locator('.aui-tab:not(.aui-active) .aui-tab-close').first().evaluate((el) => getComputedStyle(el).opacity), '0', '非当前标签的 × 平时不露');
  assert.equal(await p.locator('.aui-tab.aui-active').evaluate((el) => getComputedStyle(el).borderBottomStyle !== 'none' && getComputedStyle(el).borderRadius !== '0px'), true, '胶囊：圆角细边，不是下划线');
  await p.getByRole('button', { name: '已打开的页面（4）' }).first().click();
  const list = p.locator('.aui-openpages-pop');
  await list.waitFor();
  assert.equal(await list.locator('.aui-openpages-row').count(), 4);
  await shot(p, 'shell-open-pages');
  await p.keyboard.press('Escape');
  await p.locator('.aui-tab', { hasText: '系统设置' }).click({ button: 'right' });
  const ctx = p.getByRole('menu', { name: '工作标签菜单' });
  await ctx.waitFor();
  assert.deepEqual(await ctx.getByRole('menuitem').allInnerTexts(), ['关闭', '关闭其他', '关闭右侧']);
  await ctx.getByRole('menuitem', { name: '关闭右侧' }).click();
  await p.waitForTimeout(200);
  assert.deepEqual(await p.locator('.aui-tab').allInnerTexts().then((t) => t.map((x) => x.trim())), ['用户管理', '系统设置'], '关闭右侧（公告编辑 / 素材管理）');
  await nav(p, '素材管理');
  await p.locator('.aui-tab', { hasText: '素材管理' }).click({ button: 'middle' });
  await p.waitForTimeout(150);
  assert.equal(await p.locator('.aui-tab', { hasText: '素材管理' }).count(), 0, '中键关闭');
  await shot(p, 'shell-desktop');
  step('折叠 64：标志、公司图标、菜单图标、头像；角上数字；向右弹出');
  await p.getByRole('button', { name: '收起侧栏' }).click();
  await p.waitForTimeout(200);
  assert.equal(Math.round((await box(p.locator('.aui-sidebar'))).width), 64);
  assert.equal(await p.locator('.aui-brand-text').isVisible(), false);
  assert.equal(await p.getByRole('navigation', { name: '主导航' }).getByRole('button', { name: '资金账本', exact: true }).locator('.aui-nav-badge').evaluate((el) => getComputedStyle(el).position), 'absolute');
  await company.click();
  await companyPop.waitFor();
  await p.waitForTimeout(150);
  assert.ok((await box(companyPop)).x >= 48, '折叠态公司菜单向右弹出');
  await shot(p, 'shell-collapsed');
  await p.keyboard.press('Escape');
  await p.getByRole('button', { name: '展开侧栏' }).click();
  step('「外壳与布局」页：面包屑灰色、当前深色；页内标签下划线 +「更多」');
  await nav(p, '外壳与布局');
  const page = p.locator('#aui-page-navigation');
  const bc = page.getByRole('navigation', { name: '面包屑' }).first();
  const linkColor = await bc.locator('.aui-crumb-link').first().evaluate((el) => getComputedStyle(el).color);
  const primary = await p.locator('.adminui').first().evaluate((el) => getComputedStyle(el).getPropertyValue('--aui-primary').trim());
  assert.notEqual(linkColor, primary, '面包屑链接不是主色');
  assert.equal(await bc.locator('[aria-current=page]').evaluate((el) => getComputedStyle(el).fontWeight), '600');
  assert.equal(await page.getByRole('button', { name: '更多层级' }).count(), 1, '太深中间收成 …');
  const tab = page.getByRole('tab', { name: /跟进/ }).first();
  assert.equal(await tab.evaluate((el) => getComputedStyle(el).backgroundColor), 'rgba(0, 0, 0, 0)', '页内标签选中没有浅底块');
  assert.equal(await page.getByRole('button', { name: '记录分区：更多' }).isVisible(), true, '放不下右端「更多 ⌄」');
  assert.equal(await page.locator('.aui-scroll-arrow').count(), 0, '没有圆箭头');
  step('表设置抽屉：880、左 184 分节、一次一节、底部保存条、关之前问');
  await page.getByRole('button', { name: '打开表设置' }).click();
  const sheet = p.locator('.aui-settings-sheet');
  await sheet.waitFor();
  await p.waitForTimeout(300);
  assert.equal(Math.round((await box(sheet)).width), 880);
  assert.equal(Math.round((await box(sheet.locator('.aui-settings-nav'))).width), 184);
  assert.deepEqual(await sheet.locator('.aui-settings-nav-group').allInnerTexts(), ['表格', '业务线 · CRM', '高级']);
  assert.equal(await sheet.getByRole('button', { name: '保存', exact: true }).isDisabled(), true, '没改时保存不能点');
  await sheet.getByRole('button', { name: /业务线设置/ }).click();
  assert.equal(await sheet.locator('.aui-settings-panel h3').innerText(), '业务线设置');
  await p.locator('#nav-limit').fill('300');
  await sheet.locator('.aui-savebar').getByText('改了 1 处').waitFor();
  assert.equal(await sheet.locator('.aui-settings-nav-dot').count(), 1, '改过的节有琥珀圆点');
  await p.locator('#nav-cur').fill('CN');
  assert.equal(await sheet.locator('.aui-settings-nav-error').count(), 1, '出错的节红色叹号');
  await shot(p, 'settings-sheet');
  await p.locator('#nav-cur').fill('CNY');
  await sheet.getByRole('button', { name: '取消', exact: true }).click();
  await p.getByRole('heading', { name: '放弃没保存的改动？' }).waitFor();
  await p.getByRole('button', { name: '继续编辑' }).click();
  await sheet.getByRole('button', { name: '保存', exact: true }).click();
  await p.getByText('表设置已保存').waitFor();
  await sheet.getByRole('button', { name: '关闭弹窗' }).click();
  await sheet.waitFor({ state: 'detached' });
  step('步骤：做完的字用正文色；出错 = 异常色 ×');
  const done = page.locator('.aui-step[data-state=done]').first();
  const text = await p.locator('.adminui').first().evaluate((el) => getComputedStyle(el).getPropertyValue('--aui-text').trim());
  assert.equal(await done.evaluate((el) => getComputedStyle(el).color), await p.evaluate((c) => { const d = document.createElement('i'); d.style.color = c; document.querySelector('.adminui').append(d); const v = getComputedStyle(d).color; d.remove(); return v; }, text), '做完的步骤字是正文色');
  assert.equal(await page.locator('.aui-steps[data-tone=error]').count(), 1);
  step('加载更多：四态');
  assert.match(await page.locator('.aui-loadmore[data-state=end]').innerText(), /已经到底了 · 共 128 条/);
  assert.match(await page.locator('.aui-loadmore[data-state=error]').innerText(), /重试/);
  step('登录：按钮一直能点，空着点 → 字段下面写缺什么；密码错 → 卡片顶上一条');
  const login = page.locator('.aui-login');
  const submit = login.getByRole('button', { name: '登录', exact: true });
  assert.equal(await submit.isDisabled(), false, '登录按钮不灰');
  await submit.click();
  await login.getByText('请输入账号').waitFor();
  await login.getByText('请输入密码').waitFor();
  assert.equal(await p.evaluate(() => document.activeElement?.getAttribute('autocomplete')), 'username', '焦点到第一个缺的字段');
  await login.getByLabel('账号').fill('tester');
  await login.getByLabel('密码', { exact: true }).fill('123');
  await submit.click();
  await login.getByRole('alert').filter({ hasText: '账号或密码不对' }).waitFor();
  await shot(p, 'navigation-desktop', true);
  await p.close();

  // ───────── 深色 ─────────
  const d = await open(1440, 900, true);
  await d.getByRole('button', { name: '外观', exact: true }).click();
  await d.locator('.aui-appearance-pop').waitFor();
  await shot(d, 'shell-dark');
  await d.keyboard.press('Escape');
  await nav(d, '外壳与布局');
  await d.locator('#aui-page-navigation').getByRole('button', { name: '打开表设置' }).click();
  await d.locator('.aui-settings-sheet').waitFor();
  await d.waitForTimeout(300);
  await shot(d, 'settings-sheet-dark');
  await d.keyboard.press('Escape');
  await d.waitForTimeout(300);
  await shot(d, 'navigation-dark', true);
  await d.close();

  // ───────── 390 ─────────
  const m = await open(390, 844);
  step('手机：没有工作标签条；顶栏 ≡ + 页名 + 页签数');
  assert.equal(await m.locator('.aui-tabs-strip').isVisible(), false);
  assert.equal(await m.locator('.aui-topbar-page').innerText(), '用户管理');
  assert.equal(await m.locator('.aui-topbar-crumbs').isVisible(), false);
  const count = m.locator('.aui-tabs-count');
  assert.ok(await count.isVisible());
  await shot(m, 'mobile-topbar');
  step('手机抽屉：min(304, 84vw)、44px 行、右上 ×、Esc 关');
  await m.getByRole('button', { name: '打开菜单' }).click();
  await m.waitForTimeout(350);
  assert.equal(Math.round((await box(m.locator('.aui-sidebar'))).width), Math.round(Math.min(304, 390 * 0.84)));
  assert.equal(Math.round((await box(m.getByRole('navigation', { name: '主导航' }).getByRole('button', { name: '公告编辑', exact: true }))).height), 44);
  await shot(m, 'mobile-drawer');
  await m.locator('.aui-acct-row').click();
  await m.locator('.aui-acct-pop').waitFor();
  await m.waitForTimeout(150);
  await shot(m, 'mobile-account');
  await m.keyboard.press('Escape');
  await m.locator('.aui-acct-pop').waitFor({ state: 'detached' });
  await m.keyboard.press('Escape');
  await m.waitForTimeout(350);
  assert.equal(await m.locator('.aui-shell.aui-mobile-open').count(), 0, 'Esc 关抽屉');
  await m.getByRole('button', { name: '打开菜单' }).click();
  await m.locator('.aui-drawer-close').click();
  await m.waitForTimeout(350);
  assert.equal(await m.locator('.aui-shell.aui-mobile-open').count(), 0, '× 关抽屉');
  await nav(m, '外壳与布局');
  await count.click();
  await m.locator('.aui-openpages-pop').waitFor();
  await shot(m, 'mobile-open-pages');
  await m.keyboard.press('Escape');
  step('手机：列表 → 详情两步');
  const ld = m.locator('.aui-listdetail[data-narrow=steps]');
  assert.equal(await ld.locator('.aui-listdetail-main').isVisible(), false, '先只看列表');
  await ld.getByRole('button', { name: /^组长/ }).click();
  await m.waitForTimeout(150);
  assert.equal(await ld.locator('.aui-listdetail-list').isVisible(), false, '点一行只看详情');
  await ld.getByRole('button', { name: '返回角色' }).click();
  assert.equal(await ld.locator('.aui-listdetail-list').isVisible(), true, '← 回列表');
  step('手机：面包屑只留「← 上一级」；设置抽屉铺满 + 分节胶囊');
  assert.equal(await m.locator('#aui-page-navigation .aui-crumb-back').first().innerText(), '智能家居');
  await shot(m, 'navigation-mobile', true);
  await m.locator('#aui-page-navigation').getByRole('button', { name: '打开表设置' }).click();
  const ms = m.locator('.aui-settings-sheet');
  await ms.waitFor();
  await m.waitForTimeout(300);
  assert.equal(Math.round((await box(ms)).width), 390);
  assert.equal(await ms.locator('.aui-settings-nav').evaluate((el) => getComputedStyle(el).flexDirection), 'row');
  await shot(m, 'settings-sheet-mobile');
  await m.close();
  assert.deepEqual(errors, []);
  console.log(`PASS navigation: shell 232/64/48, company top-left, avatar account menu (我的资料 / API 令牌 / 管理后台 ↗ / 外观 / 退出登录), menu counts, real breadcrumb, pill work tabs + 「N ⌄」 + right-click + middle-click, appearance popover, collapsed menus open right; in-page underline tabs + 「更多」, SettingsSheet (880 / 184 / one section / save bar / discard prompt), steps, load more, login validates on click; 390: no tab strip + tab count, drawer 44px rows × / Esc, list → detail steps, back crumb, full-screen sheet with pills → ${output}`);
} finally {
  await browser.close();
  await server.close();
}
