// 浏览器验收：starter「反馈与弹层」页（审阅「组件库 03 反馈与弹层」10 项，通知中心 / 命令面板各有自己的测试）。
// 弹框（五档宽度 + 全屏、圆角 12、无模糊、白底栏、滚动才出分隔线、底栏顺序、提交中锁住、失败顶部提示、未保存关闭叠一个小确认、手机底部升起 / 整屏）、
// 确认（图标块、焦点在取消、输入名称打勾、原因必填、失败不关、没有正文就不出正文区）、能撤销就不问（撤销倒计时、放回来）、
// 侧边弹层（无圆角、底栏「改了 N 项」、关之前先问、不挡表格的评论）、菜单（一种外观、行高 32、鼠标打开不高亮、键盘打开高亮第一项、
// 中性悬停、快捷键写短、灰掉写原因、多选菜单头、手机底部操作单）、弹出面板（贴按钮、触发按钮两种状态）、提示条（白卡 12、失败不消失、进行中→完成）、
// 行内提示（四种口气、紧凑 / 淡 / 横幅）、空 / 错 / 没权限 / 404（图标块各不相同、重试、错误详情）、编辑冲突（保留他的、用我的）。
// 1440 浅 / 深色 + 390 截图（test/artifacts/overlays/，和已审定的样稿截图并排看）。
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer } from 'vite';
import react from '@vitejs/plugin-react';
import { chromium } from 'playwright';

const root = fileURLToPath(new URL('..', import.meta.url));
const output = resolve(root, 'test/artifacts/overlays');
mkdirSync(output, { recursive: true });
const server = await createServer({ root: resolve(root, 'examples/starter'), configFile: false, plugins: [react()], server: { host: '127.0.0.1', port: 6150, hmr: false, watch: null }, logLevel: 'error' });
await server.listen();
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH || chromium.executablePath() });
const step = (name) => console.log(`  · ${name}`);
let page;
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  await context.grantPermissions(['clipboard-read', 'clipboard-write'], { origin: new URL(server.resolvedUrls.local[0]).origin });
  page = await context.newPage();
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  const shot = (name, full = false) => page.screenshot({ path: resolve(output, `${name}.png`), animations: 'disabled', fullPage: full });
  const box = (locator) => locator.evaluate((el) => { const r = el.getBoundingClientRect(); return { left: r.left, top: r.top, right: r.right, bottom: r.bottom, width: r.width, height: r.height }; });
  const style = (locator, prop) => locator.evaluate((el, p) => getComputedStyle(el).getPropertyValue(p), prop);
  const settle = () => page.waitForTimeout(260);
  await page.goto(server.resolvedUrls.local[0]);
  await page.getByRole('navigation', { name: '主导航' }).getByRole('button', { name: '反馈与弹层', exact: true }).click();
  const area = page.locator('#aui-page-overlays');
  await area.locator('#ov-dialogs').waitFor();
  await shot('overlays-1440', true);

  step('dialog: five widths + full, radius 12, no border / blur, white footer');
  const dialog = page.getByRole('dialog');
  const widths = {};
  for (const size of ['sm', 'md', 'lg', 'xl', 'full']) {
    await area.locator(`[data-open-size=${size}]`).click();
    await dialog.waitFor();
    await settle();
    widths[size] = Math.round((await box(dialog)).width);
    if (size === 'md') {
      assert.equal(await style(dialog, 'border-top-left-radius'), '12px', '圆角 12');
      assert.equal(await style(dialog, 'border-top-width'), '0px', '没有边框');
      assert.equal(await style(page.locator('.aui-dialog-overlay'), 'backdrop-filter'), 'none', '遮罩不模糊');
      assert.equal(await style(dialog.locator('.aui-dialog-footer'), 'background-color'), 'rgba(0, 0, 0, 0)', '底栏白色（透明，跟弹框同底）');
      assert.equal(await style(dialog.locator('.aui-dialog-header'), 'border-bottom-color'), 'rgba(0, 0, 0, 0)', '没滚动：头部下面没有线');
      assert.equal(await dialog.getAttribute('data-more'), '', '正文还有：底栏上有线');
      await shot('dialog-md');
      await dialog.locator('.aui-dialog-body').evaluate((el) => el.scrollTo(0, 200));
      await settle();
      assert.notEqual(await style(dialog.locator('.aui-dialog-header'), 'border-bottom-color'), 'rgba(0, 0, 0, 0)', '滚动后头部出分隔线');
      const footer = await dialog.locator('.aui-dialog-footer > *').evaluateAll((els) => els.map((el) => el.textContent.trim()));
      assert.deepEqual(footer.slice(-3), ['取消', '下载核对表', '导入 125 行'], '取消 · 次要 · 主操作最右');
    }
    if (size === 'full') {
      const b = await box(dialog);
      assert.ok(Math.abs(b.left - 24) < 1 && Math.abs(b.top - 24) < 1, `全屏四边留 24：${JSON.stringify(b)}`);
      await shot('dialog-full');
    }
    await page.keyboard.press('Escape');
    await dialog.waitFor({ state: 'detached' });
  }
  assert.deepEqual(widths, { sm: 420, md: 560, lg: 800, xl: 1080, full: 1392 }, '宽度 420 / 560 / 800 / 1080 / 全屏');

  step('form dialog: busy lock, failure on top keeps input, discard prompt stacked on the form');
  await area.getByRole('button', { name: '新建客户（表单）' }).click();
  await dialog.first().waitFor();
  const formDialog = page.getByRole('dialog', { name: '新建客户' });
  await formDialog.getByLabel('客户名称').fill('失败');
  await formDialog.getByRole('button', { name: '保存', exact: true }).click();
  assert.equal(await formDialog.getByRole('button', { name: '关闭弹窗' }).isDisabled(), true, '提交中 × 灰掉');
  await formDialog.getByRole('alert').filter({ hasText: '服务器暂时不可用' }).waitFor();
  const alertTop = (await box(formDialog.locator('.aui-dialog-alert'))).top;
  const fieldTop = (await box(formDialog.getByLabel('客户名称'))).top;
  assert.ok(alertTop < fieldTop, '失败提示在顶部');
  assert.equal(await formDialog.getByLabel('客户名称').inputValue(), '失败', '输入保留');
  const start = await box(formDialog.locator('.aui-dialog-footer-start'));
  const save = await box(formDialog.getByRole('button', { name: '保存', exact: true }));
  assert.ok(start.left < save.left, '危险操作在最左');
  assert.match(await style(formDialog.getByRole('button', { name: '删除草稿' }), 'color'), /rgb/, '删除草稿是红字幽灵');
  await shot('dialog-form-error');
  await page.keyboard.press('Escape');
  const discard = page.getByRole('dialog', { name: '放弃未保存的内容？' });
  await discard.waitFor();
  assert.equal(await page.locator('.aui-dialog').filter({ has: page.locator('#ov-cust-name') }).isVisible(), true, '原弹框还在下面，看得见填了什么');
  assert.equal(await page.evaluate(() => document.activeElement?.textContent), '继续填写', '小确认焦点在「继续填写」');
  await shot('dialog-discard');
  await discard.getByRole('button', { name: '继续填写' }).click();
  await discard.waitFor({ state: 'detached' });
  assert.equal(await formDialog.getByLabel('客户名称').inputValue(), '失败');
  await page.keyboard.press('Escape');
  await page.getByRole('dialog', { name: '放弃未保存的内容？' }).getByRole('button', { name: '放弃修改' }).click();
  await formDialog.waitFor({ state: 'detached' });

  step('confirm: icon block, focus on 取消, typed name ticks, reason required, failure stays, no empty body');
  await area.getByRole('button', { name: '转交客户（普通）' }).click();
  const transfer = page.getByRole('dialog', { name: /转交给小王/ });
  await transfer.waitFor();
  await settle();
  assert.equal(await transfer.locator('form.aui-dialog-body').isHidden(), true, '没有正文就不出正文区');
  assert.equal(await page.evaluate(() => document.activeElement?.textContent), '取消', '默认焦点在取消');
  assert.equal(Math.round((await box(transfer)).width), 420);
  await shot('confirm-plain');
  await page.keyboard.press('Escape');
  await transfer.waitFor({ state: 'detached' });
  await area.getByRole('button', { name: '删除业务线（输入名称）' }).click();
  const line = page.getByRole('dialog', { name: /删除业务线/ });
  await line.waitFor();
  assert.equal(await style(line.locator('.aui-confirm-icon'), 'width'), '36px', '36 图标块');
  assert.equal(await line.getByRole('button', { name: '删除业务线' }).isDisabled(), true, '没输名称按钮不亮');
  assert.equal(await line.locator('.aui-confirm-impact li').count(), 3, '影响清单');
  await line.getByLabel(/请输入/).fill('智能家居客户');
  await line.getByLabel('名称正确').waitFor();
  assert.equal(await line.getByRole('button', { name: '删除业务线' }).isDisabled(), false);
  await shot('confirm-type');
  await page.keyboard.press('Escape');
  await line.waitFor({ state: 'detached' });
  await area.getByRole('button', { name: '停用账号（写原因）' }).click();
  const reason = page.getByRole('dialog', { name: /停用「周经理」/ });
  await reason.waitFor();
  await reason.getByRole('button', { name: '停用账号' }).click();
  await reason.getByText('请填写原因').waitFor();
  await page.keyboard.press('Escape');
  await reason.waitFor({ state: 'detached' });
  await area.getByRole('button', { name: '失败的确认' }).click();
  const fail = page.getByRole('dialog', { name: /作废报价单/ });
  await fail.getByRole('button', { name: '作废' }).click();
  await fail.getByRole('alert').filter({ hasText: '先去作废合同' }).waitFor();
  assert.equal(await fail.isVisible(), true, '失败不关');
  await shot('confirm-fail');
  await page.keyboard.press('Escape');
  await fail.waitFor({ state: 'detached' });

  step('undo instead of confirm: act at once, 撤销 with seconds, put it back');
  await area.locator('[data-undo-row="陈冠宇"]').click();
  const toast = page.locator('.aui-notice').filter({ hasText: '已删除客户' });
  await toast.waitFor();
  assert.equal(await area.locator('[data-undo-row="陈冠宇"]').count(), 0, '直接删了，没有确认框');
  assert.match(await toast.locator('.aui-notice-action').innerText(), /撤销\s*[78]/, '撤销按钮倒数');
  assert.equal(await toast.locator('.aui-notice-bar').count(), 1, '底部细进度');
  assert.equal(await style(toast, 'border-top-left-radius'), '12px');
  assert.equal(Math.round((await box(toast)).width), 380);
  await shot('toast-undo');
  await toast.locator('.aui-notice-action').click();
  await area.locator('[data-undo-row="陈冠宇"]').waitFor();
  await page.locator('.aui-notice').filter({ hasText: '已撤销' }).waitFor();

  step('toasts: failure stays, progress turns into the result in place, at most 3');
  await area.getByRole('button', { name: '失败', exact: true }).click();
  const failToast = page.locator('.aui-notice-error');
  await failToast.waitFor();
  await area.getByRole('button', { name: '进行中 → 完成' }).click();
  await page.locator('.aui-notice-loading').waitFor();
  await page.locator('.aui-notice').filter({ hasText: '导出好了' }).waitFor({ timeout: 4000 });
  await page.waitForTimeout(4600);
  assert.equal(await failToast.count(), 1, '失败过了 4 秒还在');
  for (const name of ['成功', '带操作', '部分成功', '能撤销']) await area.getByRole('button', { name, exact: true }).click();
  assert.ok((await page.locator('.aui-notice').count()) <= 3, '最多 3 条');
  await shot('toasts');
  await failToast.getByRole('button', { name: '关闭通知' }).click().catch(() => undefined);

  step('side sheet: no radius, footer counts changes, asks before closing; comments sheet leaves the page usable');
  await area.getByRole('button', { name: '表设置' }).click();
  const sheet = page.getByRole('dialog', { name: '表设置' });
  await sheet.waitFor();
  await settle();
  assert.equal(await style(sheet, 'border-top-left-radius'), '0px', '侧边不做圆角');
  const sb = await box(sheet);
  assert.ok(Math.abs(sb.right - 1440) < 1 && sb.top === 0 && Math.round(sb.height) === 900, `贴右边上下铺满：${JSON.stringify(sb)}`);
  await sheet.getByLabel('几天没跟进退回公海').fill('10');
  await sheet.getByText('改了 1 项，还没保存').waitFor();
  await shot('sheet-settings');
  await page.keyboard.press('Escape');
  await page.getByRole('dialog', { name: '放弃没保存的改动？' }).getByRole('button', { name: '放弃改动' }).click();
  await sheet.waitFor({ state: 'detached' });
  await area.getByRole('button', { name: '评论（不挡表格）' }).click();
  const comments = page.getByRole('dialog', { name: '评论 · 赵静怡' });
  await comments.waitFor();
  assert.equal(await page.locator('.aui-dialog-overlay').count(), 0, '评论没有遮罩');
  await area.getByRole('button', { name: '成功', exact: true }).click();
  assert.equal(await comments.isVisible(), true, '点页面上的按钮评论不关');
  await shot('sheet-comments');
  await comments.getByRole('button', { name: '关闭弹窗' }).click();

  step('menus: one look, 32 rows, mouse open highlights nothing, keyboard opens on the first, neutral hover, compact keys, reasons');
  await area.getByRole('button', { name: '新建 ▾' }).click();
  let menu = page.getByRole('menu');
  await menu.waitFor();
  assert.equal(await menu.locator('[data-active]').count(), 0, '鼠标打开不高亮任何一项');
  assert.equal(await style(menu, 'border-top-left-radius'), '12px');
  assert.equal(Math.round((await box(menu.getByRole('menuitem').first())).height), 32, '行高 32');
  await menu.getByRole('menuitem').first().hover();
  assert.equal(await style(menu.getByRole('menuitem').first(), 'outline-style'), 'none', '不画焦点框');
  const hover = await style(menu.getByRole('menuitem').first(), 'background-color');
  const soft = await page.evaluate(() => getComputedStyle(document.querySelector('.adminui')).getPropertyValue('--aui-soft').trim());
  assert.notEqual(hover, soft, '悬停是中性浅底，不是主色浅底');
  await shot('menu-new');
  await page.keyboard.press('Escape');
  await area.getByRole('button', { name: '新建 ▾' }).focus();
  await page.keyboard.press('Enter');
  await menu.waitFor();
  assert.equal(await menu.locator('[data-active]').count(), 1, '键盘打开高亮第一项');
  await page.keyboard.press('Escape');
  const row = area.locator('#ov-menu-table tbody tr').first();
  await row.click({ button: 'right' });
  menu = page.getByRole('menu', { name: '单元格菜单' });
  await menu.waitFor();
  assert.deepEqual(await menu.locator('.aui-cmenu-kbd').first().locator('.aui-kbd').allInnerTexts(), ['Ctrl', 'C']);
  assert.deepEqual(await menu.locator('.aui-cmenu-kbd').nth(1).locator('.aui-kbd').allInnerTexts(), ['⇧', '↵'], '快捷键写短');
  assert.equal(await menu.locator('.aui-cmenu-reason').innerText(), '管理员关掉了导出', '灰掉的写原因');
  const items = await menu.getByRole('menuitem').allInnerTexts();
  assert.match(items.at(-1), /^删除/, '危险项在最后');
  await menu.getByRole('menuitem', { name: '移到阶段' }).hover();
  const sub = page.getByRole('menu', { name: '移到阶段' });
  await sub.waitFor();
  const gap = (await box(sub)).left - (await box(menu)).right;
  assert.ok(gap >= 4 && gap <= 8, `子菜单右边 6px 展开：${gap}`);
  await shot('menu-context');
  await page.keyboard.press('Escape');
  await page.keyboard.press('Escape');
  await area.getByRole('button', { name: '批量操作 ▾' }).click();
  menu = page.getByRole('menu');
  assert.match(await menu.locator('.aui-cmenu-head').innerText(), /已选 3 条/, '多选菜单头');
  assert.equal(await menu.getByRole('menuitem', { name: '删除 3 条记录' }).count(), 1, '动作写数量');
  await page.keyboard.press('Escape');

  step('popover: hangs under the trigger, trigger open / applied looks');
  const trigger = area.locator('#ov-popover').getByRole('button', { name: /筛选/ });
  await trigger.click();
  const pop = page.getByRole('dialog', { name: '筛选' });
  await pop.waitFor();
  const tb = await box(trigger);
  const pb = await box(pop);
  assert.ok(Math.abs(pb.left - tb.left) < 1 && pb.top - tb.bottom >= 3 && pb.top - tb.bottom <= 8, `贴按钮左边缘往下：${JSON.stringify({ tb, pb })}`);
  const openBg = await style(trigger, 'background-color');
  await pop.getByRole('button', { name: '添加条件' }).click();
  await page.keyboard.press('Escape');
  assert.notEqual(await style(trigger, 'background-color'), openBg, '已生效和打开不一样');
  assert.match(await trigger.innerText(), /筛选\s*1/);
  await shot('popover');

  step('states: distinct icons per kind, retry and error details, 404 code');
  const states = area.locator('#ov-states');
  const icons = {};
  for (const label of ['还没有', '搜不到', '加载失败', '没权限', '断网', '404']) {
    await states.getByRole('button', { name: label, exact: true }).click();
    const panel = states.locator('[data-state-kind] .aui-state');
    icons[label] = await panel.locator('.aui-empty-icon svg').getAttribute('class');
    if (label === '加载失败') {
      await panel.getByRole('button', { name: '重试' }).waitFor();
      await panel.getByText('错误详情').click();
      await panel.getByText(/req_7f3a9c21/).waitFor();
      await shot('state-error');
    }
    if (label === '搜不到') assert.match(await panel.innerText(), /没找到「陈小姐」[\s\S]*清除搜索/);
    if (label === '没权限') assert.equal(await panel.getAttribute('data-tone'), 'warning');
    if (label === '404') assert.equal(await panel.locator('.aui-state-code').innerText(), '404');
  }
  assert.equal(new Set(Object.values(icons)).size, 6, `六种状态六个图标：${JSON.stringify(icons)}`);
  assert.equal(await style(states.locator('[data-state-kind] .aui-empty-icon'), 'border-top-left-radius'), '16px', '整页尺寸图标块圆角 16');

  step('conflict: keep theirs by default, 用我的 on purpose');
  const conflict = area.locator('#ov-conflict');
  assert.match(await conflict.locator('.aui-conflict-notice').innerText(), /王小明 刚改过「电话」 · 14:31[\s\S]*较新，已保留/);
  await conflict.getByRole('button', { name: '保存时冲突' }).click();
  const saveDialog = page.getByRole('dialog', { name: '保存时有冲突' });
  await saveDialog.waitFor();
  assert.equal(await saveDialog.getByRole('radio', { checked: true }).count(), 2, '默认选他的');
  await saveDialog.getByRole('radio', { name: /用我的/ }).first().click();
  await saveDialog.getByText('保留他的 1 项 · 用我的 1 项').waitFor();
  await shot('conflict-save');
  await saveDialog.getByRole('button', { name: '保存', exact: true }).click();
  await conflict.locator('[data-conflict-result]').filter({ hasText: 'stage=mine，amount=theirs' }).waitFor();

  step('dark');
  await page.getByRole('button', { name: '切换到深色模式' }).click();
  await page.waitForTimeout(150);
  assert.equal(await page.locator('.adminui').first().getAttribute('data-aui-mode'), 'dark');
  await area.locator('[data-open-size=md]').click();
  await dialog.waitFor();
  await settle();
  const surface = await page.evaluate(() => getComputedStyle(document.querySelector('.adminui')).getPropertyValue('--aui-surface').trim());
  assert.notEqual(await style(dialog, 'background-color'), surface, '深色下弹框比页面亮一档');
  await shot('dialog-dark');
  await page.keyboard.press('Escape');
  await area.locator('#ov-menu-table tbody tr').first().click({ button: 'right' });
  await page.getByRole('menu').waitFor();
  await shot('menu-dark');
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '切换到浅色模式' }).click();
  assert.deepEqual(errors, [], '没有页面错误');

  step('390: dialogs rise from the bottom / take the screen, ⋯ menus are action sheets, toasts above the bottom bar');
  const phone = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const pshot = (name) => phone.screenshot({ path: resolve(output, `${name}.png`), animations: 'disabled' });
  await phone.goto(server.resolvedUrls.local[0]);
  await phone.getByRole('button', { name: /菜单|导航/ }).first().click().catch(() => undefined);
  await phone.getByRole('button', { name: '反馈与弹层', exact: true }).first().click();
  const parea = phone.locator('#aui-page-overlays');
  await parea.locator('#ov-dialogs').waitFor();
  await parea.locator('[data-open-size=md]').click();
  const pd = phone.getByRole('dialog');
  await pd.waitFor();
  await phone.waitForTimeout(400);
  const pdb = await pd.evaluate((el) => { const r = el.getBoundingClientRect(); return { left: r.left, right: r.right, bottom: r.bottom, radius: getComputedStyle(el).borderTopLeftRadius }; });
  assert.ok(pdb.left === 0 && Math.round(pdb.right) === 390 && Math.round(pdb.bottom) === 844 && pdb.radius === '16px', `md 从底部升起：${JSON.stringify(pdb)}`);
  const pbtn = await pd.locator('.aui-dialog-footer > .aui-button').last().evaluate((el) => el.getBoundingClientRect().height);
  assert.ok(pbtn >= 44, '底栏按钮 44 高');
  await pshot('dialog-mobile');
  await phone.keyboard.press('Escape');
  await parea.locator('[data-open-size=lg]').click();
  await pd.waitFor();
  await phone.waitForTimeout(400);
  const plg = await box(pd);
  assert.ok(plg.top === 0 && Math.round(plg.height) === 844, 'lg 整屏');
  await pshot('dialog-mobile-lg');
  await phone.keyboard.press('Escape');
  // 8.0.2: four footer actions (删除草稿 · 取消 · 保存并新建下一个 · 保存) never overflow a phone — danger row on top,
  // the secondary action a full row, 取消 · 保存 share the bottom row (保存 right)
  await parea.getByRole('button', { name: '新建客户（表单）' }).click();
  const pform = phone.getByRole('dialog', { name: '新建客户' });
  await pform.waitFor();
  await phone.waitForTimeout(400);
  const fb = async (name) => box(pform.getByRole('button', { name, exact: true }));
  const [pDanger, pCancel, pMore, pSave] = [await fb('删除草稿'), await fb('取消'), await fb('保存并新建下一个'), await fb('保存')];
  for (const [n, b] of Object.entries({ pDanger, pCancel, pMore, pSave })) assert.ok(b.left >= 0 && b.right <= 390.5 && b.height >= 44, `手机底栏 ${n} 在屏内、44 高：${JSON.stringify(b)}`);
  assert.ok(pDanger.bottom <= pMore.top && pMore.bottom <= pCancel.top, `危险在上、次要一整行、取消 · 保存在最下：${JSON.stringify({ pDanger, pMore, pCancel })}`);
  assert.ok(Math.abs(pCancel.top - pSave.top) < 1 && pCancel.right <= pSave.left && pMore.width > 300, `取消 · 保存同一行（保存在右），次要占满一行：${JSON.stringify({ pCancel, pSave, pMore })}`);
  await pshot('form-dialog-mobile');
  await pform.getByRole('button', { name: '取消', exact: true }).click();
  await pform.waitFor({ state: 'detached' });
  await parea.getByRole('button', { name: '视图更多' }).click();
  const actionSheet = phone.locator('.aui-action-sheet');
  await actionSheet.waitFor();
  const rowHeight = await actionSheet.getByRole('menuitem').first().evaluate((el) => el.getBoundingClientRect().height);
  assert.ok(rowHeight >= 48, `操作单行高 48：${rowHeight}`);
  await actionSheet.getByRole('button', { name: '取消' }).waitFor();
  await phone.waitForTimeout(300);
  await pshot('menu-mobile');
  await actionSheet.getByRole('menuitem', { name: '复制视图' }).click();
  await actionSheet.waitFor({ state: 'detached' });
  await parea.getByRole('button', { name: '能撤销', exact: true }).click();
  const ptoast = phone.locator('.aui-notice').first();
  await ptoast.waitFor();
  const ptb = await box(phone.locator('.aui-notices'));
  const lift = await phone.evaluate(() => innerHeight - document.querySelector('.aui-notices').getBoundingClientRect().bottom);
  assert.ok(lift >= 48 && ptb.left >= 12, `提示条抬到底栏之上：${JSON.stringify({ ptb, lift })}`);
  await pshot('toast-mobile');
  await parea.getByRole('button', { name: '表设置' }).click();
  await phone.getByRole('dialog', { name: '表设置' }).waitFor();
  await phone.waitForTimeout(400);
  assert.equal(Math.round((await box(phone.getByRole('dialog', { name: '表设置' }))).width), 390, '手机上侧边整屏');
  await pshot('sheet-mobile');
  await phone.keyboard.press('Escape');
  await parea.getByRole('button', { name: '写跟进（底部弹层）' }).click();
  await phone.locator('.aui-sheet-formhead').waitFor();
  await phone.waitForTimeout(400);
  await pshot('bottom-sheet-mobile');
  assert.equal(await phone.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, '手机不横向溢出');
  await phone.close();
  console.log(`PASS overlays (${output})`);
} finally {
  await browser.close();
  await server.close();
}
