import type { ComponentDoc } from "./types";

const recordDetail: ComponentDoc = {
  slug: "record-detail",
  title: "记录详情",
  subtitle: "RecordDetail · RecordDetailDialog · RecordPage · useRecordDetail · StagePath · FollowButton · RecordHeader · FactStrip · RecordDetailBody · useRecordLayoutEditor · RecordLayoutBar · RecordLayoutButton · ActivityComposer",
  group: "business",
  depth: "deep",
  importFrom: "@adminui/react",
  summary: "一条记录的详情：一份 RecordLayout，三档展示（简要弹框 / 详情大弹框 / 整页）。字段多、有阶段、有跟进的档案用卡片分区：阶段 + 关键数在顶上，左栏跟进和评论，右栏字段分区卡片，用户可以自己调布局。",
  keywords: "record detail drawer dialog page stage path pipeline follow key numbers layout editor activity composer 记录详情 详情页 详情弹框 卡片分区 阶段 关键数 跟进 关注 编辑布局 商机 客户档案",
  when: [
    "点开表格、看板、搜索结果里的一行看完整信息：表格用 expandRecord，其他入口用 useRecordDetail 或 RecordDetailDialog。",
    "客户、商机、工单这类字段多、有阶段、要记跟进和评论的档案：给 RecordLayout.cards，变成可调布局的卡片分区。",
    "需要收藏、分享链接、放图表和关联表的完整档案：RecordPage 做成独立路由。",
    "自己的页面里只要正文：RecordDetailBody + useRecordLayoutEditor，头部自己画。",
  ],
  whenNot: [
    "只有 3–5 个字段、看一眼就走 —— 简要档（peek）就够，不要上卡片分区。",
    "新建 / 编辑一条记录的表单 —— 用表单弹框或表单页，详情里只做就地编辑。",
  ],
  anatomy: [
    "头部 RecordHeader：首字头像、标题、彩色小标签（badges）、灰色一行 meta（客户 · 负责人 · 城市），右边「编辑布局」「关注」和操作；上一条 / 下一条",
    "阶段条 StagePath：分段进度，每段下面写停了几天（完成的「2 天」、当前的「第 3 天」）；右上「进入下一阶段」，输单 / 作废在「更多」里",
    "关键数：最多 4 个（预计金额 + 赢率、下次跟进、最后跟进、跟进次数），快到期的用注意色",
    "左宽栏：宿主画的块（slots）——跟进（ActivityComposer + 时间线）、评论、子表、附件",
    "右栏 380px：字段分区卡片（联系方式、需求、成交、系统信息），空字段收成一行「3 个空字段已收起 · 显示」",
    "编辑布局条 RecordLayoutBar：改给谁（所有人的默认 / 只改我的）、版式、恢复默认、取消、完成",
  ],
  states: [
    "三种版式（spec.preset）：cards 卡片分区（默认）、single 单栏（阶段变箭头）、split 左资料右动态",
    "手机（≤ 760px 或容器窄于 720px）：一律一列，顺序是顶部 → 主栏 → 右栏；分段进度只留色条",
    "就地编辑：点值（或悬停出来的「编辑」、焦点在值上按 Enter / F2）换成编辑器；失败留在编辑器显示原因；Esc 只取消这一格",
    "只读字段：edit 返回 null，悬停出一把锁，原因写 lockedReason",
    "编辑布局：卡片右上角出拖动把手、整理字段、默认收起、隐藏；隐藏的进底部「已隐藏」托盘；Esc 先退出编辑，不关弹框",
    "记录已退出路径（输单 / 作废）：「更多」按钮显示出口名，用危险色",
  ],
  dos: [
    "一份 RecordLayout 定义一次，三档通用：字段、分区、操作、阶段都只写一遍。",
    "布局存成 JSON（RecordDetailSpec），服务端保存前也用 normalizeRecordDetailSpec 校验；未知字段丢掉，新字段进「其他字段」。",
    "主操作最多 2 个（另可加 1 个 tone: \"attention\" 的当下要办的事）；删除放「更多」并走确认框。",
    "字段说明写在 RecordField.description，悬停字段名就能看到。",
    "跟进类的「写一条」用 ActivityComposer：方式小标签 + 短文本 + 底部一行（工具 | 下次跟进 + 日期 + 保存）。",
    "从看板、日历这类视图打开时用 RecordDetailDialog frame=\"drawer\"，同一份内容放在右侧抽屉里。",
  ],
  donts: [
    "不要卡片套卡片：字段行的分区之间一条线就够，右栏和正文同一个底色。",
    "不要一行一个「—」堆满空字段；空字段收起成一行，点「显示」再就地填。",
    "不要把字段名、值加粗放大；字段名灰色，值用正文字重。",
    "不要用 ⓘ 图标放字段说明，也不要多写一行说明文字。",
    "不要在简要 / 详情弹框里再开一个详情弹框；关联记录替换当前内容或链到整页。",
    "不要自己拼详情弹框、阶段条和跟进框；各处样子会不一样，键盘和读屏也会漏。",
  ],
  a11y: [
    "Esc 关闭详情，焦点回到打开它的那一行；Alt + ↑ / ↓ 随时切换上一条 / 下一条，J / K 在不打字时切换。",
    "阶段每段是按钮：Tab 到它按 Enter 改阶段，当前段带 aria-current=\"step\"，读屏会读出「已完成，2 天」。",
    "编辑布局里卡片可以用键盘移动：Alt + ↑ / ↓ 换顺序、Alt + ← / → 换栏，或空格拿起、方向键移动、空格放下；每一步都有 aria-live 播报。",
    "「关注」是开关按钮（aria-pressed）；字段上的工具按钮在悬停和键盘聚焦时都会出现，触屏常显。",
  ],
  demos: [
    { id: "business/record-detail-cards", title: "卡片分区", description: "阶段可点、关键数、跟进框和时间线、评论、分区卡片；「需求说明」点值就地编辑，右上角可切上一条 / 下一条。", height: 640 },
    { id: "business/record-detail-layout-editing", title: "编辑布局", description: "点「编辑布局」：拖卡片换位置 / 换栏、整理字段、隐藏、换版式；「完成」时选择只改自己的还是改所有人的默认。", height: 640 },
    { id: "business/record-detail-tiers", title: "三档：简要 / 详情 / 整页", description: "同一份 RecordLayout：简要小弹框、详情大弹框（卡片分区）、整页 RecordPage。", height: 320 },
    { id: "business/record-detail-stage-path", title: "阶段路径单独用", description: "StagePath：分段、箭头、只读三种样子。", height: 260 },
    {
      id: "business/record-detail-playground",
      title: "在线调试",
      description: "换版式、开关阶段条和关键数、只读阶段、编辑布局。",
      height: 640,
      controls: [
        { name: "preset", label: "版式 spec.preset", type: "select", options: ["cards", "single", "split"], default: "cards" },
        { name: "showStage", label: "阶段条 stage", type: "boolean", default: true },
        { name: "readOnly", label: "阶段只读 stage.readOnly", type: "boolean", default: false },
        { name: "showKeyNumbers", label: "关键数 keyNumbers", type: "boolean", default: true },
        { name: "showFollow", label: "关注 follow", type: "boolean", default: true },
        { name: "editable", label: "编辑布局 layoutEditor", type: "boolean", default: false },
      ],
    },
  ],
  props: [
    {
      component: "RecordDetail",
      rows: [
        { name: "row", type: "T", description: "这条记录" },
        { name: "title", type: "string", description: "标题；和标题相同的字段不在正文重复" },
        { name: "fields", type: "readonly RecordField<T>[]", description: "分区里可以放的所有字段（value / text / edit / lockedReason / copy / tel / reveal / description …）" },
        { name: "spec", type: "unknown", description: "保存的布局 JSON；按 fields / slots / stage / keyNumbers 自动纠正" },
        { name: "defaultSpec", type: "RecordDetailSpec", description: "spec 为空时用（默认：阶段、关键数、宿主块在主栏，所有字段一个分区）" },
        { name: "stage", type: "RecordStage | null", description: "阶段：{ steps, current, onSelect, readOnly, onAdvance, onMarkLost, labels }" },
        { name: "keyNumbers", type: "readonly RecordKeyNumber[]", description: "关键数，最多显示 4 个：{ key, label, value, hint, tone }" },
        { name: "slots", type: "Record<string, RecordDetailSlot>", description: "宿主画的块（跟进、评论、子表）：{ title, count, actions, render }，按 id 放进布局" },
        { name: "follow", type: "{ on, onToggle, label? } | null", description: "头部安静的星「关注 / 已关注」" },
        { name: "layoutEditor", type: "RecordLayoutEditor", description: "给了才有「编辑布局」：{ onSave(spec, scope), onReset, canEditDefault, scope }；onSave reject 时留在编辑态显示原因" },
        { name: "badges / meta / avatar / status", type: "RecordBadge[] / RecordMetaPart[] / ReactNode / ReactNode", description: "标题旁的彩色小标签、灰色一行（{ person } 显示小头像）、首字头像（默认标题第一个字，null 不要）" },
        { name: "nav", type: "{ index, total, onMove }", description: "上一条 / 下一条" },
        { name: "actions", type: "ReactNode", description: "头部「编辑布局」「关注」之后的按钮（更多菜单、关闭）" },
        { name: "recordKey", type: "string", description: "记录 id：换记录时关掉打开的就地编辑器" },
      ],
    },
    {
      component: "StagePath",
      rows: [
        { name: "steps", type: "readonly StagePathStep[]", description: "{ id, label, days?, kind?: \"normal\" | \"lost\" | \"void\", state?, tone? }；lost / void 不进路径，进末尾「更多」" },
        { name: "current", type: "string | null", description: "当前阶段 id：前面的算完成、后面的算未开始；不给才读每段的 state" },
        { name: "onSelect", type: "(stepId: string) => void", description: "点一段改阶段；不给就不能点" },
        { name: "readOnly", type: "boolean", default: "false", description: "只看，哪一段都不能点" },
        { name: "variant", type: '"segments" | "chevrons"', default: '"segments"', description: "分段（卡片分区）或箭头（单栏版式）" },
        { name: "showDays", type: "boolean", default: "true", description: "分段下面写天数（「2 天」「第 3 天」）" },
        { name: "label", type: "string", default: '"阶段"', description: "读屏名字" },
        { name: "moreLabel", type: "string", default: '"更多"', description: "出口菜单按钮的文字" },
      ],
    },
  ],
};

const orgPicker: ComponentDoc = {
  slug: "org-picker",
  title: "人员选择器",
  subtitle: "OrgPicker · OrgPickerField",
  group: "business",
  depth: "deep",
  importFrom: "@adminui/react/org-picker",
  summary: "按组织架构选人：一个单独的弹窗，左边部门树、中间这个部门的人、右边已选；小场合用行内输入 OrgPickerField，找不到再打开弹窗。单独的子路径和样式块，没有选人的页面不会带上它。",
  keywords: "org picker member picker user picker department tree people select transfer assignee share 人员选择 选人 选成员 部门树 组织架构 指派 审批人 转交 分享",
  when: [
    "分享、字段 / 表权限再授权、指派、选审批人、转交负责人：凡是「选人、部门、角色」的地方都用它。",
    "不知道名字、要按部门找，或者想一次选整个部门（含以后新进的人）。",
    "小场合（名单里加一两个人）用行内输入 OrgPickerField：打字直接选，点「组织架构」再开大弹窗。",
  ],
  whenNot: [
    "从一个短的固定列表里选（5 个以内）—— 用下拉或分段控件。",
    "选的不是人 / 组织（标签、分类）—— 用多选下拉。",
  ],
  anatomy: [
    "顶上：搜索框（搜整个管得着的组织，支持拼音首字母）+ 来源分页（组织架构 / 角色 / 业务线 / 用户组 / 最近，宿主可关）",
    "左栏部门树（约 264 宽）：集团 ▸ 公司 ▸ 部门 ▸ 子部门，箭头展开收起，每层前面勾选框 = 选整个部门",
    "中栏成员：快捷「我 / 我的部门 / 上级」、「整个「一组」」一行、成员（负责人排前面）、「全选这些人」",
    "右栏已选：按 人 / 部门 / 公司 / 角色 / 业务线 分组，写路径和人数，悬停出 ×；「清空」；底部「共覆盖 N 人（去重）」",
    "底栏：说明「部门按含下级算」+「取消 / 确定 (N)」",
    "行内输入 OrgPickerField：已选是小标签（头像 + 名字 + ×），后面直接打字；右边「组织架构」按钮",
  ],
  states: [
    "打开位置：树展开到「我」所在的部门并点中它（左边一条主色竖线），由宿主按 defaultFocus 传入，组件不自己猜",
    "勾部门默认含下级：被盖住的下级和人灰着已勾，写「已含在「销售部」里」；下面有人被选时上级显示半选「—」",
    "范围外：灰掉 + 锁 +「不在你的管理范围」，悬停看完整原因；也可以直接隐藏（availability 返回 hidden）",
    "单选：没有右栏、弹窗窄一档、圆点；最多 N 个：选满后没勾的变灰，右栏顶上「最多选 5 个，已满」",
    "已经在名单里的：灰着写「已授权 · 可读写」，不能再勾",
    "加载：树和成员都是骨架条，不转圈；大部门（500 人）虚拟滚动；空部门说清楚为什么空，部门本身仍可选",
    "搜不到：给三个常见原因（只列管得着的、已离职 / 停用的不显示、可以搜拼音）",
    "手机（≤ 760）：整屏弹层，部门树换成一层层点进去的下钻列表，已选收成底部一条",
  ],
  dos: [
    "管辖范围、默认定位、预选、已授权都由宿主传进来，组件只负责显示和交互；数据走 OrgDataSource 适配器。",
    "预选跟场景走：分享不预选，审批人默认直属主管，培训指派默认上次那批。",
    "搜索放在服务端（search(query)），前端只做防抖、高亮和分组；每条结果写完整路径。",
    "选整个部门时说清楚「含下级」：以后新进的人自动包含，右栏每个部门后面一个开关。",
    "确定才回调 onChange，按钮上带数量「确定 (4)」。",
  ],
  donts: [
    "不要只给一个搜索框：不知道名字就找不到人，也看不到部门结构。",
    "不要打开时什么都不显示：空着点进去要给「我的部门 + 最近选过的」。",
    "不要让人输入部门、角色的编号。",
    "不要把同名部门平铺成一列：每条都要写「公司 › 部门 › 小组」路径。",
    "搜不到时不要只说「无结果」，要说原因和找谁开通。",
    "不要每个页面各写一套选人：分享、权限、指派、审批都用同一个组件。",
  ],
  a11y: [
    "树用 role=\"tree\" / treeitem、aria-level、aria-expanded；勾选 aria-checked=\"true | false | mixed\"（下面有人被选 = mixed）。",
    "成员列表 role=\"listbox\" + aria-multiselectable。",
    "键盘：/ 聚焦搜索；树上 ↑↓ 移动、→ 展开 / 进第一个子、← 收起 / 回父、空格勾选、回车在中间看成员；Tab 在 树 → 成员 → 已选 → 底栏 之间走；Esc 关闭。",
    "手机上行高 56、勾选框 20，触控区不小于 44px。",
  ],
  demos: [
    { id: "business/org-picker-desktop", title: "桌面三栏", description: "部门树 | 成员 | 已选：分享（多选，名单里有一个已离职的人）、转交负责人（单选）、培训指派（只选人、最多 5 个）；换「打开的人」看管辖范围。", height: 860 },
    { id: "business/org-picker-search", title: "搜索与默认定位", description: "打开时停在「我」的部门；搜索框里试试拼音首字母和部门名：人、部门、角色、业务线一起出，命中的字标出来，每条写路径；换身份看范围外的公司怎么显示。", height: 860 },
    { id: "business/org-picker-inline", title: "行内输入与模式", description: "OrgPickerField：空着给建议、打字分组带路径；立刻进名单或攒好再添加；授权名单 GrantList 接 orgSource，「组织架构」打开大弹窗回填。", height: 720 },
    { id: "business/org-picker-mobile", title: "手机", description: "390 宽的框里：整屏弹层、下钻列表、搜索、底部已选条、单选转交。", height: 820 },
  ],
  props: [
    {
      component: "OrgPicker",
      rows: [
        { name: "open / onClose", type: "boolean / () => void", description: "受控打开；Esc、取消、点遮罩都调 onClose" },
        { name: "source", type: "OrgDataSource", description: "数据适配器：roots / loadChildren / loadMembers（游标分页）/ search / resolve / pathOf" },
        { name: "value", type: "PickedSubject[]", description: "受控：{ kind, id, label, path?, includeSub?, status? }；草稿只在「确定」时回调" },
        { name: "onChange", type: "(next: PickedSubject[], picks: OrgPick[]) => void", description: "点「确定」后调用；第二个参数是给服务端的精简形状 { kind, id, label, path, includeSub? }" },
        { name: "mode", type: '"single" | "multiple"', default: '"multiple"', description: "单选：没有右栏、弹窗窄一档" },
        { name: "selectable", type: "SubjectKind[]", default: "人 + 部门 + 公司", description: '["person"] = 只选人（部门只能点进去找人）' },
        { name: "max", type: "number", description: "最多选几个；满了没勾的变灰" },
        { name: "includeSubDefault", type: "boolean", default: "true", description: "勾部门时默认含下级" },
        { name: "defaultFocus", type: "string", description: "打开时树展开到并点中的节点（宿主按「我」算）" },
        { name: "shortcuts", type: "OrgShortcut[]（{ key, label, hint?, subject }）", description: "中栏顶上的快捷：我 / 我的部门 / 上级 / 整个公司" },
        { name: "availability", type: "(ref: SubjectRef) => Availability | undefined", description: "管辖范围：ok / locked（灰掉带锁）/ partial / hidden（直接不显示），带原因" },
        { name: "lockedHint", type: "string", description: "范围外的找谁开通（「跨公司分享要集团管理员开通」）" },
        { name: "existing", type: "Record<string, string>", description: "已在名单里的：subjectKey（person:u1）或 id →「已授权 · 可读写」，灰着不能勾" },
        { name: "extraSources", type: "PickerSource[]", description: "可插拔分页：角色 / 业务线 / 用户组 / 最近；组织架构永远第一" },
        { name: "emptyAction", type: "ReactNode", description: "空部门下面的动作（「去管理后台加人」）" },
        { name: "title / description / confirmLabel", type: "string / ReactNode / string", description: "标题、标题下一行说明、确定按钮文字" },
        { name: "locale / messages", type: "OrgPickerLocale / Partial<OrgPickerMessages>", description: "语言和所有文案（ORG_PICKER_MESSAGES）" },
      ],
    },
    {
      component: "OrgPickerField",
      rows: [
        { name: "placeholder", type: "string", description: "例「添加人、部门或角色」" },
        { name: "commit", type: '"instant" | "batch"', default: '"instant"', description: "选中立刻进名单（分享），或先攒成标签再点「添加 N 个」（要点保存的地方）" },
        { name: "suggestions", type: "PickedSubject[]", description: "空着点进去时的建议：我的部门 + 最近选过的" },
        { name: "chips", type: "boolean", default: "true", description: "已选在框里显示成小标签；GrantList 自己画名单时传 false" },
        { name: "label / disabled", type: "string / boolean", description: "读屏名字（默认用 placeholder）、禁用" },
        { name: "dialogTitle / dialogDescription", type: "string / ReactNode", description: "「组织架构」打开的大弹窗标题和说明；source、value、onChange 和其余属性同 OrgPicker" },
      ],
    },
  ],
};

const access: ComponentDoc = {
  slug: "access",
  title: "权限编辑",
  subtitle: "ModulePermissionEditor · DataScopeSelect · PermissionDiff · EffectiveAccessView · AccessConsole",
  group: "business",
  importFrom: "@adminui/react/access",
  summary: "角色权限按模块组织：每个模块一行（档位 + 能看到的数据 + 细调），保存前看改动和影响，再看一个人每个模块的最终权限和来源。纯展示组件：数据进、回调出，不自己请求。",
  keywords: "access permission role rbac data scope module permission editor effective access diff 权限 角色 数据范围 模块权限 有效权限 权限诊断 授权",
  when: [
    "角色页的「模块权限」：用 ModulePermissionEditor，每个模块统一 5 档（无 / 只看 / 成员·只看自己的 / 成员·按范围看 / 管理员）。",
    "「能看到的数据」下拉：用 DataScopeSelect（五档范围 + 有部门树时「指定部门…」）。",
    "点「保存…」后的确认：用 PermissionDiff 列改动和影响到的人，原因默认必填。",
    "排查「他为什么能 / 不能做这件事」：用 EffectiveAccessView 看最终档位、范围和来源。",
  ],
  whenNot: [
    "整套部门、岗位、角色、成员管理且后端已经有标准权限接口 —— 直接用整页 AccessConsole。",
    "几种角色、一张审计表的小项目 —— 用 AccessManager + AuditLogPage（见「权限治理」）。",
  ],
  anatomy: [
    "模块行：图标 + 模块名 + 一句说明 · 档位下拉（每项带一句说明）· 能看到的数据 · 「细调」",
    "细调面板：按对象列操作（看 / 加 / 改 / 删 / 导出），高危操作标出；字段三态（隐藏 / 只读 / 可写）",
    "改动条：「改了 N 个模块 · 撤销 · 保存…」，改过的行左侧打点",
    "「系统管理」小节：权限管理、组织管理这类后台模块单独一组",
    "确认弹框：按模块列改动（~ / + / −，旧值划掉 → 新值）、「影响 N 人」展开每个人多了 / 少了 / 为什么不变、修改原因",
  ],
  states: [
    "授不出的档灰掉写原因（例：你自己没有「知识库 · 管理员」）；模块没开通显示「本公司未开通 / 套餐不含」+ 去处",
    "对不上任何一档：显示「自定义」",
    "新版本带来的高危权限：不自动给，标「待确认」，在细调里逐个「给 / 不给」",
    "集团下发的角色：readOnly 横幅 +「复制后修改」，「细调」变「查看」",
    "试算之后数据变了：只提醒、照样能保存（服务端保存时再算一遍）",
    "手机（≤ 760px）：每个模块一张卡片，细调变全屏面板，每个操作一行 ≥ 48px",
  ],
  dos: [
    "角色页按模块组织：每个模块一行，档位 + 范围 + 细调。",
    "「成员·只看自己的」范围固定本人，不给选；换档位时范围回到新档的默认。",
    "保存前一定给 PermissionDiff：改了什么、影响谁、为什么，原因写进审计。",
    "影响名单由服务端试算（只允许授出编辑人自己有的权限），前端只显示。",
    "数据范围的显示名可以按业务改（labels：本人 / 部门及下级）。",
  ],
  donts: [
    "不要再画「所有模块 × 所有操作」的大勾选表；人看不懂一个角色到底能做什么。",
    "不要自己拼「下拉 + 部门对话框」做数据范围，用 DataScopeSelect。",
    "不要把新版本的高危权限悄悄给出去；先标待确认，由人决定。",
    "不要因为影响名单过期就拦住保存；提醒一下，服务端会再算。",
    "不要只在前端藏按钮当作权限：服务端逐条鉴权、校验版本、写审计。",
  ],
  a11y: [
    "档位、范围下拉都有读屏名字（例「客户管理 能看到的数据」）；灰掉的选项读得到原因。",
    "改过没保存的行除了打点还有文字说明，不只靠颜色。",
    "确认弹框打开时焦点在弹框里，原因输入框必填时有明确的错误提示；Esc 关闭。",
    "EffectiveAccessView 的「明细」是展开按钮（aria-expanded），窄屏左边选人变成下拉。",
  ],
  demos: [
    { id: "business/access-modules", title: "按模块编辑角色权限", description: "角色「销售主管」已经改了两个模块：点「细调」看操作和字段，点改动条的「保存…」看改动和影响。", height: 620 },
    { id: "business/access-data-scope", title: "能看到的数据", description: "五档范围 + 指定部门；授不出的档灰掉写原因。", height: 240 },
    { id: "business/access-effective", title: "预览 / 诊断", description: "选一个人，看每个模块的最终档位、范围和来源；「明细」展开到每一项。", height: 560 },
  ],
};

const governance: ComponentDoc = {
  slug: "governance",
  title: "权限治理",
  subtitle: "AccessManager · AuditLogPage · GovernanceConsole · SodRulesPage · createGovernanceApi",
  group: "business",
  importFrom: "@adminui/react",
  summary: "权限与审计的整页：小项目用 AccessManager + AuditLogPage（宿主 adapter）；多租户治理用 @adminui/react/access 的 GovernanceConsole 和各治理页（租户、共享 / 收窄规则、职责分离、申请审批、紧急提权、复核、安全体检）。",
  keywords: "governance audit log role management tenant separation of duties sod access request emergency review 权限治理 审计日志 角色管理 成员授权 租户 职责分离 申请审批 紧急提权 复核",
  when: [
    "小项目：几种角色、一张审计表 —— AccessManager（角色、分组权限、成员角色）+ AuditLogPage（筛选、分页、变更前后、导出当前页）。",
    "多租户 / 治理：GovernanceConsole 一页放齐，或单独挂 TenantsPage、SodRulesPage、AccessRequestsPage、EmergencyAccessPage、ReviewsPage、SecurityHealthPage。",
    "治理页自己加载和保存，只收一个 api（createGovernanceApi，或自己写一个满足 GovernanceApi 的对象）。",
  ],
  anatomy: [
    "AccessManager：角色列表、分组权限勾选、新建 / 编辑 / 删除确认、成员角色分配、有效权限",
    "AuditLogPage：关键词、成功 / 拒绝 / 失败、日期范围（UTC 日历日）、服务端分页、详情里看变更前后",
    "治理页：列表 + 编辑弹框；规则编辑先「预览影响」再保存；内置规则只读",
  ],
  states: [
    "首次加载转圈；失败给原因和「重试」；刷新失败保留旧数据并提示「当前数据可能已过期」",
    "空列表和筛选无结果分开说",
    "没有 manage 权限：页面只读，写明缺哪个权限（canManage / can.manage）",
    "保存失败（版本冲突、受保护角色、最后一个管理员）：表单保留，显示服务端的原因",
  ],
  dos: [
    "adapter 透传 AbortSignal，检查 HTTP 状态并校验响应结构；网络异常不能当成功。",
    "操作人和租户从已验证的会话取，不信请求体里自报的。",
    "业务变更和审计写在同一个事务里；拒绝和失败在回滚后单独记一条。",
    "切换租户 / 账号时换 scope，弹框和查询会重置。",
  ],
  donts: [
    "不要把按钮显隐当作鉴权；服务端逐条授权、比对版本、写审计。",
    "不要在日志里写密码、验证码、token、完整手机号；日志接口不给编辑和删除。",
    "不要在前端一次拉全量日志再分页；用服务端分页和稳定排序。",
    "规则不要不预览影响就保存；预览后再改任何地方要重新预览。",
  ],
  a11y: [
    "列表的筛选控件都有可见标签；分页按钮有读屏名字和当前页。",
    "删除、停用这类操作走确认框，焦点进弹框、关闭后回到触发按钮。",
    "成功 / 拒绝 / 失败用文字 + 颜色，不只靠颜色区分。",
  ],
  demos: [
    { id: "business/governance-console", title: "角色、成员与审计日志", description: "内存里的假服务端：改角色或给成员授权，切到「审计日志」能看到刚写的记录。", height: 600 },
    { id: "business/governance-sod", title: "职责分离规则", description: "SodRulesPage + createGovernanceApi（传入假 fetch）：新建、停用、删除规则，看现在违规的人。", height: 520 },
  ],
};

export const businessDocs: readonly ComponentDoc[] = [recordDetail, orgPicker, access, governance];
