import type { ComponentDoc } from "./types";

const chartBasics: ComponentDoc = {
  slug: "chart-basics",
  title: "图表基础与色板",
  subtitle: "AdminChart · ChartState · chartColors · vizCategory · resolveVizTokens",
  group: "charts",
  importFrom: "@adminui/react/charts",
  summary: "AdminChart 包一层 ECharts：主题、坐标轴、图例、提示框和 7 种状态都统一好；颜色全从当前色卡算，换色卡、切深色自动跟。",
  keywords: "chart echarts admin-chart chart-state palette viz color theme dark tooltip legend axis 图表 色板 配色 主题 深色 坐标轴 图例 提示框 状态 加载 空状态",
  when: [
    "页面里要画任何 ECharts 图：交给 AdminChart，不要自己 echarts.init。",
    "图还没数据、筛选后为空、加载失败、刷新失败或没有权限：用 AdminChart 的状态属性，自己画的图用 ChartState。",
    "自定义 option 里需要颜色：写 token（vizCategory(i)、VIZ_BRAND、VIZ_OTHER），由 AdminChart 换成当前色卡的颜色。",
  ],
  whenNot: ["只是一个数加对比 —— 用 KpiCard。", "表格格子里的小趋势 —— 用 Sparkline（SVG，不开图表实例）。"],
  anatomy: [
    "卡头：标题回答一个问题 + 灰字（时间窗 · 单位），由外层 Panel 的 title / count 提供",
    "图例：只有多个系列时出现，放左上，10×10 圆角方块",
    "坐标轴：只画横向网格线（线色混面板色），刻度字是备注色，柱图从 0 开始",
    "提示框：圆角 8 + 浮层阴影；每行 色块 + 名称 + 右对齐等宽数值 + 单位，堆叠带合计",
    "「查看数据」：table 属性在图下面给一张可读的数据表（色盲、读屏都能用）",
  ],
  states: [
    "加载中：骨架柱 + 扫光，和图一样高（不是每张卡一个「加载中…」）",
    "没有数据：图标 + 原因 + 下一步，不画 0 柱",
    "筛选无结果：「筛选后没有数据」+「清空筛选」",
    "失败：只坏这一张卡，给「重试」",
    "刷新失败：旧图留在原地，上面一条注意条写清是几点的数据",
    "无权限：锁 + 原因（这张卡用到了你看不到的字段），不显示 0",
  ],
  dos: [
    "颜色只写 token：类别用 vizCategory(i)，单系列 / 有序用 VIZ_BRAND / vizBrandStep(i)，「其他」用 VIZ_OTHER。",
    "维度是单选 / 多选字段时，用选项自己的标签色 vizOptionColor(hue)：表格里是黄标签，图里也是黄。",
    "多系列一定要有图例或直接标签，并给 table（「查看数据」）；折线 ≤ 6 条、环 ≤ 5 片。",
    "提示框写指标名和单位（「新增付费客户：57 家」），不写「实际：57」。",
    "7 种状态都和图一样高，数据到了下面的内容不跳。",
  ],
  donts: [
    "不要在 option 里写死十六进制颜色或网格线颜色：换色卡、深色都不会跟着变。",
    "不要用彩虹 8 色区分「本期 / 上期」这类有顺序的东西；有序用主色深浅。",
    "不要拿状态色（注意、异常）当第 4 个系列色。",
    "不要每张卡头都挂「标准」小标签；只有「自定义口径」「覆盖看板筛选」才需要露出来。",
    "不要用通用的转圈或「××加载中」做图表加载，高度一变整页会跳。",
  ],
  a11y: [
    "label 是图的读屏名称（role=\"img\"），写成一句完整的问题或标题。",
    "类别色在色盲下区分有限：用 table 提供「查看数据」表格，图例或直接标签不能省。",
    "失败状态带 role=\"alert\"；加载骨架带 aria-busy 和「××加载中」的读屏名。",
    "实时面板加 live：关掉更新动画，读数不闪；不把 aria-live 挂在数字上。",
  ],
  demos: [
    { id: "charts/chart-states", title: "7 种状态", description: "切换状态，图的位置和高度不变。展开图下的「查看数据」看表格。", height: 380 },
    { id: "charts/chart-palette", title: "色板跟着色卡走", description: "在右上角换色卡或切深色：色块和图一起变。", height: 460 },
  ],
};

const chartTypes: ComponentDoc = {
  slug: "chart-types",
  title: "图表类型",
  subtitle: "barOption · donutOption · stackedBarOption · targetBarOption · timeSeriesOption · Sparkline · StepFunnel",
  group: "charts",
  importFrom: "@adminui/react/charts",
  summary: "10 种图一套样子：柱、条形、饼、折线、环、面积、实际 vs 目标、堆叠、漏斗、迷你趋势。option 构造器是纯函数，交给 AdminChart 画。",
  keywords: "bar horizontal ranking donut pie stacked target line area time-series sparkline funnel 柱图 条形 排行 环图 饼图 堆叠 实际 目标 折线 面积 迷你趋势 漏斗",
  when: [
    "比较几个类别：柱 barOption；排行（谁最多）：条形 barOption({ horizontal: true })，highlight 突出「我」。",
    "看占比：环 donutOption（≤ 5 片 + 其他，中间写合计）；只有 2–3 片时才用饼。",
    "按第二个维度拆开：堆叠 stackedBarOption；每期和目标比：targetBarOption。",
    "看趋势：timeSeriesOption（面积 = area: true）；表格里的小趋势用 Sparkline；转化漏斗用 StepFunnel。",
  ],
  anatomy: [
    "柱：顶部圆角 4、最宽 32、间隙 42%，柱顶数字 11px 次要色",
    "环：中间写合计，右侧带数值的图例；窄卡 layout=\"stacked\" 图例放下面",
    "堆叠：段间 1px 缝，只有最外一段圆角，提示框带合计",
    "实际 vs 目标：柱 + 每期一条目标横线，没结束的一期画空心虚线标「进行中」",
    "折线：缺数据处断开，最后一段没结束画虚线；面积只给单系列，8% 填充",
  ],
  dos: [
    "一张卡一张图，标题写这张图回答什么问题，副标题写时间窗和单位。",
    "钱带货币和单位，≥ 1 万写「万」；分布图的系列名写指标（「客户数」），不写「实际」。",
    "没数据的类别传 null：不画柱，不画成 0。",
    "数据刷新时只换 option 的数据，不重建 AdminChart（它会增量合并、保留图例选择）。",
  ],
  donts: [
    "不要用双 Y 轴、3D、渐变填充、雷达图和仪表盘。",
    "不要画梯形漏斗；漏斗用横条 StepFunnel，写清每步的转化和流失。",
    "不要在宽卡里放 5 根细柱隔得很远；类别少就把卡做窄或改用条形。",
    "迷你趋势不要每格开一个 ECharts 实例；用 Sparkline（SVG），手机上不会耗尽内存。",
    "环不要超过 5 片；多出来的并进「其他」。",
  ],
  a11y: [
    "每个 AdminChart 都要 label；Sparkline 的 label 必填（读屏读「MRR 趋势」）。",
    "提示框按轴触发并 confine 在图内：手指不用点得很准，也不会被裁掉。",
    "条形排行的类别从上到下读，和视觉顺序一致。",
  ],
  demos: [
    { id: "charts/chart-types", title: "切换图表类型", description: "同一份北辰云的销售数据，换一种图看它回答什么问题。", height: 420 },
  ],
};

const kpiCard: ComponentDoc = {
  slug: "kpi-card",
  title: "指标卡",
  subtitle: "KpiCard · KpiGrid · MetricCard · MetricGrid · DeltaBadge",
  group: "charts",
  importFrom: "@adminui/react",
  summary: "一个数 + 单位 + 和什么比 + 迷你趋势。3 档尺寸；变化值和选项标签同形，颜色按好坏而不是按涨跌。",
  keywords: "kpi metric stat card delta badge trend sparkline north star 指标卡 数字卡 统计卡 变化值 环比 同比 北极星 趋势",
  when: [
    "看板首屏的 3–5 个关键数：KpiGrid + KpiCard。",
    "数要和某个基准比（上月同期、目标）：用 computeDelta 算出变化，传给 delta，并写 comparison。",
    "只是计数、没有对比基准：MetricGrid + MetricCard。",
    "表格格子、指标条里的变化值：DeltaBadge size=\"sm\"。",
  ],
  anatomy: [
    "标签：13px 次要色，可带「北极星」「进行中」小标签和「i」口径按钮",
    "数值：大 28 / 标准 24 / 紧凑 20，字重 600，等宽数字；单位小一号次要色",
    "变化值 + 「比什么」：圆角 6 软底 + 箭头 + 正负号",
    "迷你趋势：below（卡片底部）或 inline（数值右侧）；紧凑档不画",
    "页脚：数据截至时间 +「查看明细 ›」",
  ],
  states: [
    "加载：骨架占位，卡片高度不变",
    "没有数据：「—」；合法的 0 显示「0」，两者不能混",
    "数据源未接：placeholder 写原因，不显示变化值",
    "样本不足：insufficient，数值变灰、不判断好坏",
    "过期：stale，数值变灰并标「已过期」",
  ],
  dos: [
    "比率用百分点：computeDelta(cur, prev, { mode: \"points\" }) 得到「+1.2pp」。",
    "越低越好的指标（流失率、回款周期）传 better: \"down\"，下降显示为好。",
    "≥ 1 万用 formatNumber(n, { compact: true }) 缩写，精确值放 fullValue。",
    "比例写分母：detail=\"流失 18 家 / 期初 1,188 家\"。",
    "一行等宽等高，KpiGrid 按张数定列；手机两列，单数时最后一张占满。",
  ],
  donts: [
    "不要只给一个数：没有单位、没有对比、没有趋势，读者不知道好坏。",
    "不要让指标名比数字还抢眼（加粗黑字）；名字是次要色。",
    "不要把变化值做成全圆角描边胶囊；和选项标签同形。",
    "从 0 增长不要写「∞%」，跨零不要写「+300%」：组件会写「新增」「由负转正」。",
    "不要在同一行混用 1 格和 2 格宽的卡片，也不要给数字卡固定一个大高度留出半张空白。",
  ],
  a11y: [
    "DeltaBadge 的读屏文本是「比上月 上升 +5.6% 向好」：方向、数值、好坏都读出来，不只靠颜色。",
    "缩写的数值用 fullValue 提供精确值，悬停可见、读屏可读。",
    "「i」口径按钮带 aria-expanded / aria-controls；「查看明细」在手机上至少 40px 高。",
  ],
  demos: [
    { id: "charts/kpi-grid", title: "一行指标卡", description: "点「i」看口径，点「查看明细」下钻。", height: 220 },
    { id: "charts/kpi-sizes", title: "3 档尺寸与变化值", height: 320 },
    { id: "charts/kpi-states", title: "状态与 MetricCard", description: "点「重新加载」看骨架；下面是没有数据、合法的 0、数据源未接、样本不足、过期。", height: 520 },
  ],
};

const bulletProgress: ComponentDoc = {
  slug: "bullet-progress",
  title: "目标与进度",
  subtitle: "BulletBar · ProgressRing · RollupCard",
  group: "charts",
  importFrom: "@adminui/react",
  summary: "目标完成度一律用子弹图：实心条 = 当前，竖实线 = 目标，竖虚线 = 按时间进度这时候该到哪。进度环只给手机上个人自己的进度。",
  keywords: "bullet bar target progress ring gauge rollup goal quota 子弹图 目标 进度 完成率 时间进度 进度环 汇总卡 总览",
  when: [
    "KPI 卡、汇总卡、表格格子里显示「完成了目标的多少」：BulletBar（KpiCard 直接给 target + timeProgress）。",
    "总览页每个区域 / 业务线一张卡：RollupCard，放在 Panel flush 里。",
    "一个人在手机上看自己今天的进度：ProgressRing。",
  ],
  whenNot: ["团队、公司、桌面 KPI 行、表格里的进度 —— 不用环和仪表盘，用 BulletBar。"],
  anatomy: [
    "轨道：10px（sm 8px），圆角 5；分档 bands 用三档灰（越深越差）",
    "实心条：主色；进行中 inProgress 画空心虚线",
    "目标：正文色竖实线；不在末端时写「目标 240 万」",
    "时间进度：竖虚线 +「↑ 时间进度 26%」，靠近起点时左对齐，不压住「0」",
    "RollupCard：名称 + 异常标签 + 下钻按钮 / 值 vs 目标 / 3–4 格指标条",
  ],
  states: [
    "领先 / 落后：右侧写判断（领先 9pp / 落后 12pp），不只靠竖线位置",
    "超额：填充超过目标刻度，写「已达成 112%」",
    "没开始：value 为 null，只画轨道，写开始日期",
    "没设目标：不画目标刻度，引导去设目标",
    "进度环全部完成：变成勾",
  ],
  dos: [
    "timeProgress = 已过的工作日 ÷ 总工作日；假期按业务日历由页面算好再传。",
    "子弹图旁边写判断文字（领先 / 落后 / 已达成）。",
    "汇总卡里没有对比数据显示「—」，不显示「−0%」；数据源未接的格子用 value: null + note。",
    "RollupCard 的下钻按钮带上当前筛选（carryFilterContext）。",
  ],
  donts: [
    "不要用环、仪表盘、饼表示目标完成度：读不准，也不好横向比较。",
    "分档灰阶不要挨得太近，三档要一眼看得出来。",
    "不要让「时间进度」的刻度字压在起点「0」上。",
    "汇总卡的异常不要用全圆角描边胶囊；用圆角 6 的软标签 + 图标。",
  ],
  a11y: [
    "BulletBar 是 role=\"meter\"，aria-valuetext 读出当前、目标和「按时间进度应达」。",
    "ProgressRing 的 label 必填；默认读「7 / 12（58%）」。",
    "RollupCard 是一个带名称的 article；异常标签带图标和文字。",
  ],
  demos: [
    { id: "charts/bullet-bar", title: "子弹图的几种情况", description: "领先、落后、超额、分档、没开始、进行中。", height: 420 },
    { id: "charts/rollup-card", title: "汇总卡", description: "总览页每个区域一张；点「进入区域经营」下钻。", height: 420 },
    { id: "charts/progress-ring", title: "手机上的个人进度", description: "点「记一次回访」，环会走。", height: 300 },
  ],
};

const funnelCohort: ComponentDoc = {
  slug: "funnel-cohort",
  title: "漏斗与留存",
  subtitle: "StepFunnel · CohortTable",
  group: "charts",
  importFrom: "@adminui/react",
  summary: "StepFunnel 用横条画每一步的人数，每步写转化率、分母和变化，并标出「流失最多」；CohortTable 按批次 × 月龄画留存，没到月龄的格写「未到期」。",
  keywords: "funnel conversion step cohort retention heatmap 漏斗 转化 流失 留存 批次 热力表 天龄 月龄",
  when: [
    "看客户卡在哪一步：StepFunnel（试用 → 激活 → 付费）。",
    "看每一批客户过了 N 天 / N 个月还剩多少：CohortTable。",
    "需要图表版的留存热力图：cohortHeatmapOption + AdminChart。",
  ],
  anatomy: [
    "漏斗每步一行：名称 · 主色横条（人数在条内，条太短时放在条外）",
    "右侧：这一步的转化率 + 分母（「918 人 / 1,260 人」）+ 和对比期的变化（pp）",
    "流失最多的一步：注意色「流失最多」软标签；dropBy=\"rate\" 改成标转化率最低的一步",
    "页脚：整体转化（最后一步 ÷ 第一步）",
    "留存表：第一列批次 + 人数（120px），格子从面板色到主色",
    "未到期：斜纹 +「未到期」，不是 0 也不是空白",
  ],
  dos: [
    "按进线批次在固定天龄读数，不用「本月成交 ÷ 本月进线」。",
    "卡头写清是哪一批、几天读数（「9 月注册的试用 · 30 天读数」）。",
    "漏斗条用主色：步骤是有序的量级，不是类别；只有「流失最多」用注意色。",
    "留存只拿同月龄比较；行头写批次人数。",
  ],
  donts: [
    "不要只写转化率不写分母，读者不知道是 1,260 人里的 72.9% 还是 12 人里的。",
    "窄卡里不要把条压短到和数字挤在一起；组件在 ≤ 420px 时自动改成名称在上、条在下。",
    "留存表不要在深色下用浅色亮块表示低值；颜色从面板色起步。",
    "「未到期」不要只画一个描边框，看起来和空白、0 差不多。",
    "不要让留存表第一列占掉四分之一宽度，把格子挤窄。",
  ],
  a11y: [
    "StepFunnel 的 label 是整个漏斗的读屏名；每步的变化值会和 comparison 一起读出。",
    "CohortTable 是真正的 HTML 表格，label 作为 caption，行头列头都有 scope。",
    "只有很深的格子（> 72%）才反白字，保证文字对比度。",
  ],
  demos: [
    { id: "charts/step-funnel", title: "转化漏斗", description: "切换按流失人数或按最低转化率标出「流失最多」。", height: 440 },
    { id: "charts/cohort-table", title: "批次留存表", height: 340 },
  ],
};

const dashboardTabs: ComponentDoc = {
  slug: "dashboard-tabs",
  title: "看板页面",
  subtitle: "DashboardTabs · DashboardSection · DashboardView · WidgetFrame",
  group: "charts",
  importFrom: "@adminui/react/views",
  summary: "看板页的骨架：仪表盘标签和视图标签同一条（团队默认 = 楼、我的 = 人）→ 不套卡的筛选行 → 按问题分区的 6 列网格部件。",
  keywords: "dashboard tabs page layout section widget frame scope company personal 看板 仪表盘 标签 团队默认 我的 分区 部件 网格 布局",
  when: [
    "在多维表格的视图标签条里加仪表盘：DashboardTabs 放进 ViewTabs 的 trailing。",
    "看板分区：DashboardSection，标题就是这块回答的问题。",
    "展示一份存下来的看板：DashboardView（来自 @adminui/react/dashboard-builder），每个部件自带 WidgetFrame 卡头。",
  ],
  anatomy: [
    "标签条：视图标签 ‖「仪表盘」分组字 + 带范围图标的标签 +「+」新建菜单",
    "看板条：左 = 筛选行（不套卡）；右 = 数据截至 · 刷新 · 编辑",
    "网格：6 列；数字组一行等宽；图表 3 + 3 或 2 + 2 + 2",
    "部件卡头：标题 + 来源灰字；只露「自定义口径」「覆盖看板筛选」",
  ],
  states: [
    "当前标签：下划线 + ⋯ 菜单（复制成我的 / 改名 / 删除）",
    "超过 3 个仪表盘：其余收进「更多 N」，当前的一定在条上",
    "改筛选：每个部件先出骨架再出图，不整页闪",
    "手机：标签横滑，当前标签自动滚进可见区；部件按阅读顺序排，数字卡两列",
  ],
  dos: [
    "团队默认的仪表盘用楼图标，我的用人图标；按人出数的公司仪表盘（「我的今天」）也是楼。",
    "「+」菜单：新建我的 / 复制当前为我的 / 新建公司仪表盘（没有权限时写 disabledReason）。",
    "看板条右侧写「数据截至 HH:mm」和刷新，读者知道数是几点的。",
    "分区标题写问题（「这个月卖得怎么样」），说明收进「?」。",
  ],
  donts: [
    "不要把仪表盘挤在视图标签最右边、换一种样子（浅底方块 vs 描边胶囊）。",
    "不要给筛选行套一张白卡，也不要放不下就折成两行。",
    "不要每张部件卡头都挂「标准」标签。",
    "手机上不要让筛选全部展开占半屏。",
  ],
  a11y: [
    "DashboardTabs 是一个带 aria-label 的 nav，左右方向键在标签间移动焦点。",
    "范围图标是装饰（aria-hidden），范围写在菜单和提示里。",
    "DashboardView 是带 label 的 region；每个部件是带标题的 section。",
  ],
  demos: [
    { id: "charts/dashboard-page", title: "完整的看板页", description: "切换仪表盘 / 视图、改筛选、点刷新。", height: 640, bleed: true },
    { id: "charts/dashboard-tabs", title: "仪表盘标签", description: "点「+」看新建菜单，点当前标签的 ⋯ 看标签菜单。", height: 220 },
  ],
};

const dashboardFilters: ComponentDoc = {
  slug: "dashboard-filters",
  title: "看板筛选行与报表工具条",
  subtitle: "DashboardFilterBar · ReportToolbar · useDashboardFilters",
  group: "charts",
  importFrom: "@adminui/react",
  summary: "一行、不套卡：时间分段 · 对比 · 维度胶囊 ·（改过才出）重置。报表工具条同一条，选了就查，没有「查询」按钮。",
  keywords: "dashboard filter bar report toolbar time range compare dimension pill reset url 筛选 筛选行 报表 工具条 时间 对比 环比 同比 维度 重置 导出",
  when: [
    "看板顶部的全局筛选：DashboardFilterBar，状态是一个 DashboardFilterValue。",
    "筛选要进地址栏、能分享、返回键能回到上一组筛选：useDashboardFilters。",
    "报表页按日期范围和来源统计：ReportToolbar。",
  ],
  anatomy: [
    "时间分段：今天 / 本周 / 本月 / … / 自定义（选好两个日期才生效）",
    "对比：每项带一句说明；只有一个可选项时是纯文字，不出下拉",
    "维度胶囊：30px、圆角 8；没值描边，有值浅主色底 + 粗字 + ×",
    "重置：和标准筛选不同才出现",
    "报表工具条：日期快捷 · 日期范围 · 来源 ·（改过）重置 ‖ 数据截至 · 刷新 · 导出",
  ],
  states: [
    "展开：主色边 + 聚焦光圈（和下拉同一套）",
    "未应用：页面用不上的筛选写「未应用：负责人」",
    "手机：时间胶囊 +「筛选 · n」→ 底部弹层，底部「重置 / 看结果」",
    "报表日期无效：留在输入框里并写原因，不应用",
  ],
  dos: [
    "时间保存成相对值（today、month），分享出去的链接打开仍是「今天」。",
    "对比的说明写具体（「10-01 ~ 10-07 比 9-01 ~ 9-07，同样天数」）；遇到假期等特殊情况用 compareNote。",
    "下钻到别的页面用 carryFilterContext 带走筛选，目标页不支持的写进 unapplied。",
    "地址栏里的筛选只是请求：服务端仍按查看者的权限范围取交集。",
  ],
  donts: [
    "不要给筛选行套白卡（圆角 + 阴影），和下面的部件抢层级。",
    "「重置」不要一直显示，也不要做成浅灰像禁用。",
    "只有一个对比选项时不要出一个只有一项的下拉。",
    "报表不要再加「查询」按钮；选了就查。",
    "手机上不要把所有筛选全部展开。",
  ],
  a11y: [
    "整行是 role=\"group\" + aria-label（默认「看板筛选」）。",
    "每个胶囊的读屏名是「区域：华东」；清除按钮是「清除区域筛选」。",
    "底部弹层里的选项至少 40px 高，选中用 aria-pressed。",
  ],
  demos: [
    { id: "charts/filter-bar", title: "看板筛选行", description: "改时间、对比和维度；改过才出「重置」。选了负责人会出现「未应用」。", height: 200 },
    { id: "charts/report-toolbar", title: "报表工具条", description: "点快捷日期或改来源立即重新统计。", height: 200 },
  ],
};

const dashboardBuilder: ComponentDoc = {
  slug: "dashboard-builder",
  title: "看板搭建器",
  subtitle: "DashboardBuilder · DashboardView · WidgetLibrary · WidgetConfig",
  group: "charts",
  depth: "deep",
  importFrom: "@adminui/react/dashboard-builder",
  summary: "让用户自己拼看板：左边组件库、中间 6 列画布、选中卡片右边才出设置。看板是一份普通 JSON，数据由宿主在服务端按权限聚合后交回。",
  keywords: "dashboard builder editor canvas widget library config drag resize undo redo preview read-only json 看板搭建 仪表盘编辑 拖拽 画布 组件库 卡片设置 撤销 重做 预览 只读",
  when: [
    "用户要自己拼看板（「我的周报」），或管理员维护团队默认看板。",
    "看板需要存成 JSON、在别的地方只读展示：编辑用 DashboardBuilder，展示用 DashboardView。",
  ],
  whenNot: ["固定不变的看板页 —— 直接用 KpiGrid、Panel + AdminChart 写死，更简单。"],
  anatomy: [
    "工具条（一行 52px）：名字 ✎ · 范围（团队默认 / 我的）·「3 处修改未保存」· ? 权限说明 ‖ 撤销 重做 · 预览 · 取消 · 另存为我的 · 保存",
    "筛选行：宿主传入的 DashboardFilterBar，作用于全部组件",
    "组件库（248px，可收成 56px 图标栏）：搜索 + 图表图标块 + 标准组件（口径来自指标字典）；拖到画布或点一下加到最后",
    "画布：6 列、行高 28px、淡色列参考线；卡片工具（复制 / 设置 / 删除）在卡头里，悬停或选中才出现",
    "卡片设置（320px，只在选中时出现）：「数据」选来源、标准指标或自定义口径、分组、对比、目标值；「样式」换图表类型、颜色、数值标签",
  ],
  states: [
    "拖动：主色虚线占位，其他卡让位，松手后往上收",
    "改大小：右 / 下 / 右下 3 个把手 +「3 列 × 10 行」提示",
    "没改动：保存按钮禁用；有改动：注意色写「N 处修改未保存」",
    "预览：一键看最终样子（只读）",
    "保存失败：留在搭建器里，显示原因",
    "手机（< 760px）：只读预览 +「请在电脑上编辑」",
  ],
  dos: [
    "标准组件和标准指标来自宿主的指标字典（metrics），口径不能在看板里改；要改就换成「自定义」并写口径说明。",
    "loadWidgetData 在服务端按查看者的权限范围取交集再聚合；分享给别人时按对方的权限出数。",
    "多个数字放一行用「数字组」（2–6 个等宽），不要用很多张 1 格的数字卡拼。",
    "存量看板先过 migrateDashboardSpec(spec) 再交给搭建器（只认 version 2）。",
    "没数据返回 { kind: \"empty\" }，看不到的字段返回 { kind: \"forbidden\" }，不要画 0。",
  ],
  donts: [
    "不要让组件库和设置面板一直占着两边，把画布挤到数字只剩「1.」。",
    "不要把卡片工具条浮在卡片上方压住标题。",
    "工具条不要拆成两行、中间留一大块空。",
    "不要用 64px 这种粗格子：数字卡会空出半张。",
    "不要在搭建器里另起一套状态胶囊样式；范围和未保存状态用统一的样子。",
  ],
  a11y: [
    "画布里的卡片可以 Tab 聚焦：方向键移动、Shift + 方向键改大小、Delete 删除、Ctrl+D 复制、Esc 取消选中；Ctrl+Z 撤销，Ctrl+Shift+Z / Ctrl+Y 重做。",
    "每张卡的读屏名带位置：「新签合同额（第 1 列第 5 行，宽 3 高 8）」；移动、改大小后有播报。",
    "组件库的项目既能拖也能点（键盘 Enter 加到最后），不要求拖拽。",
    "范围图标是装饰，范围文字写在标签里。",
  ],
  demos: [
    {
      id: "charts/builder-playground",
      title: "在线调试",
      description: "拖动、改大小、加组件、改设置、撤销都能真的做。切到「只读」看同一份 JSON 交给 DashboardView 的样子。",
      height: 640,
      bleed: true,
      controls: [
        { name: "mode", label: "模式", type: "select", options: ["edit", "view"], default: "edit" },
        { name: "scope", label: "范围 scope", type: "select", options: ["company", "personal"], default: "company" },
        { name: "libraryCollapsed", label: "组件库收成图标栏 libraryCollapsed", type: "boolean", default: false },
      ],
    },
    { id: "charts/builder-empty", title: "从空白开始", description: "只开放 5 种图；第一次保存会失败，看错误怎么显示。", height: 600, bleed: true },
    { id: "charts/dashboard-view", title: "只读看板 DashboardView", description: "切到「按阅读顺序」看手机上的排法。", height: 760 },
    { id: "charts/target-progress", title: "目标进度卡与时长单位", description: "「目标进度」组件（kind: targetProgress）：落后、超额、还没设目标；右边是 unit: \"duration\" 的数字卡。", height: 320 },
  ],
  props: [
    {
      component: "DashboardBuilder",
      rows: [
        { name: "value", type: "DashboardSchema", description: "要编辑的看板（只在挂载时读一次；要换一份看板就给新的 key）" },
        { name: "loadWidgetData", type: "(widget, context, signal) => Promise<DashboardWidgetData>", description: "必填：宿主在服务端按权限聚合，返回和组件类型对应的数据" },
        { name: "filterContext", type: "DashboardFilterValue", description: "必填：当前看板筛选（来自 DashboardFilterBar / useDashboardFilters）" },
        { name: "filterBar", type: "ReactNode", description: "筛选行，一般是宿主的 DashboardFilterBar" },
        { name: "onSave", type: "(schema) => void | Promise<void>", description: "保存；reject 时留在搭建器并显示原因" },
        { name: "onSaveAsMine", type: "(schema) => void | Promise<void>", description: "「另存为我的」（编辑不能覆盖的公司看板时）" },
        { name: "onChange", type: "(schema: DashboardSchema) => void", description: "每次完成的改动（草稿 / 自动保存）" },
        { name: "sources", type: "readonly DashboardDataSource[]", default: "[]", description: "数据源（可分组、带记录数、未接入时写 disabledReason）" },
        { name: "metrics", type: "readonly DashboardMetricDef[]", default: "[]", description: "宿主的指标字典（标准指标：名称、版本、单位、公式）；单位 \"duration\" = 值是秒，卡片、图表、表格写「3.2 小时」/「1.5 天」（formatDuration）" },
        { name: "targets", type: 'readonly { id; name; period: "week" | "month" | "quarter" | "year"; unit? }[]', default: "[]", description: "宿主保存的目标（表上的每月目标…）：子弹图 / 汇总卡 / 实际 vs 目标 / 目标进度的「目标」可选其中一个，卡片只存 targetRef，取数时宿主按本期算值" },
        { name: "templates", type: "readonly WidgetTemplate[]", default: "[]", description: "组件库里的现成组件（标准指标组件、表格视图…）" },
        { name: "kinds", type: "readonly WidgetKind[]", default: "WIDGET_KINDS", description: "组件库和「样式」里可选的图表类型" },
        { name: "scope / scopeLabel", type: '"company" | "personal" / string', description: "名字旁的范围标签：公司 = 楼图标，我的 = 人图标" },
        { name: "permissionNote", type: "ReactNode", description: "工具条「?」里的权限说明（「你只能看到华东区的数据」）" },
        { name: "libraryCollapsed", type: "boolean", default: "false", description: "组件库一开始收成 56px 图标栏" },
        { name: "height", type: "number | string", default: "760", description: "整个搭建器的高度，各面板在里面自己滚" },
        { name: "phoneBreakpoint", type: "number", default: "760", description: "比这窄时变成只读预览 +「请在电脑上编辑」" },
      ],
    },
    {
      component: "TargetProgressCard（loadWidgetData 返回 kind: \"targetProgress\"）",
      rows: [
        { name: "value / target", type: "number | null", description: "本期实际值 / 目标值；target 为 null = 没设目标，卡上「还没有目标」+「设目标」" },
        { name: "period", type: "{ start; end; label? }", description: "目标的期（两头都算，本月 = 1 日到月底）：「按时间应完成」= 已过天数 ÷ 本期天数（今天算已过），「剩 N 天」" },
        { name: "targetNote", type: "string", description: "灰字说明是谁的目标（「全公司目标」），跟在期的名字后面" },
        { name: "unit / currency / digits", type: "string / string / number", description: "和其他卡一样的数值格式：单位、币种（CNY 或符号）、1 万以下的小数位；unit \"duration\" = 秒" },
      ],
    },
    {
      component: "DashboardView",
      rows: [
        { name: "widgets", type: "readonly DashboardWidget[]", description: "看板 JSON 里的组件（schema.widgets）" },
        { name: "context", type: "DashboardFilterValue", description: "当前筛选；每个组件实际用的筛选由 widgetFilterContext 算出" },
        { name: "load", type: "LoadWidgetData", description: "和搭建器同一个取数函数" },
        { name: "decor", type: "WidgetDecor", default: "{}", description: "卡头用的指标字典、来源名称、维度名称、「清空筛选」回调和「设目标」回调（onSetTarget）" },
        { name: "stacked", type: "boolean", default: "false", description: "按阅读顺序排成一列（手机）：数字卡两列，单数时最后一张占满" },
        { name: "label", type: "string", default: '"看板"', description: "整块区域的读屏名称" },
      ],
    },
  ],
};

export const chartsDocs: readonly ComponentDoc[] = [chartBasics, chartTypes, kpiCard, bulletProgress, funnelCohort, dashboardTabs, dashboardFilters, dashboardBuilder];
