import type { ComponentDoc } from "./types";

const comments: ComponentDoc = {
  slug: "comments",
  title: "评论",
  subtitle: "CommentThread · patchComment · removeComment · toggleReaction",
  group: "collab",
  depth: "deep",
  importFrom: "@adminui/react",
  summary: "记录、文档、知识库页面唯一的评论实现：默认只看未解决，@ 提到同事，4 种回应，一层回复，解决、编辑、删除都在一条评论上完成。",
  keywords: "comment thread mention reaction reply resolve 评论 讨论 @ 提到 回应 回复 解决 批注 划词",
  when: [
    "记录详情右栏、文档侧栏、知识库页面需要围绕一条数据讨论。",
    "要 @ 提到同事并通知他；要标记「已解决」把讨论收起来。",
    "文档里的划词评论：线程挂在一段原文上（quote），点线程让正文滚到那段。",
  ],
  whenNot: ["只记录「谁在什么时候改了什么」—— 用修改历史（LogTimeline / CellHistoryPopover）。", "即时聊天、群聊 —— 评论是异步讨论，不是聊天窗口。"],
  anatomy: [
    "标题行 48：「评论 8」+ 分段「全部 / 未解决 4 / @我 1」（不用漏斗图标）",
    "列表自己滚，日期分隔「今天 10月8日 / 昨天」；输入框贴底，回复时上方出「回复 某人 ×」",
    "一条评论：头像 24（按人取色）· 名字 13.5 / 时间 12 · 正文 14 / 1.6 · 附件 · 回应胶囊",
    "行内小工具（悬停 / 聚焦出现，触屏常显）：回应 · 回复 · 解决 · ⋯（编辑 / 删除）",
    "回复缩进一层，超过 1 条折成「展开 N 条回复」",
  ],
  states: [
    "默认「未解决」：已解决的线程不出现；在「全部」里整串收成一行灰条，点开看、可重新打开",
    "提到别人：主色浅底 + 深主色字；提到我：主色实底白字，一眼找到",
    "@ 弹层往上开、和输入框同宽；看不到这条记录的人灰掉并写原因，不能选",
    "编辑：就地复用输入框（Esc 取消、Ctrl + Enter 保存），显示「已编辑」",
    "删除：小气泡确认；有回复的留墓碑「评论已删除」，回复保留",
    "发送 / 保存失败：文字留着 + 原因 + 重试；空、加载、出错都有各自的状态",
  ],
  dos: [
    "侧栏里给 `fill`，让列表自己滚、输入框贴底；外层容器给确定的高度。",
    "`searchMentions` 由服务端只返回能看这条记录的人；看不到的给 `unavailable` 写原因。",
    "回应固定 4 种：赞 / 收到 / 看过 / 有疑问（图标 + 字），悬停看是谁点的。",
    "用 `canEdit` / `canDelete` 只放开自己的评论，服务端再校验一次。",
    "本地更新用 `patchComment` / `removeComment` / `toggleReaction`，不要自己递归改嵌套回复。",
  ],
  donts: [
    "不要让评论栏跟着详情一起滚：往下看字段时评论区会整块变空白。",
    "不要把输入框放在列表最后，评论一多要滚到底才能写。",
    "不要给每条评论常驻一排「回复 / 回应 / 解决」文字按钮；悬停才出，触屏常显一行小字。",
    "不要所有头像都画同一个主色圆，分不清谁是谁。",
    "回应不要只有图标和数字，看不出是什么、谁点的；也不要开放任意 emoji。",
    "不要再自己写一套评论列表和输入框。",
  ],
  a11y: [
    "行内小工具用透明度隐藏，按钮始终在 Tab 顺序里，键盘聚焦时出现。",
    "@ 弹层：↑ ↓ 选人、Enter 确定、Esc 关闭；Ctrl + Enter 发送。",
    "回应胶囊的说明（「收到：你、林晓」）键盘聚焦也能看到，读屏读作按钮 + 状态。",
    "触屏和 ≤ 760px 时动作常显，点击区域不小于 32px。",
  ],
  demos: [
    {
      id: "collab/comments-playground",
      title: "在线调试",
      description: "改右侧属性看默认分段、只读、按天分隔的效果。",
      height: 560,
      controls: [
        { name: "defaultFilter", label: "默认分段 defaultFilter", type: "select", options: ["open", "all", "mine", "resolved"], default: "open" },
        { name: "readOnly", label: "只读 readOnly", type: "boolean", default: false },
        { name: "groupByDay", label: "按天分隔 groupByDay", type: "boolean", default: true },
        { name: "title", label: "标题 title", type: "text", default: "评论" },
        { name: "placeholder", label: "输入框提示 placeholder", type: "text", default: "写评论，@ 提到同事" },
      ],
    },
    { id: "collab/comments-record", title: "记录详情右栏", description: "完整的发送、回复、回应、解决、编辑、删除；正文写「失败」演示发送失败。", height: 600 },
    { id: "collab/comments-quote", title: "文档划词评论", description: "quote 挂在原文上，activeId 高亮当前线程，onSelect 让正文定位。", height: 500 },
    { id: "collab/comments-states", title: "空、加载、出错与只读", height: 360 },
  ],
  props: [
    {
      component: "CommentThread",
      rows: [
        { name: "comments", type: "readonly CommentItem[]", description: "顶层评论（含 replies、reactions、resolved、quote、deleted）；数据和权限以服务端为准" },
        { name: "onSend", type: "(draft: CommentDraft) => Promise<void>", description: "发送评论 / 回复（draft.replyTo）；reject 一个 Error 保留文字并显示原因" },
        { name: "searchMentions", type: "(query: string) => Promise<readonly CommentPerson[]> | readonly CommentPerson[]", description: "@ 候选人；只给能看这条记录的人，看不到的带 unavailable 原因" },
        { name: "onReact", type: "(commentId: string, key: string, on: boolean) => void", description: "点回应；key 是 like / ok / seen / question" },
        { name: "onResolve", type: "(commentId: string, resolved: boolean) => void", description: "解决 / 重新打开（只对顶层评论）" },
        { name: "onEdit", type: "(id, body, mentions, attachments) => Promise<void>", description: "保存编辑；宿主设置 editedAt。reject 留在编辑状态" },
        { name: "onDelete", type: "(commentId: string) => Promise<void>", description: "气泡确认后调用；有回复时保留 deleted: true 的墓碑" },
        { name: "canEdit / canDelete", type: "(comment: CommentItem) => boolean", description: "谁能改 / 删；默认读评论上的 canEdit / canDelete 标记" },
        { name: "onUpload", type: "(files: File[]) => Promise<MediaItem[]>", description: "上传附件；不给时文件随 draft.files 交给宿主" },
        { name: "viewerId / viewerName", type: "string", description: "当前用户：出现「@我」分段、自己的提到实底、回应说明里写「你」" },
        { name: "filter / defaultFilter", type: '"open" | "all" | "mine" | "resolved"', default: '"open"', description: "标题行分段；给 filter 即受控，配 onFilterChange" },
        { name: "filters", type: "readonly CommentFilter[]", description: "显示哪些分段（默认 全部 / 未解决 / @我，加 resolved 出「已解决」）" },
        { name: "activeId / onSelect", type: "string | null · (id: string) => void", description: "划词评论：高亮当前线程；点线程让正文滚到原文" },
        { name: "fill", type: "boolean", default: "false", description: "撑满父容器高度：列表自己滚、输入框贴底" },
        { name: "readOnly", type: "boolean", default: "false", description: "没有输入框，也不能回应 / 解决 / 编辑 / 删除" },
        { name: "title", type: "string | null", default: '"评论"', description: "标题；null 隐藏整行（放在已经写着「评论」的标签页里）" },
      ],
    },
    {
      component: "CommentItem",
      rows: [
        { name: "author", type: "CommentPerson", description: "{ id, name, hint? }；头像颜色按 id 取" },
        { name: "createdAt / editedAt", type: "string", description: "ISO 时间；有 editedAt 显示「已编辑」" },
        { name: "body / mentions", type: "string · readonly CommentPerson[]", description: "纯文本；mentions 里的人的 @名字 会高亮" },
        { name: "reactions", type: "readonly CommentReaction[]", description: "{ key, count, mine?, names? }" },
        { name: "resolved / resolvedBy", type: "boolean · string", description: "只对顶层评论" },
        { name: "quote", type: '{ text: string; state?: "page" | "orphaned" }', description: "划词评论挂的原文；page = 整页评论，orphaned = 原文已删除" },
        { name: "deleted", type: "boolean", description: "墓碑：显示「评论已删除」，回复保留" },
      ],
    },
  ],
};

const shareDialog: ComponentDoc = {
  slug: "share-dialog",
  title: "分享弹窗",
  subtitle: "ShareDialog · GrantList · SharePicker · QrCode",
  group: "collab",
  importFrom: "@adminui/react",
  summary: "分享任何对象（记录、视图、表单、文件、文档、密码）都用这一个弹窗：一列从上到下，改了立刻生效，只有「复制」是主按钮。",
  keywords: "share dialog link password expiry qr grant permission 分享 链接 密码 有效期 二维码 授权 指定的人 权限名单",
  when: [
    "把一条记录、一个视图、一个文件发给公司外的人，或只给指定的人看。",
    "给页面 / 字段设授权名单：GrantList `mode=\"picked\"`（已选的人 + 搜索添加）或 `mode=\"list\"`（勾选列表，= SharePicker）。",
    "需要把链接变成二维码给手机扫：QrCode。",
  ],
  whenNot: ["公司内部的角色权限配置 —— 用权限页（TableAccessPanel 等）。"],
  anatomy: [
    "头部：「分享「对象名」」+ 类型 + 一行灰字（谁创建 · 改了立刻生效）",
    "链接行：链接（随机部分加重）+ 二维码图标按钮（点开出气泡）+「复制链接和密码」主按钮",
    "一句话摘要：「互联网上拿到链接和密码的人 · 可编辑 2 个字段 · 7 天后失效 · 还能打开 17 次」，跟着设置变",
    "谁能打开（选项卡片）→ 设置扁平列表：能做什么 · 访客能看的字段 · 密码 · 有效期 · 打开次数",
    "底栏：保存状态「保存中… → 已保存，立即生效」· 访问记录 · 「完成」（描边）",
  ],
  states: [
    "公司策略：顶上一条信息色细条；被禁的项照样摆出来、带锁、悬停写原因（「永久」→「公司最长 30 天」）",
    "保存失败：改回原值，底栏写「「30 天」没保存：网络中断 · 重试」，不弹框",
    "已暂停：顶部一条说明「访客打开会看到链接已失效，设置都留着」+ 恢复",
    "手机：底部弹层全高；复制按钮 44 高占满一行；分段撑满宽度",
  ],
  dos: [
    "每次改动立即保存：给 `onApply`（失败时 reject 一个写原因的 Error），弹窗自己处理回滚和重试。",
    "打开前用 `applySharePolicy` 把设置拉回公司策略内（去掉禁止对外的字段、强制密码、封顶有效期）。",
    "策略禁止的选项照样显示并写原因（`policy.audiences` / `requirePassword` / `maxExpiryHours`）。",
    "「指定的人」传 `people`，默认就是 GrantList picked；负责人放 `locked`，去不掉。",
    "令牌、密码校验、次数、到期、作废都在服务端；界面上的倒计时、剩余次数只是提示。",
  ],
  donts: [
    "不要在弹窗里套一张张卡片，一屏放不下要滚两屏。",
    "不要同时放三个主色实底按钮；只有「复制」是实心，「完成」描边。",
    "不要在链接下面再排一行胶囊把设置重复说一遍；用一句话摘要。",
    "不要让二维码常驻占地方，深色下也不要露一块刺眼的白方块；收进链接旁的图标按钮。",
    "不要为某个模块另做一套分享弹窗、一套「点保存才生效」的授权名单。",
  ],
  a11y: [
    "弹窗是 role=dialog，打开时焦点进第一个控件，关闭后回到「分享」按钮。",
    "分段控件用方向键切换；带锁的选项仍可聚焦，读屏读出禁用原因。",
    "一句话摘要是 aria-live，改了设置读屏能听到新的摘要；暂停状态用 role=status。",
    "QrCode 是 role=img，`label` 是它的名字；手机上能点的控件不小于 44px。",
  ],
  demos: [
    { id: "collab/share-dialog", title: "分享一条记录", description: "公司策略要求密码、最长 30 天；第一次选「30 天」演示保存失败。", height: 160 },
    { id: "collab/grant-list-picked", title: "授权名单：改了立刻生效", description: "第一次给「可管理」演示失败：改回原值、行内写原因 + 重试。", height: 400 },
    { id: "collab/share-picker-qr", title: "勾选名单与二维码", height: 340 },
  ],
};

const shareManager: ComponentDoc = {
  slug: "share-manager",
  title: "我的分享与访问记录",
  subtitle: "ShareManager · ShareAccessLog",
  group: "collab",
  importFrom: "@adminui/react",
  summary: "一个人发出去的所有分享链接：指标带 + 一行筛选 + 列表，点行展开谁在什么时候打开、下载、改了什么。",
  keywords: "share manager access log audit link list block ip 我的分享 分享管理 访问记录 打开记录 封禁 IP",
  when: [
    "「我的分享」页：查看、延长、暂停、作废自己发出去的链接。",
    "分享弹窗底栏的「访问记录」、文档的「访问记录」弹层：单独用 ShareAccessLog。",
  ],
  anatomy: [
    "指标带 4 格：有效 · 本周打开 · 即将到期 · 已作废",
    "筛选一行：搜索 · 类型 · 状态分段（有效 / 已暂停 / 已作废，带数量）",
    "列表 7 列：分享对象（图标 + 名字 + 类型）· 谁能打开（+ 能做什么标签）· 有效期 · 打开次数（数字 + 细进度条）· 最近打开 · 操作",
    "每行最多露 3 个操作：复制链接 · 改设置 · ⋯（访问记录 / 延长 / 暂停 / 重新生成 / 作废）",
    "访问记录：时间 · IP（中间打码）+ 城市 · 设备 · 事件标签 + 说明；编辑写「旧 → 新」",
  ],
  states: [
    "快到期：有效期变注意色",
    "风险行（密码连错、异常地区）：异常色浅底 + 「封这个 IP」小按钮；封过的写「已封」",
    "访问记录为空、没权限看 IP：各自一种空状态",
    "手机：表格换成卡片列表，每张卡的操作按钮 44 高",
  ],
  dos: [
    "筛选、分页由服务端做；`items` 只给当前页，`total` 给总数。",
    "IP 由服务端打码后再给（`maskIp`），界面不拿明文。",
    "作废先确认，说清楚「已经拿到链接的人再打开只会看到链接已失效，不能恢复」。",
    "访问记录展开在行下，和表格同宽，不再套一层卡片。",
  ],
  donts: [
    "不要让表格在 1440 宽（带侧栏）时横向溢出、把行尾按钮切掉。",
    "「能做什么」「事件类型」不要用五种描边胶囊；用同一套软标签。",
    "不要把状态筛选挤成搜索框旁的一个小分段，数量看不清。",
    "访问记录不要缩进再加横向滚动条。",
  ],
  a11y: [
    "访问记录是表格的展开行，展开按钮读作「远航精密制造 的访问记录」，内容紧跟在这一行后面。",
    "访问记录的类型筛选是分段控件（方向键切换）；「封这个 IP」失败时原因写在原处。",
    "数量与进度条同时给文字（「3 / 20 次」），不只靠长度表达。",
  ],
  demos: [
    { id: "collab/share-manager", title: "我的分享", description: "第一行默认展开访问记录；试试暂停、延长、作废。", height: 760 },
    { id: "collab/share-access-log", title: "单独的访问记录", height: 480 },
  ],
};

const sharedPage: ComponentDoc = {
  slug: "shared-page",
  title: "公开页",
  subtitle: "SharedPageShell · SharedRecordCard · SharedMediaCard · PasswordGate · SecretReveal · Watermark",
  group: "collab",
  importFrom: "@adminui/react",
  summary: "访客打开分享链接看到的页面：不在后台外壳里，顶栏一行、记录卡、资料卡、淡水印；密码门、一次性密钥和「链接已失效」各有固定样子。",
  keywords: "public share page visitor password gate secret one-time watermark expired 公开页 访客页 分享页 密码门 一次性密钥 阅后即焚 水印 链接已失效",
  when: [
    "分享出去的记录、文件给访客看（`variant=\"page\"`），可以开放少数字段让访客改。",
    "需要密码才能打开：PasswordGate；分享密码类信息、只看一次：SecretReveal（`variant=\"narrow\"`）。",
    "链接失效、不存在、错太多次：统一显示「链接已失效」。",
  ],
  whenNot: ["公开填写的表单 —— 用公开表单页（PublicForm / PublicPageLayout）。"],
  anatomy: [
    "顶栏一行：品牌 · 谁分享给你 · 灰色小标「7 天后失效 · 还能打开 17 次」· 唯一一个按钮",
    "记录卡：字段是灰底小方块；可改的白底 + 线框、悬停出铅笔；改过写「你 10:07 改过（原 10-12）」",
    "记录卡底部一条灰带：在这个页面你可以 看 / 改 / 下载 / ~~复制~~；联系人一行",
    "资料卡：和附件集同一套（4:3 缩略图、音频播放器、文件行）",
    "水印：备注色 14%，斜铺，不挡点击、不挡选中文字",
  ],
  states: [
    "密码门：居中 440 宽，格子 56 高等宽大字；输错抖一下 + 红字「还能再试 2 次」",
    "连错 3 次（`captchaAfter`）出滑块插槽，`captchaDone` 后才放行；5 次锁住",
    "一次性密钥：只留倒计时圈；密码一行大字 + 显示 / 复制；「我记好了，立即销毁」异常色描边",
    "链接已失效：一个图标 + 一句「请联系分享给你的人」，不说原因",
    "手机 ≤ 760px：一列，能点的东西不小于 44px",
  ],
  dos: [
    "PasswordGate 只管样子：在 `onSubmit` 里请服务端校验，失败时更新 `failed` / `error`。",
    "失效、不存在、错太多次统一显示同一个「链接已失效」，不暴露原因。",
    "SecretReveal 到点自动隐藏、可立即销毁（`onDestroy` 通知服务端）；剪贴板清空只是尽力而为，文案别承诺更多。",
    "可改字段的保存 reject 时写原因；访客的每次修改都通知分享人、写访问记录。",
  ],
  donts: [
    "水印不要太重，尤其深色下，会压住字段和按钮。",
    "顶栏不要放三个长得一样的描边胶囊，信息和按钮分不清。",
    "不要让可改和不可改的字段长得差不多，只靠一个绿字「可改」区分。",
    "密码门的按钮禁用时不要用半透明主色，像能点；输错和要滑块都要有明确状态。",
    "一次性密钥不要倒计时圈 + 进度条重复两遍；销毁按钮不要像普通描边按钮。",
  ],
  a11y: [
    "密码格子是一组输入框，粘贴整串自动分格；输错的说明是 role=alert，读屏会读出剩余次数。",
    "水印 aria-hidden，读屏不读；打印也会带上。",
    "一次性密钥隐藏、已复制都用 role=status 告知，不逐秒播报倒计时。",
    "密码字符不上色，靠等宽字体区分 0 / O、1 / l。",
  ],
  demos: [
    { id: "collab/shared-visitor-page", title: "访客页", description: "下次跟进、备注可改；水印默认开。", height: 720, bleed: true },
    { id: "collab/password-gate", title: "密码门 → 一次性密钥", description: "密码 7K2Q；输错 3 次出滑块。", height: 680, bleed: true },
    { id: "collab/shared-expired", title: "链接已失效", height: 440, bleed: true },
    { id: "collab/watermark", title: "水印", height: 300 },
  ],
};

const media: ComponentDoc = {
  slug: "media",
  title: "附件、大图与上传",
  subtitle: "AttachmentGallery · MediaThumb · MediaLightbox · UploadQueue · UploadDropZone · UploadQueueList · useUploadQueue",
  group: "collab",
  importFrom: "@adminui/react",
  summary: "一条记录的图片、视频、音频、文件放进附件集；点开是整屏沉浸的大图；多文件上传有总进度、每行状态、失败重试和断点续传。",
  keywords: "attachment gallery thumbnail lightbox image preview upload queue drop zone file 附件 图片 视频 缩略图 大图 预览 灯箱 上传 拖放 断点续传",
  when: [
    "一条记录 / 一个字段的附件：面板里 `mode=\"tiles\"`，记录详情的附件行 `mode=\"strip\"`。",
    "自己排缩略图（看板卡片、评论附件）时：MediaThumb + MediaLightbox。",
    "一次传多个大文件：UploadQueue（或 useUploadQueue + UploadDropZone + UploadQueueList 自己摆）。",
  ],
  whenNot: ["表单里只传一个文件 —— 用 UploadField。"],
  anatomy: [
    "缩略图：4:3、圆角 8、1px 线；名字一行省略但保住扩展名；悬停出勾选框和 ⋯",
    "选中条：主色浅底「已选 2 个 · 下载 · 取消」",
    "大图：媒体舞台色整屏；上栏名字 + 第几个 + 下载 / 新窗口 / 信息 / 关闭；底部浮动工具条；两侧翻页；缩略图条",
    "上传队列：总进度一条 + 每行（等待 / 上传中剩几秒 / 失败写原因 + 重试 / 完成），底部 2px 进度线",
  ],
  states: [
    "有权限限制（`lock`）：锁写在第二行灰字里，不挤名字",
    "看不了（`lock.denied`）：缩略图模糊 + 锁，不能打开、不能勾选、不进批量下载",
    "空：只有一个大拖放区（选择文件 / 拍照 / 录音）；有文件时拖放区收成一行细条",
    "没有缩略图：中性底 + 类型图标，不画插画；文件类型字不上色",
    "手机：两列缩略图、勾选框常显；大图左右滑，工具条在底部",
  ],
  dos: [
    "文件地址、签名下载、打包下载、Office 在线预览都由宿主给：`url` / `thumbUrl` / `previewUrl` / `onDownload`。",
    "上传适配器收 `{ signal, onProgress, key, attempt }`；失败 reject 一个写原因的 Error，用 `key` 找回会话续传。",
    "要在缩略图上显示进度，把队列条目映射成 `MediaItem.upload`。",
    "大小一律用 `formatBytes`（1024 进位）；类型用 `fileTypeName`，不露 MIME。",
    "媒体上的字和遮罩只用 `--aui-on-media` / `--aui-media-scrim*`。",
  ],
  donts: [
    "不要让锁标和文件名挤在一行，两个都看不全。",
    "不要在没有文件时同时出现拖放区和「还没有文件」两个虚线框。",
    "大图预览不要做成带白边的弹框里再套一张圆角卡（框中框），也不要只有一个旋转按钮。",
    "不要只在缩略图上显示百分比；要有队列总览，失败、暂停有统一的样子。",
    "不要手写缩略图、播放器、灯箱或上传进度。",
  ],
  a11y: [
    "大图：← → 切换，+ − 缩放，0 适应，Esc 关闭；关闭后焦点回到点开的缩略图。",
    "勾选框是真的 checkbox，悬停才显示但键盘聚焦时可见。",
    "拖放区可聚焦，Enter 选择文件；聚焦时可直接粘贴截图。",
    "上传进度用 role=progressbar 并给文字「46% · 还要 10 秒」。",
  ],
  demos: [
    { id: "collab/attachment-gallery", title: "附件集", description: "网格 / 列表切换、选择下载、有权限限制、点开整屏大图。", height: 620 },
    { id: "collab/media-lightbox", title: "缩略图 + 大图", description: "点附件行里任意一个打开大图（默认展开「信息」栏）。", height: 280 },
    { id: "collab/upload-queue", title: "上传队列", description: "点「模拟添加 3 个文件」；带「失败」的会在 60% 断网，重试从断点继续。", height: 360 },
    { id: "collab/attachment-strip", title: "附件行与空状态", height: 360 },
  ],
};

const audio: ComponentDoc = {
  slug: "audio",
  title: "音频播放与录音",
  subtitle: "AudioPlayer · AudioRecorder · HoldToTalk · useAudioRecorder",
  group: "collab",
  importFrom: "@adminui/react",
  summary: "一行的音频播放器（表格格子里用迷你版）、带大计时和实时波形的录音卡、手机上的按住说话；麦克风打不开时说清楚怎么办。",
  keywords: "audio player waveform mini recorder microphone hold to talk voice 音频 播放器 波形 录音 麦克风 按住说话 语音",
  when: [
    "通话录音、语音留言、现场口述：AudioPlayer；表格的录音列：`variant=\"mini\"`。",
    "在页面里录一段（拜访、会议）：AudioRecorder，`onDone` 拿到 Blob。",
    "手机上的语音输入：HoldToTalk（≥ 44px，上滑取消）。",
  ],
  whenNot: ["要看文字稿、按说话人回放 —— 用录音文字稿（TranscriptViewer）。"],
  anatomy: [
    "播放器一行：播放键 36 主色实底圆 · 名字 / 来源 · 波形（播过的主色、没播的灰）· 时间 · 倍速 · 转文字 / 下载",
    "迷你播放器 24 高放进 32–40 的行，播放中整块主色浅底",
    "录音卡：大计时 34px 等宽 · 实时波形 · 暂停 / 结束并保存 / 取消；结束后变成播放器",
    "按住说话：44 高、圆角 12；按下变录音红 + 上方气泡（计时 + 波形 + 上滑取消）",
  ],
  states: [
    "加载中：波形呼吸；出错：写原因 + 能做什么（「这个格式浏览器放不了，下载后用手机播放」）",
    "录音中：录音红只给大圆键、录音中小红点和字、录音波形",
    "麦克风打不开：两步说明（地址栏改权限、谁在占用）+「再试一次」+「改成上传录音文件」，英文原因放最后一行小字",
    "按住说话上滑：灰底红字「松开取消」；太短（< 0.6 秒）自动丢弃并提示",
  ],
  dos: [
    "波形 `peaks` 由服务端算好给（任意长度，组件降采样）；没有就是普通进度条。",
    "同一页同时只放一个在播。",
    "`notes` 只写宿主真的做到的事（例如「只在这个页面录」）。",
    "点大红键才请求麦克风；不要一进页面就弹权限框（除非用户刚点了「录音」，用 `autoStart`）。",
  ],
  donts: [
    "不要让播放键、倍速、「转文字」三种描边按钮挨在一起。",
    "迷你播放器不要只有十几根线或一条直线，「+2」也要说明是什么。",
    "不要在计时下面画一条红色虚线，像出错。",
    "麦克风打不开时不要直接显示浏览器的英文原话。",
    "录音红只用于录音，别处不要拿红色当强调。",
  ],
  a11y: [
    "波形是 slider：← → 每次 5 秒，读屏读出当前时间 / 总时长。",
    "倍速按钮读出当前倍速；播放键在播放 / 暂停间切换 aria-label。",
    "按住说话也能用键盘：按住空格或 Enter 录音，松开发送，Esc 取消。",
  ],
  demos: [
    { id: "collab/audio-player", title: "播放器与迷你播放器", description: "第二个是格式不支持时的出错样子。", height: 320 },
    { id: "collab/audio-recorder", title: "录音与按住说话", description: "演示只在点「开始录音」后才请求麦克风；没有麦克风会显示说明而不是报错。", height: 360 },
  ],
};

const transcript: ComponentDoc = {
  slug: "transcript",
  title: "录音文字稿",
  subtitle: "TranscriptViewer",
  group: "collab",
  importFrom: "@adminui/react",
  summary: "录音 + 按说话人分段的文字稿 + AI 标注：波形按说话人上色，点时间跳转，文字跟着播放滚动，敏感信息打码、留痕查看。",
  keywords: "transcript recording speaker diarization waveform annotation summary mask export 文字稿 转写 录音 说话人 标注 摘要 打码 导出 会议纪要",
  when: [
    "客户拜访、电话、会议、面试的录音需要回放和检索。",
    "AI 已经分好说话人、标出需求 / 预算 / 顾虑，需要人对照原话确认。",
  ],
  whenNot: ["只是播放一段语音 —— 用 AudioPlayer。"],
  anatomy: [
    "标题行：标题 · 元信息 · 搜索 · 导出 ⌄ · ⋯",
    "播放条（吸顶）：说话人图例（色块 + 名字 + 角色 + 占比）→ 波形 + AI 标注小钉 → 控制一行（后退 15 · 播放 · 前进 15 · 时间 · 倍速，开关在右）",
    "文字稿：时间（点了跳）· 头像（说话人色）· 名字 / 角色 · 正文；当前句主色浅底",
    "右栏：AI 摘要 + 时间点（点了跳）+ 说话占比 + 标注统计",
  ],
  states: [
    "没播的段 35% 淡、播过的满色；静默段是线色，长静默有分隔且可跳过",
    "打码值灰底等宽 + 眼睛；查看后一段时间自动重新打码",
    "没有音频地址或加载失败：文字稿照常可读",
    "手机：开关收进 ⋯，控制条一行",
  ],
  dos: [
    "宿主给已分说话人、已打码的 `segments`；`onReveal` 由服务端鉴权并记下谁看过。",
    "说话人颜色用分类色（`slot`），标注分类只用主色族 tone，不用状态色。",
    "导出收进标题行的下拉，写清楚「导出也是打码后的」（`exportNote`）。",
    "AI 摘要里的要点带时间，点了跳到原话。",
  ],
  donts: [
    "不要在波形上方排一行和波形对不齐的标注胶囊，选中还变成实心按钮。",
    "说话人颜色不要高饱和，满屏红蓝绿竖条，深色下更刺眼。",
    "不要把三个开关和播放键挤在一行，手机上排成三行。",
    "导出不要单独占一大块卡片，比 AI 摘要还显眼。",
  ],
  a11y: [
    "波形是 slider：← → 前后 5 秒，PageUp / PageDown 前后 1 分钟，Home / End 到头尾；空格播放 / 暂停。",
    "文字跟着播放滚动但不抢焦点；「跟着滚动」可以关掉。",
    "打码值旁的「查看」是按钮，查看会留痕，过一会儿自动重新打码。",
  ],
  demos: [{ id: "collab/transcript-viewer", title: "季度复盘录音", description: "能播；点时间跳转，点眼睛查看打码的手机号。", height: 760 }],
};

const history: ComponentDoc = {
  slug: "history",
  title: "修改历史与回退",
  subtitle: "CellHistoryPopover · LogTimeline · TimeMachineDialog · ViewOverrideBar · ChangeValue",
  group: "collab",
  importFrom: "@adminui/react",
  summary: "一格的版本、一批操作的撤回、整张表回到某个时间点、视图的个人改动——所有「改前 → 改后」都用同一种写法。",
  keywords: "history version undo rollback time machine operation log audit change diff 修改历史 版本 撤回 回滚 时光机 操作记录 改前改后 个人视图",
  when: [
    "看一格（或整条记录）被谁改过、恢复到旧值：CellHistoryPopover。",
    "批量操作（粘贴、批量改、导入、一次自动化）的撤回：LogTimeline `variant=\"operations\"`。",
    "整张表退回到某个时间点：TimeMachineDialog。用户改了共享视图：ViewOverrideBar（`@adminui/react/grid`）。",
  ],
  anatomy: [
    "ChangeValue：旧值备注色删除线 → 小箭头 → 新值加粗；「空」不划线",
    "单元格历史气泡 380 宽：竖线时间轴，每个版本「旧 → 新」+ 谁 / 何时 / 来源（灰色小标）；当前版本主色点 +「当前」",
    "操作记录：「做了什么」占最宽一列、两行写全，编号放第二行灰字；类型用软标签；影响范围；撤回",
    "表时光机：日期 / 时间触发器 + 快捷分段 → 时间轴（图例在轴外）→ 指标带（改回 / 加回 / 移除 / 冲突）→ 冲突表",
    "视图个人设置条：一行「你改了「续约看板」的分组、列宽，只对你生效」+ 恢复 / 另存 / 保存给所有人",
  ],
  states: [
    "恢复：只在悬停那一行出现，点了就地确认「恢复成 ¥450,000？会记成一个新版本」",
    "撤回冲突：别人后来又改过的格子默认保留别人的；可整批改成「一起退回」或逐格选",
    "超过撤回窗口（默认 3 天）：整组灰掉，按钮禁用 + 悬停说明「只能逐条恢复」",
    "时光机没有改动：不给确认，写清楚「这个时间点之后没有可回退的修改」；预览中显示「正在算」",
  ],
  dos: [
    "所有改前改后都用 `ChangeValue`，包括宿主自己的场景；不拼红绿底色。",
    "撤回的冲突选择随 `onUndo(decisions)` 交给服务端，服务端逐格重新校验、写审计。",
    "表时光机先 `onPreview` 拿到预览才能确认；回滚本身也是一次可以再撤回的操作。",
    "恢复走 `onRestore`，由服务端记成新版本；只给 `anchorRect` 时宿主负责把焦点放回格子。",
  ],
  donts: [
    "不要给每个旧版本常驻一个「恢复」按钮，一列按钮很吵，更不要有主色实底的。",
    "记录修改历史不要只写「修改了「状态」」，要直接写出改成了什么。",
    "操作记录的「做了什么」列不要太窄被截断，右边却空一大块。",
    "表时光机改动为 0 时不要还能点确认；轴上的点不要挤成一团。",
  ],
  a11y: [
    "ChangeValue 读作「A 改成 B」；删除线不是唯一信号。",
    "历史气泡 Esc 关闭、焦点回到格子；恢复确认可用键盘完成。",
    "时间轴是 slider：方向键微调、PageUp / PageDown 跳一天；轴上的操作点也能聚焦，← → 在操作之间跳。",
  ],
  demos: [
    { id: "collab/cell-history", title: "单元格修改历史", description: "悬停一行出「恢复」；切到「整条记录」看所有字段。", height: 700 },
    { id: "collab/log-operations", title: "操作记录与撤回", description: "第一条展开了样例格子，其中一格后来被别人改过（冲突）。", height: 620 },
    { id: "collab/time-machine", title: "表时光机", height: 160 },
    { id: "collab/view-override-change-value", title: "视图个人设置条与改前改后", height: 420 },
  ],
};

const aiReview: ComponentDoc = {
  slug: "ai-review",
  title: "AI 审核",
  subtitle: "SuggestionReview · SourcedAnswer · CitationChips · PromptEditor · VersionList · CompareGrid",
  group: "collab",
  importFrom: "@adminui/react",
  summary: "AI 的结果先审后写：建议改字段要人点「采用」，给客户说的话每句对上出处；提示词有版本、能和已发布版对比、发布前用历史样本试跑。",
  keywords: "ai suggestion review citation source prompt editor version compare llm 建议 采用 出处 引用 提示词 版本 对比 试跑",
  when: [
    "AI 从一次沟通里建议更新字段（阶段、金额、下一步）：SuggestionReview。",
    "AI 给出的回答、话术需要标出处：SourcedAnswer / CitationChips。",
    "运营调整「怎么分析」的提示词：PromptEditor + VersionList，发布前用 CompareGrid 试跑。",
  ],
  anatomy: [
    "AI 标记：主色浅底「AI」小标 + sparkles 图标，全站一种",
    "建议一行：字段 · 旧 → 新 · 引号 + 客户原话 + 「▶ 04:10」跳录音 · 采用（描边主色字）/ 忽略（幽灵）",
    "有出处的回答：句末 [1] [2] 小方块（悬停看原文）+ 出处列表；可复制、可折叠",
    "提示词：行号 · 正文（不用等宽）· 变量信息色小标 · 加的行主色浅底、删的行删除线 · 字数 / token",
    "版本：当前在用的版本号主色实底；对比 / 回退悬停才出",
  ],
  states: [
    "已采用：整行主色浅底 +「已采用 · 撤销」；忽略：收成一行灰字 +「恢复」",
    "还剩几条时右上出「剩下 3 条全部采用」",
    "没有出处的句子：注意色波浪下划线 +「已拦下，复制时不会带上」",
    "试跑对比：有问题的格子标出来（编造 / 变差 / 变好）+ 一句结论",
  ],
  dos: [
    "AI 只给建议，点了采用才写进记录；修改历史的来源写「AI 建议 · 某人采用」。",
    "知识库里没有的价格、优惠、承诺不出现；用 `missingCitations` 查编造的编号。",
    "改提示词只改「怎么分析」，输出字段格式由宿主固定。",
    "回退 = 生成新版本，不删旧版本；token 有网关计数就传 `countTokens`，没有就显示「约」。",
  ],
  donts: [
    "不要每行一个主色实底「采用」，一屏四个实心按钮。",
    "证据时间和客户原话不要分在不同行，引号也要统一。",
    "提示词里加的行不要用异常色浅底（像错误），草稿标签也不要用注意色。",
    "不要只在旁边标一个红色胶囊说「没有出处」，却不说复制时会不会带上。",
  ],
  a11y: [
    "采用 / 忽略按钮写明字段（「采用：阶段」），状态变化用 aria-live 播报。",
    "出处编号是按钮，读作「出处 1：管理员手册 …」。",
    "提示词编辑区是普通 textarea，变量插入菜单可用键盘操作。",
  ],
  demos: [
    { id: "collab/suggestion-review", title: "建议更新与有出处的回答", height: 640 },
    { id: "collab/prompt-editor", title: "提示词与版本", height: 560 },
    { id: "collab/compare-grid", title: "试跑对比", height: 460 },
  ],
};

const approval: ComponentDoc = {
  slug: "approval",
  title: "审批",
  subtitle: "ApprovalList · ApprovalDetail · ApprovalProgress · ApprovalProgressCard · filterApprovals",
  group: "collab",
  importFrom: "@adminui/react",
  summary: "一切审批（折扣、请假、报销、权限申请）用同一套：列表 + 详情 + 竖线审批进度；驳回必须写原因，记录详情里嵌进度卡。",
  keywords: "approval workflow request approve reject withdraw steps leave discount expense 审批 申请 批准 驳回 撤回 审批流 请假 折扣 报销",
  when: [
    "审批中心：我的申请 / 待我审批 / 全部，配 ListDetailLayout（手机列表 → 详情两步）。",
    "记录详情里显示这条记录的审批进度：ApprovalProgressCard。",
  ],
  whenNot: ["设计审批路线（谁审、按什么条件）—— 用规则列表（RuleList）。"],
  anatomy: [
    "列表行两层 56–64：头像 · 谁 · 类型标签 · 申请什么 · 理由；右侧步骤小点（8px 圆 + 12px 线）+ 多久前",
    "详情：标题 + 状态小标 → 理由 / 期限 → 灰底一块「批准后会怎样」（宿主 `renderSubject`）",
    "竖线审批进度：完成主色勾、当前注意色钟、驳回异常色叉 + 原因引用、没走到灰色虚线圈",
    "意见框 → 驳回（描边异常色）/ 批准（主色实心）",
  ],
  states: [
    "驳回不写原因：意见框变红 + 一行说明，不提交",
    "提交失败：意见保留，写原因",
    "申请人看自己的待审申请：有「撤回」（先确认）",
    "空：「没有等你审批的申请」",
  ],
  dos: [
    "数据用 `ApprovalRequest`：申请时的快照放 `summary`，用 `renderSubject` 画出来。",
    "审批人由服务端从角色 / 上级解析好放进 `steps`；`mode` 写清是任一人还是全部人。",
    "谁能批 / 撤回只是显示（`canDecide` / `canWithdraw`），服务端再判；驳回原因服务端再拦一次。",
    "组件里不写业务词：「批准后能做什么」由宿主放进 `renderSubject`。",
  ],
  donts: [
    "不要把两层字挤进 40px 行，状态胶囊压到行线。",
    "审批进度不要只写一句「第 1 / 2 级：部门负责人（待审批）」。",
    "批准 / 驳回不要是一排文字按钮；批准前要看得到影响。",
    "页面上不要两排样子不同的标签，也不要一排十几个标签；第二级用分段。",
  ],
  a11y: [
    "列表每一行是一个按钮，Tab 依次聚焦、Enter 打开详情；当前选中的一行带 aria-current。",
    "驳回原因缺失时意见框 aria-invalid，错误说明用 aria-describedby 关联到输入框。",
    "进度步骤用文字写明状态（「已批准」「等待中」），不只靠颜色和图标。",
  ],
  demos: [
    { id: "collab/approval-center", title: "审批中心", description: "你是销售总监林晓；驳回必须写原因，意见写「失败」演示提交失败。", height: 640 },
    { id: "collab/approval-progress", title: "进度卡与审批进度", height: 520 },
  ],
};

export const collabDocs: readonly ComponentDoc[] = [comments, shareDialog, shareManager, sharedPage, media, audio, transcript, history, aiReview, approval];
