import type { ComponentDoc } from "./types";

const dataTable: ComponentDoc = {
  slug: "data-table",
  title: "数据表格",
  subtitle: "DataTable · RowActionBar · BulkActionBar · QueryBar · CellText · CellTags",
  group: "data",
  depth: "deep",
  importFrom: "@adminui/react",
  summary: "后台管理主列表的默认组件：每行一样高、操作直接露在行上、勾选后底部浮出批量条、页码或游标分页。手机上每行自动变成一张卡片。",
  keywords: "data-table datatable table list 表格 数据表格 列表 分页 排序 勾选 批量 行操作 行高 骨架 空状态 cursor pagination bulk",
  when: [
    "同类记录多、会增长，用户要找、筛、排序，并对每行做操作（编辑、转交、删除）。",
    "日志、流水这类上万条的数据：DataTable + 服务端分页（页码或游标）。",
    "十几行一次拿全的配置表：pagination={{ mode: \"all\" }}，页脚只写「共 N 条」。",
  ],
  whenNot: [
    "主要工作是在格子里录入、粘贴、自己分组统计 —— 用多维表格 BitableGrid。",
    "卡片、弹窗里 20 行以内的小表 —— 用 CompactTable。",
    "按时间发生的事 —— 用 ActivityFeed；一个对象的属性 —— 用 DescriptionList。",
  ],
  anatomy: [
    "表头 40px：12px / 600 次要色，和多维表格同一套；排序箭头悬停才出，多列排序带序号",
    "勾选列：部分勾选时表头半选「−」",
    "数据行：三档行高 紧凑 40 / 宽松 48（默认）/ 两行 56，格子放不下就省略号 + 悬停全文",
    "操作列（kind: \"actions\"）：RowActionBar 放得下就露、最多 3 个，其余进 ⋯；横向滚动时固定在右侧",
    "批量浮条 BulkActionBar：底部居中「已选 N 条 · 动作 · ✕」，不推动表格",
    "分页脚：左「共 168 条」（选中时「已选 2 / 共 168 条」），右「每页条数 + 页码」；游标分页写「已显示 1–20 条」",
  ],
  states: [
    "加载：保留表头，骨架行和列宽一致（列的 skeleton 形状）；条数写「—」，10 秒后「加载比较慢… · 重试」",
    "刷新（refreshing）：旧数据留着、略变淡，顶部 2px 进度条",
    "空表 / 筛选无结果：emptyKind 区分「还没有」和「没找到」，emptyAction 给下一步",
    "出错：一句人话 + 「错误详情」（请求号可复制）+ 重试",
    "悬停行：浅底，操作按钮从次要色变主色；选中行：主色浅底，操作照常可点",
    "手机（≤ 760px）：每行一张卡片 —— 标题 + 状态、灰字一行、勾选和 ⋯ 都在卡上；批量浮条贴屏幕底",
  ],
  dos: [
    "名称、备注用 truncate 或 CellText（主文字 + 一行灰字）；编号、金额、状态不截断。",
    "数字列加 numeric：右对齐、等宽数字；单位写在列标题里（「合同金额（元）」）。",
    "操作列一律用 RowActionBar，按常用顺序给全部操作；危险操作默认在 ⋯ 里。",
    "不能用的操作给 disabledReason：它不占按钮位，在 ⋯ 里带着原因。",
    "列表页用 ResourcePanel 包住：标题 + 条数 + 主按钮，QueryBar 放 filters。",
    "数据交给 useDataSource / useCursorDataSource，表格本身只负责显示，不切片、不算总数。",
  ],
  donts: [
    "不要把名字和长编号硬塞进 40px 一行 —— 两行信息用 rowHeight=\"medium\"。",
    "同一个后台不要出现两套行高；用三档预设，不自己写 padding。",
    "不要把批量操作栏插在筛选和表格之间：一出现整张表往下跳。",
    "部分勾选时表头不要显示全勾；选中后不要把操作列整列变灰。",
    "分页脚不要只写「第 1 页」不说总数；当前页不要用比主按钮还抢眼的实心色块。",
    "手机上不要只露两列再让人横滑找操作 —— 用默认的卡片模式。",
  ],
  a11y: [
    "caption 必填：作为表格的可访问名称。",
    "RowActionBar 的 label 写成「某某的更多操作」，读屏能区分是哪一行。",
    "可排序表头是按钮，带 aria-sort；批量浮条是 role=\"toolbar\"，← → 在按钮间移动，Esc 清空选择。",
    "已选条数用 aria-live 播报；行首展开按钮的名称来自 expandRecord.label。",
    "状态不只靠颜色：标签都有文字。",
  ],
  demos: [
    {
      id: "data/data-table-playground",
      title: "在线调试",
      description: "改右侧属性看行高、斑马纹、各种状态、勾选和两种分页；把窗口拉窄看手机卡片。",
      height: 560,
      controls: [
        { name: "rowHeight", label: "行高 rowHeight", type: "select", options: ["default", "short", "medium", "tall"], default: "default" },
        { name: "state", label: "状态", type: "select", options: ["数据", "加载中", "出错", "空"], default: "数据" },
        { name: "paging", label: "分页 pagination.mode", type: "select", options: ["page", "cursor"], default: "page" },
        { name: "mobile", label: "手机 mobile", type: "select", options: ["cards", "table"], default: "cards" },
        { name: "selectable", label: "可勾选 selected", type: "boolean", default: true },
        { name: "zebra", label: "斑马纹 zebra", type: "boolean", default: false },
      ],
    },
    { id: "data/data-table-list-page", title: "标准列表页", description: "ResourcePanel + QueryBar + DataTable：搜索、阶段筛选、排序、勾选后批量浮条、操作列、记录详情。", height: 620 },
    { id: "data/data-table-states", title: "加载、空、无结果、出错", height: 360 },
    { id: "data/data-table-grouping", title: "两行行高、分组与游标分页", height: 560 },
  ],
  props: [
    {
      component: "DataTable",
      rows: [
        { name: "rows / columns / rowKey", type: "readonly T[] / readonly Column<T>[] / (row) => string", description: "必填。rows 是当前页的数据" },
        { name: "caption", type: "string", description: "必填：表格的可访问名称" },
        { name: "pagination", type: '{ mode: "page", total, page, pageSize, onPageChange, onPageSizeChange, pageSizes? } | { mode: "cursor", pageIndex, pageSize, canPrev, canNext, onPrev, onNext, onPageSizeChange } | { mode: "all" }', description: "必填。page 有真实总数；cursor 没有总数和页码；all 是一次拿全的短表" },
        { name: "sort / onSortChange", type: '{ key: string; direction: "asc" | "desc" }', description: "单列排序；多列用 sorts / onSortsChange（数组顺序 = 优先级），两种只用一种" },
        { name: "selected / onSelectionChange", type: "readonly string[] / (ids: string[]) => void", description: "受控勾选；isRowSelectable(row) 决定哪些行能勾" },
        { name: "bulkActions", type: "readonly BulkAction[]", description: "勾选后底部浮条的按钮 { key, label, icon?, onSelect, danger?, disabled?, disabledReason? }；bulkNote 写小字备注" },
        { name: "rowHeight", type: '"short" | "medium" | "tall" | "extraTall" | "auto"', description: "40 / 56 / 88 / 120px；不传按密度（宽松 48）。auto 让内容撑高，只给十几行的小表" },
        { name: "loading / refreshing", type: "boolean", description: "首次加载 = 表头 + 骨架行；refreshing = 旧数据 + 顶部进度条" },
        { name: "error / errorDetails / onRetry", type: "string / string / () => void", description: "出错的一句话、可复制的详情（请求号）、重试" },
        { name: "emptyKind / emptyLabel / emptyAction", type: '"empty" | "no-results" / string / ReactNode', description: "区分「还没有」和「筛选没结果」，给下一步按钮" },
        { name: "expandRecord", type: "ExpandRecordOptions<T>", description: "行首图标打开记录详情：{ title?, description?, label?, fields?, layout?, level?, url? }" },
        { name: "expandable / grouping", type: "{ expanded, onExpandedChange, render, label } / { by, header, collapsed?, onCollapsedChange? }", description: "行内展开；整行宽、可折叠的分组标题" },
        { name: "mobile", type: '"cards" | "table"', default: '"cards"', description: "≤ 760px 每行一张卡片；table 保留横滑表格" },
        { name: "zebra / maxHeight / toolbar", type: "boolean / number / ReactNode", description: "斑马纹；有界滚动 + 固定表头；表格上方的工具区" },
      ],
    },
    {
      component: "Column<T>",
      rows: [
        { name: "key / title / render", type: "string / string / (row, { selected }) => ReactNode", description: "必填" },
        { name: "width / minWidth / maxWidth", type: "number", description: "列宽；截断的列必须给 width 或 maxWidth" },
        { name: "truncate", type: "(row) => string", description: "单行省略 + 悬停全文；返回全文，省略号永远能看到原文" },
        { name: "wrap", type: "boolean", description: "在行的行数内换行，放不下省略号，不撑高行" },
        { name: "numeric / align", type: 'boolean / "left" | "right"', description: "数字右对齐、等宽数字" },
        { name: "sortable", type: "boolean", description: "表头可点排序" },
        { name: "kind", type: '"data" | "actions"', default: '"data"', description: "actions = 操作列：固定在右、手机卡片上只露 ⋯" },
        { name: "mobile", type: '"primary" | "status" | "meta" | "hidden"', description: "手机卡片上的位置：标题 / 标题后的标签 / 灰字行 / 只在详情里" },
        { name: "skeleton", type: '"text" | "tag" | "person" | "number" | "action"', description: "首次加载时这一列骨架的形状" },
        { name: "detail", type: "(row) => ReactNode", description: "记录详情里这一列的完整显示" },
      ],
    },
    {
      component: "RowActionBar",
      rows: [
        { name: "actions", type: "readonly RowAction[]", description: "{ key, label, onSelect, icon?, destructive?, disabled?, disabledReason?, menuOnly?, ariaLabel? }" },
        { name: "max", type: "number", default: "3", description: "最多露出几个按钮，其余进 ⋯；灰掉的操作不占位" },
        { name: "label", type: "string", default: '"更多操作"', description: "⋯ 按钮和菜单的名称，写成「某某的更多操作」" },
      ],
    },
  ],
};

const grid: ComponentDoc = {
  slug: "grid",
  title: "多维表格",
  subtitle: "BitableGrid · useGridView · GridToolbar · ViewOverrideBar",
  group: "data",
  depth: "deep",
  importFrom: "@adminui/react/grid",
  summary: "像电子表格一样用的表格：格子里直接编辑、复制粘贴、填充、撤销，自己筛选、分组、排序、统计、填色。可选子路径，按需加载。",
  keywords: "bitable grid spreadsheet 多维表格 电子表格 视图 筛选 分组 排序 统计 填色 冻结 填充柄 单元格编辑 tanstack",
  when: [
    "用户的主要工作是在格子里录入、修改、粘贴数据，并自己分组统计（客户台账、项目跟踪、库存）。",
    "几千条以内用 rows（前端算）；上万条用 dataSource（服务端分块、无限滚动）。",
    "卡片里要格内编辑的小表：height=\"auto\" + toolbar={false} + summary={false}。",
  ],
  whenNot: [
    "后台管理主列表、每行要点按钮操作 —— 用 DataTable，操作别被收进菜单。",
    "只读的小表 —— 用 CompactTable；弹窗里的小表不要做成多维表格。",
  ],
  anatomy: [
    "视图标签（ViewTabs，下划线选中）+ 工具栏，固定两行，换一张表按钮位置也不跳",
    "工具栏左：字段 · 筛选 · 分组 · 排序 · 行高 · 填色 · 撤销重做；生效中 = 主色浅底 + 数量徽标",
    "工具栏右：快捷筛选 toolbarQuick · 搜索（可收成图标）· 条数 · ⋯（表设置、权限、操作记录、导出）· 一个主按钮",
    "行号列 48px：数字悬停变勾选框，悬停行出拖动手柄；展开按钮在主字段格子右侧",
    "冻结线：最后一个冻结列右边一条细主色线，表头悬停出现手柄，拖到哪条列边界就冻结到哪",
    "分组行：折叠箭头 · 字段 · 选项标签 · 条数，组内统计对齐到对应列；每组末尾「+ 新增一行」",
    "底部统计栏吸底：第一格记录数，设了统计的列显示「求和 ¥5,223,000」，没设的悬停出「统计 ▾」",
  ],
  states: [
    "格子选中 = 2px 主色内框；多选一片 = 主色 8% 底，右下角填充柄",
    "保存中：新值立刻显示、格子右上角小点；失败按格回滚并说原因，左下角可「撤销」",
    "校验失败：异常色框 + 一行红字，编辑框不关，不弹窗",
    "只读格悬停出锁；空格子留白（不画「—」）",
    "勾选：表头半选「−」，只有一个反馈 —— 底部批量浮条（和 DataTable 同一个）",
    "手机：隐藏行号列，主字段冻结，其他列横滑；五个视图面板变底部弹层",
  ],
  dos: [
    "字段定义放模块级或 useMemo，保持引用稳定；值的形状按类型给（金额是「分」）。",
    "onCellsChange 收到的是一整批改动；rows 带上新值后再 resolve，拒绝的格子返回 { rejected }。",
    "视图用 useGridView 按人保存（键里带项目、用户、表名）；改了共享视图用 ViewOverrideBar 提示。",
    "少用的表级操作进 toolbarMore；actions 只放一个主按钮。",
    "截止日期用 GridField.deadline（逾期标红 +「逾期 N 天」），评论用 cellBadge 角标，不在格子里自己画带样式的 span。",
    "服务端模式下「我」「我的下属」从登录会话解析，不信前端传来的身份。",
  ],
  donts: [
    "工具栏不要占三行：表设置、权限、操作记录、公开链接不各占一个按钮。",
    "生效中的按钮不要只换浅底不说数量；也不要把数量写进按钮文字让宽度跳动。",
    "横向滚动后冻结列和后面的列之间不要留白缝；行号列不要宽到手机上只剩一列能看。",
    "勾了行不要在工具栏和表格上方各出一条「已选 N 条」，把表格往下推。",
    "选项标签不要用胶囊 + 描边；空格子不要满屏「—」。",
    "单选编辑下拉不要离格子 30px、左边对不齐：弹层贴格子下边 4px、最小宽 = 格子宽。",
  ],
  a11y: [
    "整张表只占一个 Tab 停靠点；方向键移动活动格，Enter / F2 编辑，Esc 取消。",
    "格子里有链接、标签、按钮时 Enter 进入格子，Tab 在格内循环，Esc 回到格子。",
    "Shift + F10 / 菜单键打开表头或格子的菜单；Ctrl + E 展开记录。",
    "主字段（primary）给读屏称呼这一行；cellBadge 的 label 会被读出。",
    "caption 是表格的可访问名称（默认「多维表格」，请写具体）。",
  ],
  demos: [
    {
      id: "data/grid-customers",
      title: "客户表（在线调试）",
      description: "双击 / 回车 / 直接打字编辑；拖选后 Ctrl + C / V；右下角小方块填充；勾选行号看底部浮条。",
      height: 540,
      controls: [
        { name: "rowHeight", label: "行高 rowHeight", type: "select", options: ["short", "medium", "tall"], default: "short" },
        { name: "frozenColumns", label: "冻结列 frozenColumns", type: "number", default: 1, min: 0, max: 3 },
        { name: "toolbarSearch", label: "搜索 toolbarSearch", type: "select", options: ["icon", "box"], default: "icon" },
        { name: "summary", label: "统计栏 summary", type: "boolean", default: true },
      ],
    },
    { id: "data/grid-grouping", title: "分组、统计与填色", description: "视图里带分组、组内统计、筛选和整行填色；每组底部「+ 新增一行」自动带上分组值。", height: 540 },
    { id: "data/grid-editing", title: "卡片里的小表：校验与回滚", description: "数量超过 500 在格子里报错；单价改成 0 被「服务端」拒绝并回滚。", height: 300 },
    { id: "data/grid-deadline", title: "截止日期与格子里新建选项", description: "「截止」逾期标红并写「逾期 N 天」，今天 / 2 天内橙色，已完成的不提醒；在「状态」里输入没有的名字，回车新建并选上。", height: 300 },
  ],
  props: [
    {
      component: "BitableGrid",
      rows: [
        { name: "rows / dataSource", type: "readonly T[] / GridDataSource<T>", description: "前端数据（几千条以内）或服务端数据源（分块加载，给 loadGroups 才能分组）" },
        { name: "getRowId / fields", type: "(row) => string / readonly GridField<T>[]", description: "必填。fields 保持引用稳定" },
        { name: "caption", type: "string", default: '"多维表格"', description: "表格的可访问名称" },
        { name: "view / onViewChange / defaultView", type: "GridView / (view) => void / GridViewInput", description: "受控视图（配 useGridView 保存）或不受控的初始视图：筛选、分组、排序、统计、填色、冻结、行高" },
        { name: "onCellsChange", type: "(changes, { source }) => void | { rejected } | Promise", description: "一批改动（编辑、粘贴、清空、撤销、填充）一次保存；throw 整批回滚，rejected 按格回滚" },
        { name: "rowHeight / frozenColumns", type: '"short" | "medium" | "tall" | "extraTall" / number', default: '"short" / 1', description: "视图没设时的默认行高（32 / 56 / 88 / 120）和冻结列数" },
        { name: "selection / onSelectionChange / bulkActions", type: "readonly string[] / (ids) => void / (ids) => BulkAction[]", description: "勾选与底部批量浮条" },
        { name: "toolbar / actions / toolbarQuick / toolbarMore / toolbarSearch", type: 'boolean | ReactNode / ReactNode / ReactNode / MenuSection[] / "box" | "icon"', description: "工具栏开关或替换；一个主按钮；快捷筛选；「⋯」菜单；搜索框样式" },
        { name: "height / maxHeight", type: '"fill" | "auto" | number | string / number', default: '"fill"', description: "fill 铺到窗口底；auto 随行数到 maxHeight（默认 480）" },
        { name: "summary", type: "boolean", default: "true", description: "底部统计栏" },
        { name: "expandRecord / rowActions", type: "boolean | GridExpandRecord<T> / (row) => RowAction[]", description: "记录详情（默认开）；最右固定的 ⋯ 菜单" },
        { name: "onAddRow / onRowMove / cellBadge", type: "(group) => void / (move) => void / (row, field) => { label, tone? } | null", description: "每组「+ 新增一行」；拖动排序；格子角标" },
        { name: "peopleOptions / conditionContext", type: "Record<string, GridPerson[]> / ConditionContext", description: "人员字段的候选人；筛选里「我」「我的下属」和相对日期怎么算" },
      ],
    },
    {
      component: "GridField<T>",
      rows: [
        { name: "key / title / type", type: "string / string / GridFieldType", description: "25 种类型：text、longText、number、money、date、datetime、singleSelect、multiSelect、user、checkbox、url、email、rating、progress、phone、formula、attachment、link、lookup…" },
        { name: "primary", type: "boolean", description: "主字段：冻结在最左、不能隐藏、读屏用它称呼这一行" },
        { name: "editable", type: "boolean | (row) => boolean", description: "能否在格子里编辑；需要表格给 onCellsChange" },
        { name: "options", type: "readonly { value, label, tone? }[]", description: "单选 / 多选的选项；顺序 = 排序和分组顺序，tone 是 10 色之一" },
        { name: "required / validate / parse", type: "boolean / (value, row) => string | null / (text, row) => …", description: "必填、校验（返回原因）、自定义输入解析" },
        { name: "summary", type: '"count" | "filled" | "empty" | "unique" | "sum" | "avg" | "min" | "max"', description: "默认统计（用户可改）" },
        { name: "currency / precision / timeZone", type: "string / number / string", description: "金额符号（值是分）、小数位、日期时区" },
        { name: "tone / locked / description", type: "(row) => tone | null / boolean | string / string", description: "按行给文字着色；表头的锁；表头 ⓘ 字段说明" },
        { name: "deadline", type: "boolean | { closed?: (row) => boolean }", description: "日期 / 日期时间是截止日期：按时区的日历天比今天（deadlineState），逾期红字 +「逾期 N 天」，今天 / 2 天内橙字；closed 为真不提醒；tone 返回颜色时以 tone 为准" },
        { name: "onCreateOption", type: "(label) => Promise<GridSelectOption | null | undefined>", description: "单选 / 多选：搜不到同名选项时编辑器最后一行「+ 新建选项「…」」，回车或点它等宿主建好再选上；null = 取消，reject = 编辑器不关并提示原因" },
        { name: "value / text / render", type: "(row) => unknown / (row) => string / (row) => ReactNode", description: "值不在 row[key] 时读取；custom 字段的搜索文字；覆盖格子显示（尽量不用）" },
      ],
    },
  ],
};

const selectList: ComponentDoc = {
  slug: "select-list",
  title: "选择列表",
  subtitle: "SelectList",
  group: "data",
  importFrom: "@adminui/react",
  summary: "列表 + 详情页的左栏：搜索、分组标题、单选高亮、未读徽标、两行摘要，搜不到和加载中都有样子。",
  keywords: "select-list list master-detail 左栏 角色列表 会话列表 未读 搜索 高亮",
  when: [
    "左边选一项、右边看 / 改它：角色与权限、数据表目录、客服会话、模板列表。",
    "会话、通知这类要显示未读和最后一条消息的列表（两行版）。",
  ],
  whenNot: ["要排序、筛选、批量操作的记录 —— 用 DataTable。", "层级目录 —— 用 NavTree 或 CheckableTree。"],
  anatomy: [
    "顶部：搜索框 28px + 新建图标按钮（toolbar）",
    "分组标题：12px 备注色 + 数量",
    "行 36px（两行内容 52px，手机 44px）：16px 备注色图标或字母头像 · 名称 · 右侧附注 / 未读徽标（垂直居中）",
  ],
  states: [
    "选中：主色浅底 + 加粗",
    "未读：名字加粗 + 主色数量徽标（超过 99 写 99+）；没数字时一个小圆点",
    "搜索：命中的字高亮；搜不到写「没有找到「…」」+ 「新建这个…」",
    "加载：骨架行；空：emptyLabel",
  ],
  dos: [
    "图标用 16px 备注色，不套彩色圆底；名字才是重点。",
    "同一组的项目要相邻，group 写分组名。",
    "给 onCreate，让搜不到的时候能直接新建。",
    "手机上列表整屏显示，点进去是详情（带返回）。",
  ],
  donts: [
    "不要每个图标套一个浅色圆底：一列下来全是圆点，名字反而不突出。",
    "右侧附注不要用偏上的小字，要和行垂直居中。",
    "搜不到时不要显示「还没有…」：那读起来像什么都没有。",
    "手机上不要把整个列表收成一个「切换」按钮。",
  ],
  a11y: [
    "每行是按钮，选中项 aria-current；label 是列表的可访问名称。",
    "未读徽标带 aria-label「N 条未读」，小圆点读「有新消息」。",
    "行高不低于 36px，手机 44px，触屏好点。",
  ],
  demos: [
    { id: "data/select-list-roles", title: "角色列表 + 详情", description: "搜「运营」看搜不到的样子和「新建这个角色」。", height: 380 },
    { id: "data/select-list-inbox", title: "会话列表：两行、未读、加载", height: 420 },
  ],
};

const sortableTree: ComponentDoc = {
  slug: "sortable-tree",
  title: "拖动排序与树",
  subtitle: "SortableList · CheckableTree",
  group: "data",
  importFrom: "@adminui/react",
  summary: "SortableList 是能拖手柄或用键盘排序的竖向列表（字段顺序、分组层级、选项）；CheckableTree（@adminui/react/access）是三态勾选树，也能单选做部门树。",
  keywords: "sortable drag reorder tree checkable 拖动 排序 拖拽 树 勾选树 部门树 权限树 三态",
  when: [
    "用户自己调顺序：字段顺序、分组层级、排序规则、选项列表、表单题目。",
    "从层级里勾选一批：菜单权限、数据范围、通知对象（CheckableTree）。",
    "选一个部门做导航（CheckableTree mode=\"single\"）。",
  ],
  whenNot: ["整页的目录导航 —— 用 NavTree。", "几个平级选项多选 —— 用 MultiChoice / ChipGroup。"],
  anatomy: [
    "排序行 32px（dense 28px）、圆角 8：拖手柄（悬停才出，触屏常显）· 内容 · 右侧开关",
    "可选的两级分组：组头带折叠箭头和「N 个字段」，项目可以在组之间移动；locked 项固定不动",
    "树行 32px（手机 40）：每级缩进 20px + 1px 引导线 · 三态勾选 · 名称 · 编码（等宽小号备注色）",
    "树工具：搜索 + 展开 / 收起 + 全选 / 全不选 + 「只看已选」",
  ],
  states: [
    "拿起：浮起阴影 + 手柄变主色；落点：主色细线 + 圆点；原位置留浅色占位",
    "父节点部分选中：「−」；搜索时自动展开命中的分支并高亮",
    "停用节点（disabled）：备注色，联动时保持原样",
  ],
  dos: [
    "SortableList 的数据由你掌握：onChange 拿到新数组后存起来。",
    "给 itemLabel 和 label：拖动和键盘移动时读屏会播报「已移到第 3 位」。",
    "锁住的项目给 lockedHint 说明为什么不能动（「主字段固定在第一列」）。",
    "树节点的编码、人数放 hint，不要拼进名字。",
  ],
  donts: [
    "不要让输入框占满整行、手柄常驻；拖动中不要只是变透明，要看得出拿起了哪一行。",
    "树不要只有「复选框 + 名字 + 编码」同色同字号，也不要没有层级引导线。",
    "「展开全部 / 收起全部 / 全选 / 全不选」不要做成一排文字链接。",
  ],
  a11y: [
    "SortableList：Tab 到手柄，空格拿起、↑↓ 移动、空格放下、Esc 取消；Alt + ↑↓ 直接移一步；每步 aria-live 播报。",
    "CheckableTree 是 WAI-ARIA tree：一个 Tab 停靠点，↑↓ Home End 移动，→ 展开，← 收起，空格勾选。",
    "行带 aria-level / aria-setsize / aria-posinset；勾选状态用 aria-checked（含 mixed）。",
  ],
  demos: [
    { id: "data/sortable-list-fields", title: "字段顺序（带编组和锁定项）", height: 340 },
    { id: "data/checkable-tree-permissions", title: "权限勾选树", description: "从 @adminui/react/access 引入；搜「导出」看自动展开。", height: 440 },
    { id: "data/checkable-tree-departments", title: "部门树（单选）", height: 300 },
  ],
};

const descriptionList: ComponentDoc = {
  slug: "description-list",
  title: "键值列表",
  subtitle: "DescriptionList · readableDetail",
  group: "data",
  importFrom: "@adminui/react",
  summary: "一个对象的只读属性：每项一个标签 + 一个值，一到三列，手机一列。空值写「—」，补充说明跟在值后面。",
  keywords: "description-list descriptions key-value 键值 属性 详情 字段 只读",
  when: [
    "详情页、弹窗、侧栏里展示一个对象的属性（客户资料、订单信息、账号信息）。",
    "表格展开行、审计日志里的「改了什么」。",
  ],
  whenNot: ["要编辑的字段 —— 用表单或记录详情。", "多个对象互相比较 —— 用表格。"],
  anatomy: [
    "每项：标签 12.5px 备注色在上，值 14px 正文色在下（等宽数字）",
    "列数 columns：1 / 2 / 3，手机自动一列；full 的项占整行（长文本、地址、JSON）",
    "hint：值下面一行灰字补充说明",
  ],
  states: [
    "空值（null / undefined）：「—」；合法的 0 或空字符串照原样显示",
    "长文本：full 占整行，不截断",
  ],
  dos: [
    "值按类型渲染：人员用 PersonChip、状态用标签、编号用 CopyableValue、金额日期用等宽数字。",
    "嵌在展开行里时单独一块，技术字段（请求号、ID 数组）收进「原始数据（JSON）」：readableDetail 帮你分开。",
    "标签写人话（「转交给」），不要直接显示 lineId / ids 这种 key。",
    "放在窄卡片、KPI 下方时用一列；长文本、地址给 full 占整行。",
  ],
  donts: [
    "不要给值单独加大字号或加粗成标题：键值列表是读的，不是看的。",
    "空值不要有时写「—」有时整格不显示；补充说明不要单独占一行。",
    "一个对象的属性不要做成两列表格。",
  ],
  a11y: [
    "渲染成 <dl> / <dt> / <dd>，读屏按「标签：值」读出。",
    "「—」只是显示，必要时在 hint 里写清原因（「还没有签约」）。",
    "可复制的值用 CopyableValue，复制结果有读屏播报。",
  ],
  demos: [
    { id: "data/description-list-customer", title: "客户资料：一到三列", height: 360 },
    { id: "data/description-list-expanded", title: "嵌在展开行里，技术字段折叠", height: 320 },
  ],
};

const statStrip: ComponentDoc = {
  slug: "stat-strip",
  title: "指标带与变化值",
  subtitle: "StatStrip · DeltaBadge · MetricCard · MetricGrid · KpiCard · KpiGrid",
  group: "data",
  importFrom: "@adminui/react",
  summary: "列表页、工作台顶上的一排数字：一张卡细线分格，每格说明 + 数值 + 单位 + 一行脚注。变化值的好坏看指标是「越大越好」还是「越小越好」。",
  keywords: "stat-strip stats kpi metric delta 指标 指标带 统计 变化值 环比 同比 涨跌 metric-card",
  when: [
    "列表、工作台、个人页顶上 4–6 个数字（客户总数、本月新增、逾期未跟进）。",
    "数字旁边要说「比上周 +3」：DeltaBadge。",
    "3–4 个只有数值的卡片：MetricCard；要趋势线、目标、缺数据说明：KpiCard（看板里的用法见「KPI 卡」）。",
  ],
  whenNot: ["超过 6 个数字 —— 拆成几段。", "随时间变化的走势 —— 用图表。"],
  anatomy: [
    "StatStrip：一张卡 + 可选标题行（标题 · 灰字 count · 右侧时间范围等）；格子之间 1px 细竖线",
    "每格：图标 14px + 说明 12.5px · 数值 22px + 单位 12px · 一行脚注（对比、构成、原因）",
    "DeltaBadge：圆角 6、无边框、20px（sm 18px）；箭头 = 方向，颜色 = 好 / 坏",
  ],
  states: [
    "变好：主色；变差：异常色（由 better 决定，不看箭头方向）",
    "持平：「持平」灰底；从 0 增长：「新增」，不写 ∞%",
    "没有基准：「—」纯文字；缺数据：数值写「—」+ 原因，不写 0",
    "数值本身要注意：tone=\"attention\" / \"danger\"",
  ],
  dos: [
    "用 computeDelta(本期, 上期, { better, mode }) 算变化值；比率用 mode: \"points\"（百分点）。",
    "越小越好的指标（响应时长、流失、逾期）给 better: \"down\"。",
    "comparison 写清和谁比（「比上周」）：读屏会连同变化一起读。",
    "手机上两列；同一页的 KPI 卡和指标带用同一套字号，间距 12。",
  ],
  donts: [
    "不要一页只放两格各占半屏宽的数字，看起来像没做完。",
    "变化值不要用全圆胶囊 + 描边；「持平」前面不要多一个减号。",
    "不要只看箭头方向定颜色：响应时长下降是好事，不能和赢单率下降同一个红色。",
    "KPI 卡高度要齐，脚注不折行；缺数据不要写 0。",
  ],
  a11y: [
    "StatStrip 渲染成 <dl>，没有标题时给 label 作为可访问名称。",
    "DeltaBadge 的 aria-label 读出「比上周 下降 −7 分钟 向好」：颜色不是唯一信息。",
    "图标都是装饰（aria-hidden），说明文字必须写全。",
  ],
  demos: [
    { id: "data/stat-strip-list-page", title: "列表页顶上的指标带", description: "切换本周 / 本月，看变化值的颜色怎么跟着「越大越好 / 越小越好」变。", height: 220 },
    { id: "data/delta-badge-cases", title: "变化值的几种情况", height: 300 },
    { id: "data/metric-cards", title: "MetricCard 与 KpiCard", height: 420 },
  ],
};

const timeline: ComponentDoc = {
  slug: "timeline",
  title: "时间线",
  subtitle: "Timeline · TimelineDay · TimelineItem · ActivityFeed · LogTimeline",
  group: "data",
  importFrom: "@adminui/react",
  summary: "按时间发生的事，一套解剖三种用法：自己拼的跟进记录（Timeline 积木）、窄栏动态 ActivityFeed、审计密排 LogTimeline。",
  keywords: "timeline activity feed log audit history 时间线 动态 跟进记录 操作日志 审计 历史",
  when: [
    "某个对象的历史：客户跟进、工单处理、审批过程（Timeline 积木）。",
    "侧栏、卡片里的最近动态：备份、同步、谁做了什么（ActivityFeed）。",
    "操作日志、审计：一行一条，展开看改动前后（LogTimeline）。",
  ],
  whenNot: ["要搜要筛的上万条日志 —— 用 DataTable + 服务端分页。", "几项检查各一个状态 —— 用 StatusChecklist。"],
  anatomy: [
    "左侧 20px 轨道，1px 线穿过中心",
    "标记：人做的事 = 20px 头像（按人分色，浅底 + 首字）；系统的事 = 8px 圆点；结果 = 带 ✓ / ✕ / ! 的 20px 圆",
    "标题行「谁 + 做了什么 + 对象」，时间在右（正文数字字体，悬停看完整时间）",
    "正文 13.5px；附件 / 录音是描边小卡（TimelineAttachment）",
    "按天分组，日期标题吸顶「今天 10月7日 周三」；底部「显示更早的 N 条」",
    "LogTimeline：一行 44px「时间 · 头像 + 人 · 摘要 · 对象 · 展开」",
  ],
  states: [
    "加载：TimelineSkeleton / loading 骨架行",
    "空：居中在卡片里的空状态（图标 + 一句话 + 可选说明）",
    "展开：下方白底键值列表，技术 key 收进「原始数据（JSON）」",
    "手机：时间折到标题下面",
  ],
  dos: [
    "宿主自己的跟进列表用 Timeline / TimelineDay / TimelineItem 拼，不自己画圆点和竖线。",
    "dayHeading(\"2026-10-07\") 得到「今天」「昨天」或日期，传给 TimelineDay。",
    "ActivityFeed 的 meta 是普通文字（「1.2 GB」），不要做成状态胶囊。",
    "LogTimeline 只改一个字段时用 inlineDiff，直接在行里写「跟进中 → 已成交」。",
  ],
  donts: [
    "不要三个地方三种长相：动态、审计、跟进记录用同一套解剖。",
    "审计头像不要全是同一个实心色圆，分不出是谁；时间不要用等宽字体。",
    "展开后不要整行灰底铺满，也不要直接显示原始 key。",
    "空状态不要只有一个图标 + 一句话挂在页面顶上。",
  ],
  a11y: [
    "Timeline 是 <ol>，label 是列表名称；时间用 <time dateTime>。",
    "结果圆带读屏文字（成功 / 失败 / 注意），头像是装饰。",
    "onOpen 时标题行变成按钮，可以用键盘打开。",
    "「显示更早的 N 条」是按钮；加载中禁用并写「正在加载…」。",
  ],
  demos: [
    { id: "data/timeline-follow-up", title: "客户跟进记录（Timeline 积木）", height: 520 },
    { id: "data/activity-feed", title: "最近动态 ActivityFeed", height: 480 },
    { id: "data/log-timeline-audit", title: "操作日志 LogTimeline", height: 420 },
  ],
};

const compactTable: ComponentDoc = {
  slug: "compact-table",
  title: "紧凑表格与状态清单",
  subtitle: "CompactTable · StatusChecklist",
  group: "data",
  importFrom: "@adminui/react",
  summary: "CompactTable 是 20 行以内、一眼看完的小表（排行、图表旁明细、弹窗里的小表）；StatusChecklist 是几项有名字的检查，每项一个状态 + 原因。",
  keywords: "compact-table mini table ranking checklist health check status 小表 排行 紧凑表格 自检 状态清单",
  when: [
    "卡片、弹窗、标签页里的少量固定行：排行、统计明细、几条配置。",
    "自检、依赖、连接状态、步骤进度：StatusChecklist。",
  ],
  whenNot: ["要找、要筛、要操作的列表 —— 用 DataTable。", "要在格子里编辑 —— 用 BitableGrid（height=\"auto\"）。"],
  anatomy: [
    "CompactTable：表头一行、行高固定（默认 32px，rowHeight=\"medium\" 两行），数字右对齐；没有工具栏、行号、统计栏",
    "字段定义和 BitableGrid 共用 GridField；columns 之外的字段在点开的详情里",
    "maxRows +「显示更多」，viewAll「去完整列表」",
    "StatusChecklist：顶部汇总「1 项异常 · 3 项正常」；每项 状态图标 + 文字 · 名称 · 原因 · 右侧附注 · 一个操作",
  ],
  states: [
    "CompactTable：loading / error + onRetry / emptyLabel 都在表格位置原地显示",
    "StatusChecklist 状态：ok 正常 · warning 注意 · error 异常 · pending 进行中 · off 未启用 · unknown 未知",
    "全部正常时汇总写「全部正常（N 项）」",
  ],
  dos: [
    "CompactTable 用 sort 固定顺序（没有排序按钮）；行动作 1 个时直接是按钮，多了进 ⋯。",
    "弹窗、卡片里用 maxHeight 内部滚动，多了给「去完整列表」。",
    "每项检查最多一个操作（「重新连接」「去修复」），原因写人话。",
  ],
  donts: [
    "3 行的表不要配搜索、筛选、分组、行号、统计栏：控件比数据还多。",
    "弹窗里不要塞完整的表格。",
    "状态不要只靠颜色：永远是图标 + 文字。",
  ],
  a11y: [
    "CompactTable 的 caption 是表格名称；可展开的行用键盘也能打开。",
    "StatusChecklist 每项的状态以文字读出，不依赖图标颜色。",
    "操作按钮不可用时给 disabledReason。",
  ],
  demos: [
    { id: "data/compact-table-ranking", title: "卡片里的排行", height: 320 },
    { id: "data/status-checklist", title: "连接自检", height: 380 },
  ],
};

export const dataDocs: readonly ComponentDoc[] = [dataTable, grid, selectList, sortableTree, descriptionList, statStrip, timeline, compactTable];
