import type { ComponentDoc } from "./types";

const dialog: ComponentDoc = {
  slug: "dialog",
  title: "弹框",
  subtitle: "Dialog · FormDialog · DialogFooter",
  group: "feedback",
  depth: "deep",
  importFrom: "@adminui/react",
  summary: "居中弹框，五档宽度 + 全屏。头部、正文、底栏三段；正文自己滚动，滚起来才出分隔线。FormDialog 自带提交中锁定、失败提示和「放弃未保存的内容？」。",
  keywords: "dialog modal form-dialog dialog-footer 弹框 弹窗 对话框 模态框 表单弹框 全屏 底栏",
  when: [
    "需要用户专心完成一件小事又不离开当前页面：新建客户、重命名、导入预览。",
    "填表并提交用 FormDialog；只看结果、做选择、看只读详情用 Dialog。",
    "内容很大（报价单预览、两个版本对比）用 xl 或 full，不要硬塞进 lg。",
  ],
  whenNot: [
    "能撤销的单条操作（删一条、改阶段）—— 直接做并给「撤销」提示条（useUndoToast）。",
    "撤不回的危险操作要问一句 —— 用 ConfirmDialog。",
    "页面旁边的工具面板、评论、设置 —— 用 SideSheet。",
    "很长的表单、多步骤流程 —— 做成独立页面。",
  ],
  anatomy: [
    "头部：标题 16 / 600 + 一行说明（description）；右侧可放 headerActions，最右是 28px 的 × 图标按钮",
    "正文：超出高度时自己滚动；滚动起来头部下面才出现分隔线，不要自己画线",
    "底栏（白底）：从右往左依次是 主操作 · 次要操作 · 取消；危险操作（删除客户）放最左，红字幽灵按钮；左边可放一句提示",
    "宽度：sm 420 · md 560 · lg 800 · xl 1080 · full（四边留 24）",
  ],
  states: [
    "提交中：主按钮转圈，× 灰掉，点遮罩和 Esc 都不关，重复提交无效",
    "失败：弹框不关，顶部一条异常提示 + 字段标红，填的内容全部保留；多处错误时出汇总并可跳到字段",
    "有改动时关闭：在弹框上叠一个小确认「放弃未保存的内容？」，下面的表单仍看得见",
    "深色：弹框比页面亮一档，外加 1px 很淡的白边",
    "手机：sm / md 从底部升起（拖动条、圆角 16），lg 以上整屏；按钮 44 高",
  ],
  dos: [
    "按内容选宽度：一两个字段用 sm，常规表单 md，表格预览 lg / xl，整份文档 full。",
    "底栏用 DialogFooter 或 FormDialog 的 dangerAction / secondaryActions，按钮顺序交给组件。",
    "主按钮写动作（「导入 125 行」「保存」），不要只写「确定」。",
    "FormDialog 传 dirty，让用户误关时有机会回去；保存失败用 throw 交给组件显示。",
    "只读的长内容设 initialFocus=\"dialog\"，焦点不要跳到第一个链接上。",
  ],
  donts: [
    "不要给遮罩加模糊，背景糊成一片后用户看不出弹框是从哪儿来的。",
    "不要把底栏做成灰条、也不要在头部下面固定画一条线：短弹框会被切成三截。",
    "放弃确认不要替换原弹框的标题和内容，要叠在上面，让用户看得到刚才填了什么。",
    "手机上不要用居中的小卡片，也不要让底栏三四个按钮平分宽度。",
    "宽度不要只有几档大跳，大内容不要硬塞进 lg 弹框。",
  ],
  a11y: [
    "打开后焦点锁在弹框内，Tab 循环；关闭后焦点回到打开它的按钮。",
    "title 是弹框的可访问名称（aria-labelledby），description 是 aria-describedby。",
    "Esc 关闭（提交中除外）；有未保存内容时先出放弃确认。",
    "失败提示用 role=\"alert\" 读出；字段错误带 aria-invalid 并把焦点移到第一个错误。",
    "手机上按钮 44 高，满足触屏尺寸。",
  ],
  demos: [
    {
      id: "feedback/dialog-playground",
      title: "在线调试",
      description: "改右侧属性，再点按钮打开弹框。打开「长正文」看滚动和分隔线。",
      height: 160,
      controls: [
        { name: "size", label: "宽度 size", type: "select", options: ["sm", "md", "lg", "xl", "full"], default: "md" },
        { name: "title", label: "标题 title", type: "text", default: "导入预览" },
        { name: "description", label: "说明 description", type: "text", default: "确认没问题再导入；可以先下载核对。" },
        { name: "longBody", label: "长正文", type: "boolean", default: false },
        { name: "withDanger", label: "底栏危险操作 danger", type: "boolean", default: false },
        { name: "hint", label: "底栏提示 hint", type: "text", default: "共 128 行，3 行有问题" },
      ],
    },
    { id: "feedback/dialog-form", title: "表单弹框", description: "填点内容再关，看叠上来的放弃确认；客户名称填「失败」看保存失败。", height: 160 },
    { id: "feedback/dialog-sizes", title: "五档宽度", height: 160 },
    { id: "feedback/dialog-header", title: "只读详情：标题旁状态 + 上一条 / 下一条", height: 160 },
  ],
  props: [
    {
      component: "Dialog",
      rows: [
        { name: "open", type: "boolean", description: "是否打开（受控）" },
        { name: "title", type: "string", description: "标题，同时是弹框的可访问名称" },
        { name: "description", type: "ReactNode", description: "标题下一行说明" },
        { name: "onClose", type: "() => void", description: "× / Esc / 点遮罩时调用" },
        { name: "size", type: '"sm" | "md" | "lg" | "xl" | "full" | "record"', default: '"md"', description: "420 / 560 / 800 / 1080 / 全屏；record 给记录详情用" },
        { name: "footer", type: "ReactNode", description: "底栏，通常放 <DialogFooter>；不传就没有底栏" },
        { name: "headerActions", type: "ReactNode", description: "× 左边的按钮（上一条 / 下一条、在新页面打开）" },
        { name: "titleAdornment", type: "ReactNode", description: "紧跟标题的小元素，如状态徽标" },
        { name: "headerExtra", type: "ReactNode", description: "头部底部整宽的一块（标签页、要点）" },
        { name: "initialFocus", type: '"first" | "dialog"', default: '"first"', description: "打开后焦点落在第一个控件，或落在弹框本身（长的只读内容）" },
        { name: "placement", type: '"center" | "side" | "bottom"', default: '"center"', description: "一般不直接用：侧边用 SideSheet，底部用 BottomSheet" },
        { name: "modal", type: "boolean", default: "true", description: "false = 不带遮罩，背后页面仍可操作（评论类侧边）" },
      ],
    },
    {
      component: "FormDialog",
      rows: [
        { name: "open / title / onClose", type: "同 Dialog", description: "同 Dialog" },
        { name: "description", type: "string", description: "必填：一行说明这个表单做什么" },
        { name: "onSubmit", type: "() => void | Promise<void>", description: "提交；成功后自动关闭。抛 Error 显示在顶部，抛 FormFieldErrors 标到字段上" },
        { name: "dirty", type: "boolean", default: "false", description: "有未保存的改动：关闭前叠一个「放弃未保存的内容？」" },
        { name: "busy", type: "boolean", default: "false", description: "外部锁住表单（如还在加载数据）" },
        { name: "submitLabel", type: "string", default: '"保存"', description: "主按钮文字，写动作" },
        { name: "error", type: "string", description: "外部给的表单级错误，显示在顶部" },
        { name: "fieldErrors", type: "Record<string, string>", description: "按控件 id 给的字段错误（FormField htmlFor）" },
        { name: "destructive", type: "boolean", description: "主按钮变成危险实心" },
        { name: "size", type: "DialogSize", default: '"md"', description: "同 Dialog" },
        { name: "dangerAction", type: "ReactNode", description: "底栏最左的危险操作（删除客户），红字幽灵按钮" },
        { name: "secondaryActions", type: "ReactNode", description: "「取消」和主按钮之间的次要操作（保存并新建）" },
        { name: "hint", type: "ReactNode | false", default: "「带 * 的为必填项」", description: "底栏左边一句话；false = 不显示" },
      ],
    },
    {
      component: "DialogFooter",
      rows: [
        { name: "children", type: "ReactNode", description: "按 取消 · 次要操作 · 主操作 的顺序放按钮，主操作在最右" },
        { name: "danger", type: "ReactNode", description: "最左边的危险操作" },
        { name: "hint", type: "ReactNode", description: "左边一句提示（「共 128 行，3 行有问题」）" },
      ],
    },
  ],
};

const confirmDialog: ComponentDoc = {
  slug: "confirm-dialog",
  title: "确认弹框",
  subtitle: "ConfirmDialog · ChangeList · OneTimeSecretDialog",
  group: "feedback",
  importFrom: "@adminui/react",
  summary: "撤不回、影响别人或量很大的操作，先问一句。左边图标块定口气，标题直接问对象，按钮写动作；能撤销的操作不要问。",
  keywords: "confirm confirm-dialog change-list one-time-secret 确认 二次确认 删除确认 输入名称确认 改动清单 密钥 令牌 confirmOrUndo",
  when: [
    "撤不回的操作：删除整张表 / 业务线、作废已发出的单据。",
    "影响别人的操作：停用账号、批量转交客户。",
    "量很大的操作：一次删 ≥ 20 条（用 confirmOrUndo 判断）。",
    "改了重要配置，先用 ChangeList 列出「原值 → 新值」再保存；密钥只显示一次时用 OneTimeSecretDialog。",
  ],
  whenNot: [
    "能撤销的单条操作（删一条、移动、改阶段）—— 直接做，提示条里给「撤销」8 秒（useUndoToast）。",
    "需要填一整张表 —— 用 FormDialog。",
  ],
  anatomy: [
    "左边 36px 图标块：信息蓝（info）· 琥珀（warning）· 陶土红（danger）",
    "标题直接问对象：「删除客户『远航精密制造』？」；下面一句后果",
    "影响清单（impact）：灰底小清单，列出会被波及的东西",
    "输入名称确认（typeToConfirm）：名称是红字代码块，点一下就选中；输对了右边打勾，按钮才亮",
    "原因（reason）：必填时空着点按钮就地提示",
    "没有影响、原因、名称时不出正文区，只有头部和底栏",
  ],
  states: [
    "默认焦点在「取消」，回车不会误删；有原因 / 名称输入框时焦点在输入框",
    "处理中：按钮转圈并写「处理中…」，不能关闭、不能重复提交",
    "失败：弹框不关，顶部说原因和下一步",
    "填了原因再关闭：先问「放弃已填写的原因？」",
    "手机：从底部升起，两个按钮各占一半、44 高",
  ],
  dos: [
    "按钮写动作和数量：「转交 23 位」「删除业务线」，不写「确认」。",
    "危险操作给 destructive，按钮变成危险实心；页面上的入口按钮用危险描边。",
    "影响范围写进 impact 数组，一行一件事。",
    "onConfirm 失败就 throw Error，消息写原因 + 下一步。",
    "OneTimeSecretDialog 的密钥只在这里出现一次；服务端不能再返回同一个值。",
  ],
  donts: [
    "不要给能撤销的操作弹确认，多一次打断；直接做并给「撤销」。",
    "不要在没有正文时留一条空白的正文区和上下两条线。",
    "不要把输入名称做成普通输入框：要看得出该输什么，输对了要有反馈。",
    "不要让焦点一打开就落在右上角 ×。",
  ],
  a11y: [
    "标题是弹框的可访问名称，后果说明是 aria-describedby。",
    "默认焦点在「取消」，Enter 不会触发危险操作。",
    "输对名称时的勾带 aria-label「名称正确」；失败提示 role=\"alert\"。",
    "ChangeList 是带 caption 的表格，「→」对读屏隐藏并读作「改为」。",
  ],
  demos: [
    { id: "feedback/confirm-tones", title: "三种口气、输入名称、原因与失败", height: 160 },
    { id: "feedback/confirm-or-undo", title: "能撤销就别问", description: "单条直接删 + 撤销；批量 36 条才弹确认。", height: 200 },
    { id: "feedback/confirm-change-secret", title: "改动清单与一次性密钥", height: 160 },
  ],
};

const sheet: ComponentDoc = {
  slug: "sheet",
  title: "侧边 / 底部弹层",
  subtitle: "SideSheet · BottomSheet · ActionSheet",
  group: "feedback",
  importFrom: "@adminui/react",
  summary: "侧边弹层贴右边、上下铺满、不做圆角，用于设置和评论这类工具面板；底部弹层给手机用：快速表单、操作单、选择列表。",
  keywords: "side-sheet bottom-sheet action-sheet drawer 抽屉 侧边栏 侧滑 底部弹层 操作单 手机",
  when: [
    "设置类面板（表设置、通知规则）：带遮罩、有底栏，改了没保存要提示。",
    "评论、附件：modal={false}，不挡后面的表格，表格还能点能滚。",
    "手机上的快速表单（写跟进）：BottomSheet + onDone，头部「取消 · 标题 · 完成」。",
    "手机上的「⋯」菜单会自动变成 ActionSheet，一般不用手写。",
  ],
  whenNot: [
    "记录详情 —— 用居中弹框或整页，不用侧边弹层自己拼。",
    "分节很多的大设置（左边分节列表）—— 用 SettingsSheet。",
  ],
  anatomy: [
    "侧边：宽 md 480 · lg 640 · xl 800；贴右边、上下铺满、无圆角，左边 1px 线 + 阴影",
    "头部 56 高，标题 15；正文滚动；底栏左边写「改了 N 项，还没保存」",
    "cards：正文浅灰底，上面放白卡，不要白里套白",
    "底部：顶上拖动条、圆角 16、最高 88% 屏幕；表单头「取消 · 标题 · 完成」",
  ],
  states: [
    "有改动（changes > 0）时关闭：先问「放弃没保存的改动？」",
    "非模态（modal={false}）：没有遮罩，焦点可以回到页面",
    "手机：侧边弹层变整屏",
    "BottomSheet doneDisabled：没填内容时「完成」灰掉",
  ],
  dos: [
    "设置类侧边传 changes，用户一眼知道有没有保存。",
    "多个分区时用 cards，每个分区一张白卡。",
    "评论、附件用 modal={false}，让用户边看表格边写。",
    "手机上的 ⋯ 菜单直接用 Menu / MoreMenu，组件会换成操作单。",
  ],
  donts: [
    "不要在白底侧边里再套带边框的白卡片。",
    "不要给侧边弹层做圆角或留边，看起来像没放好的弹框。",
    "设置类侧边不要没有底栏，用户不知道改动保存了没有。",
    "手机上不要用桌面式小下拉，再点进去才看到侧边。",
    "评论、附件不要开模态，用户就看不到表格了。",
  ],
  a11y: [
    "和 Dialog 一样的焦点锁定、Esc 关闭、焦点归还。",
    "modal={false} 时不锁焦点，页面其余部分仍可用键盘操作。",
    "BottomSheet 表单头的「取消」「完成」是真按钮，44 高可点。",
    "ActionSheet 每行 48 高，危险项红字，灰掉的项写原因。",
  ],
  demos: [
    { id: "feedback/sheet-settings", title: "设置类：带底栏和未保存提示", description: "改一下天数或开关，再点 × 试试。", height: 160 },
    { id: "feedback/sheet-comments", title: "评论类：不挡后面的列表", height: 240 },
    { id: "feedback/sheet-bottom", title: "底部弹层：手机快速表单", height: 160 },
  ],
};

const menu: ComponentDoc = {
  slug: "menu",
  title: "菜单与行操作",
  subtitle: "Menu · MenuButton · ContextMenu · MoreMenu · RowActions · RowActionBar",
  group: "feedback",
  importFrom: "@adminui/react",
  summary: "所有菜单一种外观：圆角 12、行高 32、悬停中性浅底。菜单项是数据，快捷键、子菜单、勾选、灰掉写原因、危险项都内置；手机上自动变底部操作单。",
  keywords: "menu dropdown context-menu menu-button more-menu row-actions row-action-bar 下拉菜单 右键菜单 更多 行操作 操作单 action-sheet",
  when: [
    "按钮下拉（「新建 ▾」「批量操作」）：MenuButton。",
    "工具栏或卡片角的「⋯」：MoreMenu。",
    "右键菜单（表格单元格、列表项）：ContextMenu。",
    "表格行的操作：RowActionBar（露几个 + ⋯）或只有一个 ⋯ 的 RowActions。",
  ],
  whenNot: ["在几个选项里选一个值 —— 用 Choice / Select。", "带标题和内容的面板 —— 用 PopoverPanel。"],
  anatomy: [
    "菜单头（header，可选）：多选时写对象「已选 3 条：远航精密制造、青禾教育…」",
    "分组（sections，可带小标题）→ 菜单项：图标 · 文字 · 右对齐的快捷键",
    "灰掉的项：字灰 + 下一行小字写原因（disabledReason）",
    "危险项：红字，放最后一组；悬停陶土红浅底",
    "子菜单：右边 6px 展开，贴边自动翻到左边",
  ],
  states: [
    "鼠标打开：不高亮任何一项；键盘打开：高亮第一项",
    "悬停 / 键盘选中：同一种中性浅底，不再加焦点框",
    "勾选项（checked）：右侧打勾",
    "手机：「⋯」变底部操作单，48 高的行 + 单独的「取消」",
  ],
  dos: [
    "一个菜单里要么都有图标，要么都没有，文字才对得齐。",
    "快捷键写短：shortcut=\"Mod+Shift+Enter\" 会显示成符号（⌘ ⇧ ↵ / Ctrl ⇧ ↵）。",
    "多选时用 header 写对象，label 里写 {count}：「删除 {count} 条记录」。",
    "行操作最多露 3 个（图标 + 字），危险和灰掉的默认进「⋯」。",
  ],
  donts: [
    "不要自己写下拉菜单，也不要让不同菜单长得不一样。",
    "不要在子菜单父项上同时画浅底和焦点框（双层高亮）。",
    "「⋯」里只有一个危险项时，不要一打开就把它高亮成红底。",
    "不要把快捷键写成全称把菜单撑宽。",
    "不要用主色浅底做悬停，和选中状态混淆。",
  ],
  a11y: [
    "role=\"menu\" / menuitem / menuitemcheckbox；方向键移动、首字母跳转、Esc 关闭。",
    "关闭后焦点回到触发按钮；ContextMenu 可用 Shift+F10 或菜单键在聚焦元素下打开。",
    "灰掉的项仍可用键盘到达，读得到原因。",
    "MoreMenu、RowActions 的触发按钮有 label 作为可访问名称。",
  ],
  demos: [
    { id: "feedback/menu-buttons", title: "下拉、多选菜单头与「⋯」", height: 280 },
    { id: "feedback/menu-context", title: "右键菜单：子菜单、快捷键、勾选、危险项", height: 300 },
    { id: "feedback/menu-row-actions", title: "行操作：露几个 + ⋯", height: 240 },
  ],
};

const popover: ComponentDoc = {
  slug: "popover",
  title: "弹出面板",
  subtitle: "PopoverPanel",
  group: "feedback",
  importFrom: "@adminui/react",
  summary: "挂在工具栏按钮下的非模态面板：标题行 + 内容 + 底栏。筛选、字段、分组这类面板都用它，不要自己拼浮层。",
  keywords: "popover popover-panel 弹出面板 浮层 筛选面板 字段面板 下拉面板",
  when: [
    "工具栏上的筛选 / 字段 / 分组 / 排序面板。",
    "表头下面的小设置面板。",
    "需要标题、说明「?」、计数或底栏动作的浮层。",
  ],
  whenNot: ["只有一列动作 —— 用 Menu。", "要用户专心完成并提交 —— 用 Dialog。"],
  anatomy: [
    "宽度：sm 300 · md 380 · lg 560，或一个数字；永远不超过视口 − 16",
    "标题行 44：标题 + 「?」说明（help）+ 右边计数（headerExtra，「符合 23 / 168 位」）",
    "内容：可滚动；flush 去掉内边距给自带行的列表",
    "底栏（footer）：起步动作（添加条件）、清空、保存为新视图",
  ],
  states: [
    "位置：贴触发按钮左边缘往下 6px，右边放不下才翻成右对齐；不加小三角",
    "触发按钮：打开时浅灰底；已生效时主色浅底 + 数字（「筛选 2」）",
    "空：一句话 + 起步按钮；加载：骨架；出错：在面板里就地重试",
    "手机（sheet）：变底部弹层，带拖动条、标题和「关闭」",
  ],
  dos: [
    "触发按钮打开时设 aria-expanded，生效时让它看得出「这里有筛选」。",
    "说明文字放进 help 的「?」气泡，不要在面板顶上写一段介绍。",
    "需要手机可用的面板传 sheet。",
    "面板里的加载和错误用紧凑的 StatePanel 就地显示。",
  ],
  donts: [
    "不要让面板离开触发按钮、压住旁边的目录栏（对齐算错）。",
    "不要让打开状态和已生效状态看起来一样。",
    "不要把起步按钮和说明挤成一行；空状态写一句话 + 一个按钮。",
    "手机上不要浮着一个小卡片，下拉挤成一团。",
  ],
  a11y: [
    "面板有可访问名称（title 或 label）；Esc 关闭并把焦点还给触发按钮。",
    "点外面或滚动关闭时不抢焦点。",
    "在弹框里打开时挂进弹框本身，焦点锁定内仍能用键盘。",
  ],
  demos: [
    { id: "feedback/popover-filter", title: "筛选面板：打开 / 已生效两种按钮", description: "添加两个条件，关掉面板看按钮的变化。", height: 300 },
    { id: "feedback/popover-fields", title: "右对齐窄面板与就地出错", height: 360 },
  ],
};

const alert: ComponentDoc = {
  slug: "alert",
  title: "提示条与行内提示",
  subtitle: "InlineAlert · useNotify · useUndoToast · DisabledReason",
  group: "feedback",
  importFrom: "@adminui/react",
  summary: "你刚做的事 → 提示条（useNotify）；页面 / 卡片的状态 → 行内提示（InlineAlert）；表单错误 → 字段下方。能撤销的操作用 useUndoToast 先做再给「撤销」。",
  keywords: "toast notify snackbar inline-alert alert banner undo 提示条 消息提示 横幅 撤销 禁用原因 disabled-reason",
  when: [
    "操作结果：已保存、已生成报价单（带「打开」）、导入部分成功、复制失败。",
    "长任务：notify.progress 转圈，完成后 update 成「导出好了 · 下载」。",
    "页面或卡片的持续状态：开启了字段权限、还有客户没分配、系统维护横幅。",
    "功能不可用时说明原因：按钮用 disabledReason，一块区域用 DisabledReason。",
  ],
  whenNot: ["表单校验错误 —— 写在字段下方，不要用提示条。", "需要用户决定的事 —— 用 ConfirmDialog。"],
  anatomy: [
    "提示条：白卡圆角 12、宽 380，右下角；24px 圆形浅底图标 + 粗体结果 + 小字对象",
    "提示条右边最多一个操作（撤销 / 打开 / 再试一次）+ ×；带操作时底部一条细进度",
    "行内提示：圆角 8、图标 16、标题 600 + 次要色说明，右侧可放操作",
    "行内提示密度：标准（标题 + 说明 + 按钮）· 紧凑（一行）· 淡（无底色，表单里用）；banner 贴边无圆角",
  ],
  states: [
    "成功 / 信息 4 秒消失；带操作 8 秒，按钮上显示剩余秒数",
    "失败不自动消失，要用户点 ×",
    "鼠标放上去暂停计时；最多叠 3 条",
    "进行中：转圈，完成后原地变成结果",
    "手机：提示条整宽，在页面底栏上方",
  ],
  dos: [
    "简单结果仍可 notify(\"已保存\")；要写对象或操作用 notify.show({ title, description, action })。",
    "能撤销的单条操作用 useUndoToast({ title, run, undo })，不要先弹确认。",
    "延迟提交的删除把服务端调用放进 commit，倒计时结束才真删。",
    "行内提示的长段落用标题 + 次要色说明，不要整段染色。",
  ],
  donts: [
    "不要让失败的提示条 5 秒就消失，用户没看到就没了。",
    "不要用提示条做表单校验。",
    "提示条不要只有一行字、不能带操作、不支持进行中。",
    "行内提示的图标不要比文字大一圈，圆角和面板保持一致。",
    "手机上的提示条不要压住底部的分页栏。",
  ],
  a11y: [
    "失败提示条是 role=\"alert\"，其余是 role=\"status\"，读屏会读出。",
    "提示条上的操作按钮可用键盘到达；× 有「关闭」名称。",
    "InlineAlert 错误口气是 role=\"alert\"，其他是 role=\"status\"。",
    "不要只靠颜色区分口气：每种都有自己的图标。",
  ],
  demos: [
    { id: "feedback/alert-toasts", title: "六种操作结果提示", height: 200 },
    { id: "feedback/alert-inline", title: "行内提示：四种口气 × 三种密度 + 横幅", height: 360 },
    { id: "feedback/alert-disabled-reason", title: "说清楚为什么不能用", height: 160 },
  ],
};

const statePanel: ComponentDoc = {
  slug: "state-panel",
  title: "空 / 出错 / 加载",
  subtitle: "StatePanel",
  group: "feedback",
  importFrom: "@adminui/react",
  summary: "空、搜不到、出错、没权限、断网、不存在、加载中各有自己的样子：图标块 + 一句标题 + 一句原因 + 最多两个按钮。不要都写「暂无数据」。",
  keywords: "state-panel empty error loading forbidden 404 not-found offline 空状态 出错 加载 无权限 断网 骨架",
  when: [
    "列表、面板、整页还没有数据，或搜索 / 筛选为空。",
    "加载失败、超时、断网、服务不可用。",
    "没权限看、记录被删、网址打错（整页 404 保留外壳）。",
  ],
  whenNot: ["刚做完的操作结果 —— 用提示条。", "页面的持续提醒 —— 用 InlineAlert。"],
  anatomy: [
    "44px 图标块（圆角 12），按口气配色：中性（空 / 搜不到 / 不存在）· 主色（首次上手）· 琥珀（没权限 / 断网 / 超时）· 陶土红（出错）",
    "一句标题（title）：说发生了什么",
    "一句原因（message）：说为什么、怎么办",
    "最多两个按钮（action / secondaryAction），出错时 onRetry 给「重试」",
    "错误详情（details）：可展开，请求编号等可一键复制给管理员",
  ],
  states: [
    "kind：empty · no-results · error · forbidden · not-found · offline · unavailable · timeout · loading",
    "搜不到：传 query，标题变成「没找到『陈小姐』」，onClearSearch 给「清除搜索」",
    "加载：300ms 内不显示；首次用骨架；已有数据时刷新只在顶上走细线；超过 10 秒提示转后台",
    "尺寸：compact（弹层 / 卡片）· default（面板）· page（整页）",
  ],
  dos: [
    "搜不到要说搜了什么，并给清除搜索。",
    "筛选为空要说是哪几个条件。",
    "出错给重试和可复制的错误详情。",
    "没权限说找谁申请，给「申请查看」；记录不在了指向回收站。",
    "首次上手用 tone=\"brand\"，配一个主操作。",
  ],
  donts: [
    "不要搜不到时写「还没有数据」，用户会以为东西没了。",
    "不要出错只给一个红圈 + 一行字，没有重试、没有原因。",
    "不要让没权限和空用同一个图标、只换颜色。",
    "不要每种状态都用「暂无数据」「加载失败」这样笼统的话。",
    "首屏不要只放一个转圈「正在加载…」，用和内容同形状的骨架。",
  ],
  a11y: [
    "出错 / 不可用是 role=\"alert\"，其余是 role=\"status\"；重试按钮有明确文字。",
    "加载骨架带可读的文字（默认「正在加载…」），图标块对读屏隐藏。",
    "颜色之外每种状态都有独立图标。",
  ],
  demos: [
    { id: "feedback/state-kinds", title: "七种状态", description: "切换上面的分段看每一种。", height: 360 },
    { id: "feedback/state-sizes", title: "紧凑 / 整页尺寸", height: 420 },
  ],
};

const notificationCenter: ComponentDoc = {
  slug: "notification-center",
  title: "通知中心",
  subtitle: "NotificationCenter",
  group: "feedback",
  importFrom: "@adminui/react",
  summary: "顶栏铃铛 + 未读数，点开 420 宽面板：「通知」按今天 / 昨天 / 更早分组，「待我处理」能就地同意 / 拒绝。数据全由宿主的加载函数提供。",
  keywords: "notification-center inbox bell 通知 通知中心 铃铛 未读 消息 待办 待我处理 @我 mention",
  when: [
    "顶栏放在「搜索与命令」右边，让用户知道被 @、被分配、有审批等他。",
    "审批、权限申请多的系统打开「待我处理」标签（传 loadInbox）。",
  ],
  whenNot: ["刚做完的操作结果 —— 用提示条。", "后台任务进度 —— 用任务中心。"],
  anatomy: [
    "铃铛：未读时右上角红底数字，99+ 封顶",
    "面板：标签「通知」/「待我处理」；通知下有 全部 / 未读 / @我 筛选",
    "一条通知：头像（右下角小类型图标）+ 一句话（人名、记录名加粗）+ 引用原话 + 「来源 · 时间」",
    "未读主色小圆点；能就地办的给按钮（下载 / 同意 / 拒绝）",
  ],
  states: [
    "加载中、出错就地重试、空（「都看完了」）",
    "点一条：先标为已读，再交给 onOpen 跳转",
    "拒绝需要原因时先弹原因输入；动作失败就地显示，条目保留",
    "手机：整屏，右上 ×",
  ],
  dos: [
    "loadNotifications 支持 cursor 分页和 filter；尊重 signal。",
    "「待我处理」只列当前用户能处理的；执行动作时服务端再判权限、写审计。",
    "实时来了新通知时改 refreshKey 让面板重新加载。",
  ],
  donts: [
    "不要没有通知入口，让用户靠别处才知道被 @ 或被分配。",
    "不要把通知中心做成普通弹框。",
    "不要在组件里写业务代码；数据和动作都从宿主传进来。",
  ],
  a11y: [
    "铃铛按钮的名称包含未读数和待处理数（「通知，2 条未读，1 件待我处理」）。",
    "面板 Esc 关闭，焦点回到铃铛；标签可用方向键切换。",
    "未读不只靠圆点颜色，读屏会读出「未读」。",
  ],
  demos: [{ id: "feedback/notification-center", title: "铃铛 + 通知 + 待我处理", description: "点铃铛；在「待我处理」里试试同意和拒绝。", height: 560 }],
};

const commandPalette: ComponentDoc = {
  slug: "command-palette",
  title: "搜索与命令",
  subtitle: "CommandPalette · navCommands",
  group: "feedback",
  importFrom: "@adminui/react",
  summary: "Ctrl / ⌘ K 打开的全局搜索：顶部 640 宽面板，输入框就是头部。没输入显示最近和常用；输入后按 客户 / 页面 / 命令 分组，搜不到给退路。",
  keywords: "command-palette cmdk command-k search spotlight 搜索 命令面板 全局搜索 快捷键 navCommands",
  when: [
    "后台顶栏的全局搜索：跳页面、找客户 / 记录 / 文档、执行命令。",
    "菜单页面用 navCommands(navigation, onNavigate, extra) 生成，不要另写一份。",
    "各模块的数据搜索用 providers，每个模块一组。",
  ],
  whenNot: ["列表内的关键字过滤 —— 用 SearchBox。"],
  anatomy: [
    "触发器：搜索框样子（240 宽），手机上变成放大镜",
    "面板：顶部 14% 处、640 宽；输入框 52 高、15 号字，右边 Esc",
    "没输入：最近打开 + 常用命令（带单键快捷键）",
    "有输入：范围标签（全部 6 · 客户 4 …），按组列出，命中的字加粗；底部一行键盘提示",
    "搜不到：「没找到『花莲』」+ 在全部里搜 + emptyActions（新建客户「花莲」）",
  ],
  states: [
    "提供者并发查询，每个限时 800ms；超时的组显示「较慢，回车看全部」",
    "某组出错只在那一组显示「搜索出错 · 重试」，不影响别的组",
    "中文 ≥ 1 字、拉丁 ≥ 2 字才问提供者；每组 ≤ 5 条，总数 ≤ 30",
    "命令执行中显示忙，成功关闭，失败行内报错",
    "手机：整屏，右上「取消」",
  ],
  dos: [
    "提供者只返回当前用户能看的条目，只带显示用的最少信息。",
    "客户这类结果用 meta 写「阶段 · 城市 · 负责人」，方便区分重名。",
    "一个页面只让一个面板 enabled，避免 Ctrl K 冲突。",
    "给 emptyActions，让搜不到时也有下一步。",
  ],
  donts: [
    "不要把命令面板做成带标题和说明的普通表单弹框。",
    "不要只能搜菜单页面，客户、记录、文档都搜不到。",
    "搜不到时不要只有一行字；没输入时不要一片空白。",
    "手机上不要用居中小卡片和描边大方块按钮。",
  ],
  a11y: [
    "输入框是 combobox，结果是 listbox；↑↓ 移动、回车打开、Tab 切换范围。",
    "Esc 一下就关闭（框里有字也关），焦点回到触发器。",
    "组标题和结果数会读出；命中加粗不只靠颜色。",
  ],
  demos: [{ id: "feedback/command-palette", title: "页面 + 命令 + 客户搜索", description: "试试输入「青禾」「报表」或「花莲」。", height: 520 }],
};

const editConflict: ComponentDoc = {
  slug: "edit-conflict",
  title: "编辑冲突",
  subtitle: "ConflictChooser · ConflictModePicker · ConflictToggle · EditConflictNotice · SaveConflictDialog · StaleRecordNotice",
  group: "feedback",
  importFrom: "@adminui/react",
  summary: "两个人改了同一处：默认保留别人较新的值，自己填的永远不丢。就地改一格、详情多项保存、撤回 / 回到某个时间点，各有一种界面。",
  keywords: "conflict edit-conflict merge 冲突 编辑冲突 并发 撞车 覆盖 保留 退回 时光机 撤回",
  when: [
    "就地改一格时撞车：EditConflictNotice（表格会自动显示）。",
    "详情里同时改几项再保存撞车：SaveConflictDialog 逐项选。",
    "打开记录期间被别人改过：StaleRecordNotice 提醒刷新。",
    "撤回一批操作或回到某个时间点，有些格子后来又被改过：ConflictChooser。",
  ],
  anatomy: [
    "就地小卡：「陈一鸣 刚改过这一格 · 14:31」+ 两个值并排 +「重新填入我的 / 用我的覆盖」",
    "保存冲突弹框：每项两张选择卡（他的较新、默认选中 / 我的），下面写「已经替你合好 N 项」",
    "刷新提醒：顶部一条信息条 +「刷新」",
    "ConflictChooser：标题一句 + 两张规则卡（ConflictModePicker：保留别人后来的修改 / 一起退回）+ 冲突表（记录 · 字段 · 当时 · 现在 · 谁改的），每行一个「保留 / 退回」分段（ConflictToggle）",
  ],
  states: [
    "默认规则：保留别人的（keep）；退回的行淡琥珀底",
    "「当时」列用备注色，「现在」列用正文色",
    "保存失败：弹框不关，显示原因",
    "手机：选择卡竖排，整行可点",
  ],
  dos: [
    "默认保留较新的那份，要覆盖必须用户自己点「用我的」。",
    "表格 onCellsChange 对撞车的格子返回 rejected + conflict，组件自动显示提示；覆盖时 context.overwrite 为 true。",
    "ConflictChooser 的结果交给服务端，服务端逐格重新校验并写审计。",
  ],
  donts: [
    "不要撞车时只出一行错字然后刷新：看不到对方改了什么，自己填的也丢了。",
    "多项保存时不要没有「哪些自动合好了、哪些要你选」的界面。",
    "不要把规则说明塞进按钮小字，也不要自画单选小圆点。",
    "不要整块琥珀框 + 琥珀标题行，冲突提示一处醒目就够了。",
  ],
  a11y: [
    "规则卡是单选组，方向键切换；每行分段有「保留 / 退回」的可访问名称。",
    "冲突表有 caption（「有冲突的格子」）。",
    "刷新提醒是 role=\"status\"，不打断正在输入的人。",
  ],
  demos: [
    { id: "feedback/conflict-cell", title: "就地撞车与刷新提醒", height: 280 },
    { id: "feedback/conflict-save", title: "保存时逐项选", height: 160 },
    { id: "feedback/conflict-chooser", title: "撤回 / 回到时间点的冲突", height: 420 },
  ],
};

export const feedbackDocs: readonly ComponentDoc[] = [dialog, confirmDialog, sheet, menu, popover, alert, statePanel, notificationCenter, commandPalette, editConflict];
