import type { ComponentDoc } from "./types";

const select: ComponentDoc = {
  slug: "select",
  title: "下拉选择",
  subtitle: "Choice · MultiChoice · ChoiceTags",
  group: "inputs",
  depth: "deep",
  importFrom: "@adminui/react",
  summary: "表单、筛选条、弹框里所有下拉都是一种触发器 + 一种弹层：单选勾在右，多选勾选框在左；搜不到可以就地新建；手机上变成底部弹层。",
  keywords: "select dropdown combobox multiselect picker option tag 下拉 选择 单选 多选 选人 新建选项",
  when: [
    "从 7 个以上的选项里选一个：Choice；选项带颜色时值显示成选项标签。",
    "选多个（感兴趣的产品、协作人）：MultiChoice，已选是可删的标签。",
    "表单里 ≤ 6 个选项的单选：ChoiceTags，平铺成带颜色的标签按钮，一眼看全。",
    "选人：选项带 avatar，显示头像 + 姓名 + 部门 / 职位。",
  ],
  whenNot: [
    "2–6 个很短的选项、切换视图或范围 —— 用 SegmentedControl。",
    "带一行说明的少量选项 —— 用 RadioGroup 或 ChoiceTiles。",
  ],
  anatomy: [
    "触发器：和输入框同一个框，36px（size=\"sm\" 28px，筛选条、格子里）；右边箭头，打开时转向",
    "弹层：顶部搜索（选项多于 6 个或能新建时自动出）· 分组小标题 · 行高 32、圆角 6、整行悬停",
    "单选：勾在右边；多选：勾选框在左边 + 底部「已选 N 项 · 清空」",
    "新建行：「＋ 新建选项『…』」，回车直接建，颜色自动轮下一个",
  ],
  states: [
    "clearable：悬停时 × 替换箭头，Delete / Backspace 也能清空；「清空」不是一个假选项",
    "不能选的选项：灰掉，右边写原因（「要先填丢单原因」）",
    "多选放不下：收成「+N」；sm 一行，md 可换行",
    "readOnly：像值一样显示、带锁、无边框；disabled：灰底",
    "出错：FormField 的 error 写在下面一行（「最多选 3 项」）",
    "手机：同一个列表变成底部弹层，行高 44，标题 + 取消 / 完成",
  ],
  dos: [
    "选项颜色用 tone（10 色之一），和表格、详情里的选项标签保持一致。",
    "放进 FormField，可见的字段名自动成为下拉的名称；label 仍要写，手机底部弹层的标题用它。",
    "选项多时给 group 分组，给 keywords 补拼音或编码方便搜索。",
    "多选每点一下就生效，点外面关闭；不需要「完成」按钮。",
    "能让用户补选项的字段给 onCreate，返回新选项的 value 就会自动选中。",
  ],
  donts: [
    "不要在一个页面里出现几种下拉：有的左勾、有的右勾、有的没勾没搜索。",
    "不要把「（清空）」当成第一个选项，看起来像一个真实的值。",
    "不要让悬停高亮条只占一部分宽度；整行高亮。",
    "搜不到时不要只写「没有匹配的选项」，能新建就给新建。",
    "选人不要只显示灰框文字；要有头像和部门。",
    "多选的已选标签不要做成不能删，必须打开弹层才能取消。",
  ],
  a11y: [
    "触发器是 role=\"combobox\"（aria-expanded、aria-controls），列表是 listbox，选项用 aria-selected。",
    "键盘：Enter / Space / ↓ 打开；↑ ↓ 移动；Enter 选中；Esc 关闭并把焦点还给触发器；打字跳到匹配项。",
    "ChoiceTags 是 radiogroup：方向键移动并选中，跳过不能选的项。",
    "不能选的原因写成文字，读屏能读到，不只靠灰色。",
    "手机底部弹层的行高 44，点按区域足够大。",
  ],
  demos: [
    {
      id: "form-controls/select-playground",
      title: "在线调试",
      description: "改右侧属性，预览和代码同步变化。",
      height: 200,
      controls: [
        { name: "multiple", label: "多选 MultiChoice", type: "boolean", default: false },
        { name: "size", label: "尺寸 size", type: "select", options: ["md", "sm"], default: "md" },
        { name: "clearable", label: "可清空 clearable（单选）", type: "boolean", default: true },
        { name: "searchable", label: "搜索 searchable", type: "select", options: ["auto", "true", "false"], default: "auto" },
        { name: "disabled", label: "禁用 disabled", type: "boolean", default: false },
        { name: "readOnly", label: "只读 readOnly", type: "boolean", default: false },
        { name: "placeholder", label: "占位 placeholder", type: "text", default: "请选择阶段" },
      ],
    },
    { id: "form-controls/select-single", title: "分组、不能选的原因、新建选项、选人", height: 320 },
    { id: "form-controls/select-multi", title: "多选：可删标签、+N、上限提示", height: 320 },
    { id: "form-controls/choice-tags", title: "≤ 6 个选项：平铺的标签按钮", height: 220 },
  ],
  props: [
    {
      component: "Choice",
      rows: [
        { name: "label", type: "string", description: "必填：名称；也是手机底部弹层的标题" },
        { name: "value", type: "string", description: "选中的 value；\"\" = 没选" },
        { name: "onChange", type: "(value: string) => void", description: "选中或清空（清空时传 \"\"）" },
        { name: "options", type: "readonly SelectItem[]", description: "value · label · tone（选项颜色）· group · hint · avatar（选人）· disabledReason · keywords · icon" },
        { name: "clearable", type: "boolean", default: "false", description: "悬停出现 ×，Delete / Backspace 也能清空" },
        { name: "size", type: '"md" | "sm"', default: '"md"', description: "36px · 28px（筛选条、格子）" },
        { name: "searchable", type: 'boolean | "auto"', default: '"auto"', description: "auto = 选项多于 6 个或给了 onCreate 时出搜索" },
        { name: "onCreate", type: "(label: string) => string | void | Promise<string | void>", description: "搜不到时出「＋ 新建选项」；返回新 value 即选中" },
        { name: "placeholder", type: "string", default: '"请选择"', description: "空值时的灰字" },
        { name: "disabled / readOnly", type: "boolean", description: "禁用；只读（像值一样显示、带锁、无边框）" },
        { name: "emptyText", type: "string", default: '"没有匹配的选项"', description: "搜不到时的空状态文字" },
        { name: "id", type: "string", description: "和 FormField 的 htmlFor 对应" },
      ],
    },
    {
      component: "MultiChoice",
      rows: [
        { name: "label", type: "string", description: "必填：名称；也是手机底部弹层的标题" },
        { name: "value", type: "readonly string[]", description: "已选的 value，按选项顺序" },
        { name: "onChange", type: "(value: string[]) => void", description: "每次勾选 / 取消 / 删标签都立即调用" },
        { name: "options", type: "readonly SelectItem[]", description: "同 Choice" },
        { name: "max", type: "number", description: "最多选几个；超出的勾选会被拒绝，原因用 FormField error 写出来" },
        { name: "size", type: '"md" | "sm"', default: '"md"', description: "md 标签可换行；sm 只一行，放不下收成「+N」" },
        { name: "searchable", type: 'boolean | "auto"', default: '"auto"', description: "同 Choice" },
        { name: "onCreate", type: "(label: string) => string | void | Promise<string | void>", description: "新建并自动勾上" },
        { name: "disabled / readOnly", type: "boolean", description: "禁用；只读" },
      ],
    },
  ],
};

const datePicker: ComponentDoc = {
  slug: "date-picker",
  title: "日期选择器",
  subtitle: "DatePicker · DateTimePicker · TimeInput · DateRangePicker · CalendarButton · QuickDatePresets",
  group: "inputs",
  depth: "deep",
  importFrom: "@adminui/react",
  summary: "能直接打字也能点开月历的日期框，值和原生输入框同格式（YYYY-MM-DD / YYYY-MM-DDTHH:mm / HH:mm）；弹层顶上一排快捷，值后面跟「周几 · 离今天几天」。",
  keywords: "date picker datetime time range calendar preset 日期 时间 日期范围 日历 快捷日期 截止日期",
  when: [
    "选一天：DatePicker；一天 + 时间：DateTimePicker；只要时间：TimeInput。",
    "报表、筛选的起止日期：DateRangePicker，左边放常用区间。",
    "跟进、提醒、到期类字段：DatePicker deadline，框下加 QuickDatePresets（1 天 / 3 天 / 7 天）。",
    "「+ 添加」一个日子到列表（补班日、休息日）：CalendarButton。",
  ],
  whenNot: ["相对时间段（近 7 天、本月）只作为筛选条件、不需要具体日子 —— 用 SegmentedControl 或 Choice。"],
  anatomy: [
    "输入框：和输入框同一个框；值后面跟「周四 · 明天」；日历图标在右，悬停出清空 ×",
    "快捷行：今天 / 明天 / 下周一 / 一周后 + 清空",
    "月历：今天 = 主色字 + 小圆点 · 已选 = 主色实底 · 键盘焦点 = 主色描边，三者不混",
    "日期 + 时间：月历右边半小时一档的时间列，也可以直接打字",
    "范围：左边常用区间，两个月并排，悬停预览，底部写「共 N 天」",
  ],
  states: [
    "deadline：今天 / 明天用注意色，已过期用异常色",
    "禁用日（min / max / isDisabledDate）：显示但不能选，打字输入也会被拒绝",
    "空值：框里只有灰色占位字，不显示任何示例日期",
    "打字：2026-10-05、2026/10/5、10/5（今年）都认；完整的立即生效，读不懂的失焦后退回原值",
    "手机：同一个弹层变成底部弹层，日子格 40px，头部「清空 · 标题 · 确定」",
  ],
  dos: [
    "需要「今天」固定（截图、测试、按服务器时间）时传 now。",
    "节假日由你的系统提供：传 holidays 标「休」「班」，组件不带日历数据。",
    "可以不填的日期给 clearable；「留空 = 永久」写在 FormField 的 hint 里。",
    "范围选择用 dateRangePresets([...]) 生成快捷区间。",
    "日期时间给 minuteStep（如 15），打字的时间也会对齐到档位。",
  ],
  donts: [
    "不要在空字段里显示灰色的示例日期（如「2026-10-05」），看起来像已经有值。",
    "不要用同一种方框同时表示「今天」和「已选」。",
    "不要让日期时间字段只有月历、没有地方选时间。",
    "不要让弹层比输入框窄、不对齐、往上压住别的字段；手机上用底部弹层。",
    "不要只写 2026-10-05，看不出周几、离今天几天、有没有过期。",
  ],
  a11y: [
    "框是普通文本输入框，id / aria-* 都落在它上面，FormField 的标签自动关联。",
    "↓ 或 Alt+↓ 打开并进入月历；方向键换天，PageUp / PageDown 换月，Enter 选中，Esc 关闭并回到输入框。",
    "点框只打开月历不抢焦点，可以接着打字。",
    "今天、已选、禁用都有文字说明给读屏，不只靠颜色。",
  ],
  demos: [
    {
      id: "form-controls/date-picker-playground",
      title: "在线调试",
      description: "演示把「今天」固定在 2026-10-08（周四）。",
      height: 200,
      controls: [
        { name: "size", label: "尺寸 size", type: "select", options: ["md", "sm", "touch"], default: "md" },
        { name: "clearable", label: "可清空 clearable", type: "boolean", default: true },
        { name: "relative", label: "相对日期 relative", type: "boolean", default: true },
        { name: "deadline", label: "截止日期 deadline", type: "boolean", default: true },
        { name: "disabled", label: "禁用 disabled", type: "boolean", default: false },
        { name: "placeholder", label: "占位 placeholder", type: "text", default: "选择日期" },
      ],
    },
    { id: "form-controls/date-time", title: "日期 + 时间、纯时间、禁用日", height: 320 },
    { id: "form-controls/date-range", title: "日期范围与常用区间", height: 200 },
    { id: "form-controls/date-quick", title: "1 / 3 / 7 天快捷与「+ 添加」日历按钮", height: 260 },
  ],
  props: [
    {
      component: "DatePicker",
      rows: [
        { name: "value", type: "string", description: "YYYY-MM-DD 或 \"\"" },
        { name: "onChange", type: "(value: string) => void", description: "选中、打字完成、清空时调用" },
        { name: "min / max", type: "string", description: "最早 / 最晚可选日；范围外的日子灰掉，打字也会被拒绝" },
        { name: "isDisabledDate", type: "(day: string) => boolean", description: "额外不能选的日子（周末、约满）" },
        { name: "clearable", type: "boolean", description: "悬停出 ×，弹层里出「清空」" },
        { name: "relative", type: "boolean", default: "true", description: "值后面显示「周四 · 明天」" },
        { name: "deadline", type: "boolean", description: "截止日期：今天 / 明天注意色，过期异常色" },
        { name: "size", type: '"sm" | "md" | "touch"', default: '"md"', description: "28 · 36 · 44（公开页、手机）" },
        { name: "weekStart", type: "number", default: "1", description: "一周从哪天开始：0 周日 … 6 周六" },
        { name: "holidays", type: "HolidayMarks", description: "宿主提供的「休」「班」标记" },
        { name: "placeholder", type: "string", description: "空值时的灰字" },
        { name: "now", type: "() => Date", description: "替换「今天」（测试、服务器时间）" },
      ],
    },
    {
      component: "DateRangePicker",
      rows: [
        { name: "value", type: "{ from: string; to: string }", description: "两个 YYYY-MM-DD；空用 \"\"" },
        { name: "onChange", type: "(value: DateRangeValue) => void", description: "起止顺序反了会自动对调" },
        { name: "presets", type: "readonly DateRangePreset[]", description: "左边的常用区间，用 dateRangePresets([\"today\", \"last7\", …]) 生成" },
        { name: "months", type: "1 | 2", default: "2", description: "宽屏并排几个月（手机总是 1 个）" },
        { name: "min / max", type: "string", description: "可选范围" },
        { name: "isDisabledDate", type: "(day: string) => boolean", description: "不能选的日子" },
        { name: "fromLabel / toLabel", type: "string", default: '"开始日期" / "结束日期"', description: "两个框的名称" },
        { name: "clearable", type: "boolean", description: "可以一键清空" },
        { name: "size", type: '"sm" | "md" | "touch"', default: '"md"', description: "同 DatePicker" },
        { name: "now", type: "() => Date", description: "替换「今天」" },
      ],
    },
  ],
};

const radioSegmented: ComponentDoc = {
  slug: "radio-segmented",
  title: "单选与分段",
  subtitle: "RadioGroup · SegmentedControl · ChoiceTiles · ChipGroup",
  group: "inputs",
  importFrom: "@adminui/react",
  summary: "少量选项直接摊开：圆点单选带说明、分段控件切换视图和范围、选项卡片放带说明的大选项、筛选块做多选筛选。",
  keywords: "radio radio-group segmented toggle tiles chips filter 单选 圆点 分段 切换 选项卡片 筛选块",
  when: [
    "表单里 2–5 个选项、每个要一行说明：RadioGroup。",
    "2–6 个很短的选项，切换视图、条件关系、时间范围：SegmentedControl。",
    "2–4 个分量重、带说明或图标的大选项（系统、套餐）：ChoiceTiles。",
    "列表上方的多选快捷筛选，可以带数量：ChipGroup。",
  ],
  whenNot: ["选项多于 6 个 —— 用 Choice。", "页面分区 —— 用 Tabs。", "选项有颜色含义（等级、来源）—— 用 ChoiceTags。"],
  anatomy: [
    "圆点：16px，选中 = 主色实心；文字可点，说明写在第二行",
    "分段：浅底槽 + 白色凸起的选中块；可带图标；md / sm 两档",
    "选项卡片：图标 + 标题 + 说明 + 单选标记；2 / 3 / 4 列",
    "筛选块：28px、圆角 8；选中 = 主色边 + 浅底 + 勾，数量变主色",
  ],
  states: ["悬停：中性叠层", "键盘聚焦：和输入框同一个 3px 主色光圈", "禁用：灰字，方向键跳过", "选中：分段是白色凸起块，不用主色实底"],
  dos: [
    "主色只留给真正的按钮；分段的选中态用白色凸起块。",
    "RadioGroup 放进 FormField，字段名自动成为单选组的名称。",
    "ChipGroup 的数量用 count，拿不到时传 null 隐藏。",
    "一组选项保持同一种控件，不要一部分圆点、一部分标签。",
  ],
  donts: [
    "不要同一个产品里分段控件一处浅绿底、一处主色实底。",
    "不要把带颜色的选项（状态）做成空心圆点，颜色就丢了 —— 用 ChoiceTags。",
    "不要用全圆描边胶囊做筛选块，选中不明显。",
    "不要用分段控件做会立即保存的危险操作。",
  ],
  a11y: [
    "RadioGroup / ChoiceTiles：方向键移动并选中，和原生单选一样。",
    "SegmentedControl：按钮带 aria-pressed，方向键只移动焦点、Enter / Space 才选中，避免路过就触发保存。",
    "ChipGroup：每个块是开关按钮（aria-pressed），可以换行，手机上不横向溢出。",
    "每组都要有 label，读屏会先念出组名。",
  ],
  demos: [
    { id: "form-controls/radio-group", title: "圆点单选与选项卡片", height: 300 },
    { id: "form-controls/segmented-chips", title: "分段控件与筛选块", height: 180 },
  ],
};

const checkbox: ComponentDoc = {
  slug: "checkbox",
  title: "勾选与开关",
  subtitle: "Checkbox · Switch · AsyncSwitch",
  group: "inputs",
  importFrom: "@adminui/react",
  summary: "勾选框用于「选上 / 不选」并随表单一起提交；开关用于立即生效的设置；要等服务端保存的开关用 AsyncSwitch，失败会弹回。",
  keywords: "checkbox switch toggle async indeterminate 勾选框 复选框 开关 半选 全选",
  when: [
    "表单里的多项勾选、同意条款、表格行选择：Checkbox。",
    "一组的全选：Checkbox checked=\"indeterminate\" 表示部分选中。",
    "设置列表里立即生效的开 / 关：Switch，放在行的右边。",
    "开关的结果要保存到服务端：AsyncSwitch（保存中锁住，失败弹回并提示）。",
  ],
  whenNot: ["需要点「保存」才生效的选项 —— 用 Checkbox，不用 Switch。"],
  anatomy: [
    "勾选框：16px、圆角 4；选中 = 主色实底白勾，半选 = 一横",
    "开关：32×18，小号 size=\"sm\" 26×14",
    "文字：放在勾选框右边、开关左边，整段文字可点",
  ],
  states: [
    "禁用：灰底灰勾",
    "出错：aria-invalid 时异常色边框",
    "聚焦：和输入框、下拉同一个 3px 主色光圈",
    "AsyncSwitch 保存中：锁住（aria-busy），失败自动回到原来的状态并弹出错误提示",
  ],
  dos: [
    "文字用 <label> 包住或用 htmlFor 关联，点文字也能切换。",
    "开关的文字写「是什么」（每日摘要邮件），不要写「开启 / 关闭」。",
    "开关立即生效，不再配「保存」按钮；需要提交的用勾选框。",
    "全选框根据子项计算 true / false / \"indeterminate\"。",
  ],
  donts: [
    "不要混用两套勾选框（组件库的和原生 input + accent-color），大小、圆角、深色表现都不一样。",
    "不要让开关和勾选框的聚焦光圈与输入框不是一套。",
    "不要在保存失败后让开关停在新状态，用户会以为已经生效。",
    "不要用开关表示需要确认的危险操作。",
  ],
  a11y: [
    "Checkbox 是 role=\"checkbox\"（半选为 aria-checked=\"mixed\"），Space 切换。",
    "Switch 是 role=\"switch\"，Space / Enter 切换；必须有可见文字或 aria-label。",
    "AsyncSwitch 的 label 必填，保存中设置 aria-busy。",
    "整行可点时点按区域不小于 24px，手机上不小于 40px。",
  ],
  demos: [
    { id: "form-controls/checkbox-states", title: "勾选框：全选、半选、禁用、出错", height: 260 },
    { id: "form-controls/switch-settings", title: "设置列表里的开关与异步保存", height: 320 },
  ],
};

export const formControlsDocs: readonly ComponentDoc[] = [select, datePicker, radioSegmented, checkbox];
