import type { ComponentDoc } from "./types";

const ROOT = "@adminui/react";

const inputSearch: ComponentDoc = {
  slug: "input-search",
  title: "文本框与搜索",
  subtitle: "Input · Textarea · SearchBox · Highlight · QueryBar · SearchField",
  group: "inputs",
  depth: "deep",
  importFrom: ROOT,
  summary: "一种框：静止浅边、悬停加深、聚焦主色边 + 光圈；前后缀、清空、字数都长在框里。多行自动长高；列表搜索打字就筛。",
  keywords: "input textarea search searchbox querybar highlight 文本框 输入框 多行 搜索 清空 字数 前缀 后缀",
  when: [
    "单行文字：名称、地址、编号。有上限的字段（短信、名称）打开字数。",
    "多行文字：需求、备注、跟进记录、评论，统一用 Textarea（自动长高 3–10 行）。",
    "列表上方的搜索 + 筛选用 QueryBar；侧栏、卡片头里的小搜索用 SearchField。",
  ],
  whenNot: [
    "数字、金额、电话、百分比 —— 用「数字、金额、电话、百分比」里的专用输入件。",
    "密码 —— 用 PasswordInput（等宽、眼睛、大写锁定提醒）。",
    "从固定选项里选 —— 用下拉 Choice。",
  ],
  anatomy: [
    "框：和下拉、日期同一根边线、同一种聚焦光圈",
    "前缀 / 后缀（可选）：图标或单位，备注色写在框里",
    "segment（可选）：框里要选的一格（https://、区号、币种），后面一条竖线",
    "清空 ×（可选）：浅色圆圈，有值且悬停 / 聚焦时才出现",
    "字数（可选）：「12/30」写在框内右端；多行时写在框内底行",
    "多行底行（可选）：工具按钮、快捷键提示和字数",
  ],
  states: [
    "静止：浅边；悬停：边加深；聚焦：主色边 + 3px 光圈",
    "出错：红边 + 下面一行「图标 + 原因 + 怎么改」，替换原来的说明",
    "禁用：浅灰底 + 淡字，不能聚焦；只读：可选中复制，没有清空 ×",
    "字数到 90% 变提醒色，超过上限变红",
    "尺寸只有两档：sm 28（筛选行、格子）和默认 36；手机自动 40，公开页自动 44",
  ],
  dos: [
    "前后缀写进框里（`prefix` / `suffix`）；要选的一格用 `segment`，不要在框外再摆一个下拉。",
    "有上限的字段打开 `showCount`，让人在打字时就看到还剩多少，而不是提交时才报。",
    "出错文字写「原因 + 怎么改」：「邮箱少了 @：例如 lin.xiao@example.com」。",
    "列表搜索打字就筛（停 0.3 秒），写命中几条、高亮命中的字、按 / 聚焦、Esc 清空。",
    "很慢的列表（审计日志）用 `searchMode=\"enter\"`，框里会写「回车搜索」。",
    "跟进记录、评论用同一种 Textarea，工具按钮放进 `footer`。",
  ],
  donts: [
    "不要让静止的框线比下拉、日期重一档；一屏框线多时会很吵。",
    "不要用浏览器原生 textarea：右下角拖拽角、固定行数，和整套界面不搭。",
    "不要用粗黑 × 做清空；一个产品里只有一种浅色圆圈 ×。",
    "列表搜索不要再配「查询」「重置」两个按钮，也不要让同一产品里有的打字就筛、有的要点按钮。",
    "不要等提交才告诉用户超字数。",
    "不要在各个页面自己拼前后缀、清空、字数，样子会各不相同。",
  ],
  a11y: [
    "放进 FormField 时，label 的 htmlFor 指向输入框；说明和出错自动接到 aria-describedby，出错自动加 aria-invalid。",
    "清空 × 不进 Tab 顺序（键盘直接删字即可；搜索框里按 Esc 清空），读屏名称是「清空」。",
    "字数用 aria-live=\"polite\" 播报；只有图标的前缀要么是装饰，要么在 label 里说清楚。",
    "搜索快捷键 / 只在焦点不在输入框时生效；命中高亮用 <mark>，不只靠颜色。",
    "手机上框高 40、公开页 44，满足触控尺寸。",
  ],
  demos: [
    {
      id: "inputs/input-playground",
      title: "在线调试",
      description: "改右侧属性，预览和代码同步变化。",
      height: 180,
      controls: [
        { name: "size", label: "尺寸 size", type: "select", options: ["md", "sm"], default: "md" },
        { name: "clearable", label: "清空 clearable", type: "boolean", default: true },
        { name: "showCount", label: "字数 showCount", type: "boolean", default: false },
        { name: "prefix", label: "前缀 prefix", type: "text", default: "" },
        { name: "suffix", label: "后缀 suffix", type: "text", default: "" },
        { name: "disabled", label: "禁用 disabled", type: "boolean", default: false },
        { name: "error", label: "出错文字 error", type: "text", default: "" },
      ],
    },
    { id: "inputs/input-affixes", title: "前后缀、框里的一格与多行", description: "多行文本自动长高，字数和工具按钮在框内底行。", height: 520 },
    { id: "inputs/input-search", title: "搜索", description: "上面打字就筛；中间是慢列表，回车才搜；下面是侧栏里的小搜索。", height: 420 },
  ],
  props: [
    {
      component: "Input",
      rows: [
        { name: "size", type: '"sm" | "md"', default: '"md"', description: "sm 28（筛选行、格子）· md 36（手机 40、公开页 44）" },
        { name: "prefix", type: "ReactNode", description: "框内左侧：图标或单位，备注色" },
        { name: "suffix", type: "ReactNode", description: "框内右侧：单位（「元」「%」）、图标或小按钮" },
        { name: "segment", type: "ReactNode", description: "框里要选的一格（https://、区号、币种），后面一条竖线" },
        { name: "clearable", type: "boolean", default: "false", description: "有值且悬停 / 聚焦时出现浅色圆圈 ×" },
        { name: "onClear", type: "() => void", description: "点 × 时调用；不传则通过 onChange 清空" },
        { name: "showCount", type: "boolean", default: "false", description: "框内右端「12/30」，需要同时给 maxLength" },
        { name: "mono", type: "boolean", default: "false", description: "等宽字体（编号、令牌、密钥）" },
        { name: "boxClassName", type: "string", description: "带前后缀等外框时，加在外框上的 class" },
        { name: "…input 属性", type: "ComponentProps<\"input\">", description: "value / onChange / disabled / readOnly / maxLength / aria-* 都落在内部 <input> 上，ref 也是" },
      ],
    },
    {
      component: "Textarea",
      rows: [
        { name: "autoGrow", type: "boolean", default: "true", description: "随内容长高，到 maxRows 后滚动；没有拖拽角" },
        { name: "minRows", type: "number", default: "3", description: "最少行数" },
        { name: "maxRows", type: "number", default: "10", description: "最多行数" },
        { name: "showCount", type: "boolean", default: "false", description: "框内底行「120/500」，需要 maxLength" },
        { name: "footer", type: "ReactNode", description: "框内底行左侧：附件、@、快捷键提示等" },
      ],
    },
    {
      component: "QueryBar",
      rows: [
        { name: "value / onChange", type: "string / (value: string) => void", description: "搜索框文字（受控）" },
        { name: "onSearch", type: "() => void", description: "执行搜索：live 模式停 0.3 秒后调用，enter 模式按回车调用" },
        { name: "onReset", type: "() => void", description: "清空所有筛选；只在 canReset 时显示「清空筛选」" },
        { name: "searchMode", type: '"live" | "enter"', default: '"live"', description: "live 打字就筛 · enter 慢列表回车才搜" },
        { name: "hits", type: "number | null", description: "有搜索词时框里写命中几条" },
        { name: "shortcut", type: "string", description: '在页面任意处按这个键聚焦，常用 "/"' },
        { name: "variant", type: '"card" | "flush" | "bare"', default: '"card"', description: "自带卡片 · 平铺带下边线 · 无框（放进面板头）" },
        { name: "children", type: "ReactNode", description: "搜索框右侧的筛选控件" },
      ],
    },
  ],
};

const numberInput: ComponentDoc = {
  slug: "number-input",
  title: "数字、金额、电话、百分比",
  subtitle: "NumberInput · MoneyInput · PhoneInput · PercentInput · NumberStepper",
  group: "inputs",
  importFrom: ROOT,
  summary: "数字一律等宽、离开时解析；金额的币种和电话的区号是框里的一格；百分比框里写 %；小整数用 − 数 + 步进器。",
  keywords: "number money currency phone percent stepper 数字 金额 币种 千分位 电话 手机 区号 百分比 步进器 加减",
  when: [
    "数量、面积等普通数字用 NumberInput；金额用 MoneyInput（值是最小单位，分）。",
    "手机、座机用 PhoneInput：值存成 E.164（+8613800138000），方便查重。",
    "0–100 的比例（赢率、完成度）用 PercentInput；1–30 的小整数（次数、天数）用 NumberStepper。",
  ],
  whenNot: ["大概值（满意度、赢率的粗估）想拖着调 —— 用「评分与滑块」里的 Slider。", "编号、邮编这类不参与计算的数字 —— 用普通 Input。"],
  anatomy: [
    "框：和文本框同一套边框、焦点、出错写法",
    "等宽数字：表单里左对齐，表格里右对齐（align=\"right\"）",
    "↑ ↓ 小箭头：悬停 / 聚焦才出现",
    "segment：金额的币种、电话的区号，是框里能点开选的一格",
    "单位 / %：写在框内右侧",
    "金额一万以上，框下写「约 ¥860 万」这样的读法",
  ],
  states: [
    "打字时是纯数字，离开时加千分位、按 precision 取整、夹到 min / max",
    "clamp={false} 时超范围的值保留，交给 FormField 报错",
    "电话离开输入框才校验，号码按当地习惯分组（138 0013 8000）",
    "步进器到上下限时 − / + 自动变灰；禁用时整框变灰",
  ],
  dos: [
    "默认币种和区号在 AdminProvider 上设一次（defaults 的 currency / phoneCountry，例如 CNY、+86，换成你的地区即可）；单个字段要别的币种再给 currency。",
    "币种由字段定死时只给 currency，不给 onCurrencyChange，那一格就是只读。",
    "区号默认值传本公司所在地（defaultCountry），访客页加 rememberKey 记住上次选的。",
    "百分比字段在表格格子里用 PercentBar：「60%」+ 一条 56px 细条。",
    "格子里编辑时也带着币种和 %，不要变成一个空白框。",
    "↑ ↓ 一次一个 step，Shift 一次 10 个；赢率这类给 step={10}。",
  ],
  donts: [
    "不要在格子里编辑金额时给一个没有币种、没有千分位、左对齐的空白框。",
    "不要把百分比存成普通数字、格子里只写「10」，让人猜单位。",
    "不要把 +8613800138000 原样显示给人看；显示时按当地习惯分组。",
    "不要用普通文本框收手机号、只在下面写一行格式说明，打错要提交才知道。",
    "不要让小号和标准号的步进器长成两套样子，也不要用带竖线的分隔块做 − / +。",
  ],
  a11y: [
    "NumberInput 是 inputMode=\"decimal\" 的文本框，↑ ↓ / PageUp / PageDown 可调。",
    "NumberStepper 的 label 必填，是读屏名称；− / + 按钮有各自的名称并在上下限时禁用。",
    "区号、币种那一格是按钮，打开的列表可用键盘搜索和选择。",
    "电话的校验信息在离开时出现，用 onValidate 接到 FormField error，读屏会读到。",
  ],
  demos: [
    { id: "inputs/number-money-percent", title: "数字、金额与百分比", description: "试试在金额里打 8600，离开后看千分位和「约 X 万」；点 ¥ 换币种。", height: 420 },
    { id: "inputs/number-phone-stepper", title: "电话与步进器", description: "点区号换国家；第二个框是错误号码，离开时才判断。", height: 420 },
  ],
};

const password: ComponentDoc = {
  slug: "password",
  title: "密码与密钥",
  subtitle: "PasswordInput · PasswordStrength · PasswordConfirmHint · InitialPasswordField · CodeInput",
  group: "inputs",
  importFrom: ROOT,
  summary: "密码框等宽、带眼睛和大写锁定提醒；设密码时强度条和要求随打字打勾，「再输一次」当场比对；初始密码摆在明面上；分格密码可粘贴整段。",
  keywords: "password strength confirm initial code pin otp 密码 强度 确认密码 初始密码 验证码 分格 显示密码",
  when: [
    "登录、改密码、新建成员 —— 一切密码框都用 PasswordInput。",
    "设新密码时配 PasswordStrength（强度 + 要求清单）和 PasswordConfirmHint（两次是否一致）。",
    "管理员给新成员设初始密码用 InitialPasswordField：自动生成 / 我来设两种方式。",
    "短验证码、访问密码（4–6 位）用 CodeInput。",
  ],
  anatomy: [
    "密码框：等宽字 + 框内右侧眼睛按钮；大写锁定开着时框下一行提醒",
    "强度：4 段细条 + 「太弱 / 一般 / 够用 / 很强」+ 四条要求清单",
    "确认提示：一致写「两次一致」，不一致写「和上面不一样」",
    "初始密码：分段「自动生成 / 我来设」；自动时密码直接显示，旁边「换一个」「复制」",
    "分格密码：44 × 52 的格子，下面是出错文字和剩余次数小点",
  ],
  states: [
    "眼睛按钮切换明文 / 圆点；出错和文本框一样：红边 + 一行原因",
    "强度和要求随打字实时变化；「再输一次」还是前缀时什么都不说",
    "分格密码输错：只变红边并抖一下（减少动画时不抖），剩余次数小点变红",
    "次数用完：整组禁用",
  ],
  dos: [
    "设新密码用 autoComplete=\"new-password\"，登录用默认的 current-password。",
    "两次不一致时给「再输一次」加 aria-invalid，并让提交按钮说明为什么不能点。",
    "初始密码直接显示并提供复制；告诉管理员它只显示这一次。",
    "强度只是引导，真正的密码规则在服务端再校验一遍。",
  ],
  donts: [
    "不要用普通文本框收密码：没有显示开关、没有大写锁定提醒。",
    "不要只写「至少 8 位」：没有强度、两次不一致要点了按钮才知道。",
    "不要用「留空 = 自动生成」这种暗规则，生成的密码长什么样也看不到。",
    "分格密码不要用 72px 大格子，输错也不要整格铺红底。",
    "一次性密钥页不要同时放三个倒计时，也不要把「复制」做成主色实心大按钮。",
  ],
  a11y: [
    "眼睛按钮有「显示密码 / 隐藏密码」名称和 aria-pressed。",
    "大写锁定提醒和确认提示都通过 aria-describedby 接到输入框。",
    "CodeInput 的 label 是整组的读屏名称；每格可用退格回到上一格，粘贴整段自动填满。",
    "出错时焦点不跳走，读屏读到出错文字。",
  ],
  demos: [
    { id: "inputs/password-change", title: "改密码", description: "改「新密码」看强度变化；把两次改成一样，提交按钮就能点了。", height: 420 },
    { id: "inputs/password-initial-code", title: "初始密码与分格密码", height: 300 },
  ],
};

const ratingSlider: ComponentDoc = {
  slug: "rating-slider",
  title: "评分与滑块",
  subtitle: "Rating · Slider",
  group: "inputs",
  importFrom: ROOT,
  summary: "评分是实心星：亮的用注意色，没亮的浅灰实心，表单里旁边写「较高」。滑块只给大概值，旁边永远配一个数字框。",
  keywords: "rating star slider range 评分 星级 滑块 拖动 赢率 满意度",
  when: [
    "意向、满意度这类 1–5 级的主观评价用 Rating；表单用 size=\"md\"（18px），格子用默认 13px。",
    "赢率、满意度这类大概值想拖着调用 Slider；百分比可直接用 PercentInput slider。",
  ],
  whenNot: ["精确数字（金额、数量）—— 用 NumberInput。", "两三个离散选项 —— 用分段控件或单选。"],
  anatomy: [
    "评分：一排实心星 + 表单尺寸时右侧文字（「较高」，未评写「未评」）",
    "滑块：4px 轨道 + 16px 圆点（手机 22px），已过部分主色",
    "数值气泡：悬停 / 拖动时出现在圆点上方",
    "刻度（marks）与刻度文字行（scale）：可选",
    "配套数字框（withInput）：88px，可直接打字",
  ],
  states: [
    "评分悬停预览（颜色略浅）；再点当前那颗 = 清空",
    "只读评分不可聚焦，整体是一张图（「4 星（满分 5）」）",
    "滑块悬停 / 拖动出光圈和数值气泡；拖动吸附到 step",
    "禁用：评分和滑块都变灰，不响应",
  ],
  dos: [
    "给 Rating 传 labels（「很低 … 很高」），值不只靠颜色和星数表达。",
    "滑块一定配数字：用 withInput，或用 PercentInput slider。",
    "只在需要「大概」的地方用滑块，并给合适的 step（赢率一格 10%）。",
    "保存太频繁时把保存放在 onCommit（拖完 / 按完键才触发）。",
  ],
  donts: [
    "不要让两个尺寸的星星一个实心一个空心，放在一起像两个组件。",
    "不要只有星星没有文字，读屏和不看颜色的人只能数星星。",
    "不要用滑块收精确数字，也不要让滑块单独出现、看不到具体值。",
  ],
  a11y: [
    "可编辑的 Rating 是一个 slider（一个 Tab 停点）：← → / ↑ ↓ 调，Home 清空，End 最大，数字键直接设。",
    "Slider 是 role=\"slider\"，aria-valuetext 带单位（「60%」）；← → 一步，PageUp / PageDown 十步，Home / End 到两端。",
    "label 必填，作为读屏名称。",
    "手机上滑块圆点 22px，拖动区域足够大。",
  ],
  demos: [{ id: "inputs/rating-slider", title: "评分与滑块", description: "悬停星星看预览，再点当前那颗清空；拖动或用方向键调滑块。", height: 400 }],
};

const form: ComponentDoc = {
  slug: "form",
  title: "表单布局与校验",
  subtitle: "FormField · FormSection · FormErrorSummary · FormDialog · SaveBar · useChangeTracker",
  group: "inputs",
  importFrom: ROOT,
  summary: "一个字段 = 标签 → 控件 → 说明或出错；提交出错时顶部汇总、每个框标红、焦点到第一个错；设置页整页一个吸底保存条。",
  keywords: "form field section dialog validation error summary savebar change tracker 表单 字段 校验 出错 汇总 保存条 已改 设置页",
  when: [
    "任何带标签的输入都包一层 FormField：标签、必填、说明、出错、字数统一。",
    "新建 / 编辑一条记录用 FormDialog；校验失败在 onSubmit 里 throw new FormFieldErrors({...})。",
    "设置页：FormSection layout=\"side\" 分区，useChangeTracker 记改动，整页一个 SaveBar。",
    "不在弹框里的长表单，提交失败时在顶部放 FormErrorSummary。",
  ],
  anatomy: [
    "标签：13px 次要色；必填红 *，「（选填）」，可带「?」说明",
    "控件：输入框、下拉、日期……",
    "下面一行：说明或出错（出错替换说明），右侧字数",
    "分区：标题 + 一句说明；设置页左边标题、右边字段",
    "错误汇总：「有 2 项要改」+ 每项一个可点的链接",
    "保存条：「改了 2 处」+ 哪几处 + 放弃 / 保存",
  ],
  states: [
    "打字时不打断；离开一个框才判这一个",
    "点提交：顶部汇总 + 每个框红边 + 焦点到第一个错 + 底栏「N 项要改」",
    "改正一个字段，它的错误消失，汇总少一条",
    "改过未保存的字段标签后有「已改」；保存条只在有改动时出现",
  ],
  dos: [
    "出错写「原因 + 怎么改」，一句话，放在对应的框下面。",
    "弹框宽度 ≥ 560px 时两列，相关的字段放一行；手机自动一列。",
    "详情、窄设置页用左标签（labels=\"side\"，112px），手机自动变上下排。",
    "立即生效的开关（AsyncSwitch）不算进保存条的改动。",
    "保存失败时保存条留着并提示原因，改动不丢。",
  ],
  donts: [
    "不要把校验错误堆在表单最下面一行：框不变红、焦点不过去，手机上还在第二屏。",
    "不要让说明和出错叠成两行；出错替换说明。",
    "设置页不要每个分区一个保存按钮，改了哪里、存没存看不出来。",
    "不要只校验格式不校验必填：手机号格式错了标红、名字没填反而不提示。",
    "分区不要只有一个标题，写一句说明这一块管什么。",
  ],
  a11y: [
    "FormField 自动把说明 / 出错接到子控件的 aria-describedby，出错时加 aria-invalid；出错文字是 role=\"alert\"。",
    "下拉、单选组等非 input 控件自动用可见标签命名（aria-labelledby）。",
    "错误汇总的每一项是链接，点了滚到字段并把焦点放进去。",
    "保存条是一个有名称的 region，「改了 N 处」用 aria-live 播报。",
  ],
  demos: [
    { id: "inputs/form-dialog-errors", title: "弹框表单与提交出错", description: "打开后直接点「新建」。", height: 160 },
    { id: "inputs/form-error-summary", title: "页面表单：左标签与错误汇总", description: "点「提交」，再点汇总里的一项跳过去。", height: 340 },
    { id: "inputs/form-settings-savebar", title: "设置页：分区与吸底保存条", description: "改一个字段，看「已改」和底部保存条。", height: 420 },
  ],
};

const upload: ComponentDoc = {
  slug: "upload",
  title: "上传",
  subtitle: "UploadField · UploadDropZone · UploadQueueList · ImageUploadGrid · useUploadQueue",
  group: "inputs",
  importFrom: ROOT,
  summary: "一种拖放区、一种文件行。表单里单个文件用一行版；多个文件进队列，有进度、剩余时间、失败原因和重试；照片用 96px 方块。",
  keywords: "upload file dropzone drag drop queue image photo progress retry 上传 文件 拖放 队列 图片 照片 进度 重试",
  when: [
    "表单里只要一个文件（营业执照、封面）用 UploadField 一行版。",
    "一次传多个文件用 useUploadQueue + UploadDropZone + UploadQueueList（或直接用 UploadQueue 组合）。",
    "封面、现场照片这种图片墙用 ImageUploadGrid。",
  ],
  anatomy: [
    "拖放区：1.5px 虚线、圆角 12、中性图标块 + 「把文件拖到这里，或 点击选择」+ 人话写的格式和大小",
    "一行版：图标 + 说明 + 「选择文件」；传完变成缩略图 + 名字 + 大小 + 换一张 / 删除",
    "队列行：类型方块 + 名字 + 4px 细条 + 「46% · 还要 10 秒」+ 取消 / 重试",
    "队列头：「上传队列 · 3 个 · 1 个失败」+ 「全部重试」",
    "照片方块：96px，第一张标「封面」，最后一格「添加照片 · 还能加 N 张」",
  ],
  states: [
    "拖进来：主色实线 + 浅底，写「松手开始上传 3 个文件」",
    "上传中：细条 / 圆环 + 百分比 + 剩余时间；可取消",
    "失败：写原因 + 重试；可续传的适配器按 attempt 从断点接着传",
    "格式或大小不对：拖放区红边 + 原因；停止收集：disabledText",
  ],
  dos: [
    "格式和大小写人话：「图片 PNG / JPG，5 MB 以内」，不要写 image/png。",
    "真正的上传交给你自己的适配器（upload），尊重 signal 取消，失败时 reject 一个写明原因的 Error。",
    "可续传：用 key 找回会话、attempt > 1 时接着传。",
    "附件面板空的时候只放一个拖放区，选择文件 / 拍照 / 录音都放在里面（actions）。",
  ],
  donts: [
    "不要在空状态同时放一个拖放区和一个「还没有文件」虚线框，同一句话说两遍。",
    "单文件和多文件不要长成两种样子（不同图标、不同字重）。",
    "不要把 5 MB 显示成 4.8 MB，也不要把 MIME 类型直接给用户看。",
    "失败的文件不要只有图标变色、整行颜色不一致；要写原因，并提供「全部重试」。",
  ],
  a11y: [
    "拖放区本身可聚焦、可用回车 / 空格打开文件选择，聚焦时可直接粘贴截图。",
    "队列的状态文字用 aria-live 播报；取消 / 移除按钮名称带上文件名。",
    "照片方块的删除、重试按钮都有名称；ImageUploadGrid 的 label 是整组名称。",
    "手机上图片上传会提供拍照 / 相册。",
  ],
  demos: [
    { id: "inputs/upload-zone-field", title: "拖放区与单文件一行版", description: "点「上传营业执照」选一个本机文件试试。", height: 520 },
    { id: "inputs/upload-queue", title: "上传队列", description: "点「模拟上传」：一个慢、一个在 30% 断一次，点「全部重试」接着传。", height: 300 },
    { id: "inputs/upload-images", title: "图片上传", height: 220 },
  ],
};

const markdownEditor: ComponentDoc = {
  slug: "markdown-editor",
  title: "长文本编辑器",
  subtitle: "MarkdownEditor",
  group: "inputs",
  importFrom: `${ROOT}/markdown`,
  summary: "左边写 Markdown、右边实时预览，支持表格和任务列表等 GFM 语法，可以导入 .md 文件。单独一个入口，用到才加载。",
  keywords: "markdown editor preview gfm 长文本 编辑器 预览 文档 公告 说明",
  when: [
    "公告、说明文档、知识条目这类需要标题、列表、表格的长文本。",
    "要让用户直接导入已有的 .md 文件。",
  ],
  whenNot: ["一两句话的备注、跟进记录 —— 用 Textarea。", "需要所见即所得排版（字号、颜色、图片拖放）的富文本 —— 这个组件不做。"],
  anatomy: [
    "头部：标题「Markdown 编辑与预览」+ 「导入 MD」按钮",
    "左栏：Markdown 文本框（自动长高）",
    "右栏：实时预览（只渲染 Markdown，忽略其中的 HTML）",
    "出错行：导入的文件不是 Markdown 或超过 maxBytes 时出现",
  ],
  states: [
    "打字即预览，没有「预览」按钮",
    "导入成功：整段替换为文件内容；导入失败：头部下方一行红字说明",
  ],
  dos: [
    "从 `@adminui/react/markdown` 单独引入，不进主包，用到的页面才加载 Markdown 渲染器。",
    "用 maxBytes 限制导入文件的大小，并在页面上告诉用户上限。",
    "预览区正文保持中性灰，只用标题层级和列表表达结构。",
    "在编辑器下方写字数和保存状态（「已自动保存 10:42」）。",
  ],
  donts: [
    "不要信任 Markdown 里的 HTML：预览已跳过 HTML，不要再自己用 dangerouslySetInnerHTML 渲染一份。",
    "不要在没有装 Markdown 渲染依赖的环境里引用它，页面会渲染不出来。",
    "不要在 @ 同事、插入变量这些场景里另造一种弹层，和选人用同一种。",
  ],
  a11y: [
    "文本框的读屏名称是「Markdown 内容」，预览区是名为「实时预览」的 article。",
    "导入按钮是普通按钮，键盘可达；隐藏的文件框不进 Tab 顺序。",
    "导入出错用 role=\"alert\" 播报。",
  ],
  demos: [{ id: "inputs/markdown-editor", title: "编辑与实时预览", height: 520 }],
};

const fieldConfig: ComponentDoc = {
  slug: "field-config",
  title: "字段配置",
  subtitle: "FieldDialog · FieldTypePicker · OptionsEditor",
  group: "inputs",
  importFrom: ROOT,
  summary: "新建 / 修改表格字段的弹框：类型按用途分组、可搜索、选中后有说明卡；按类型换设置；选项一行 = 拖柄 + 色点 + 框 + 已用条数。",
  keywords: "field dialog type picker options editor 字段 字段类型 新建字段 选项 单选 多选 颜色 多维表格",
  when: [
    "多维表格、自定义字段里「新建字段 / 修改字段」用 FieldDialog。",
    "只需要选类型（模板、导入映射）用 FieldTypePicker；只需要编辑选项用 OptionsEditor。",
  ],
  anatomy: [
    "字段名称：必填，重名当场提示",
    "类型格子：按「基础 / 选择 / 人与联系 / 关联与计算 / 系统自动」分组，可搜索；还没做的收在最后",
    "说明卡：选中后显示这个类型存什么、在表格里长什么样",
    "类型设置（settings）：货币 → 币种、小数位；电话 → 默认区号……",
    "选项编辑：拖柄 + 色点按钮 + 输入框 + 已用条数 + 删除",
    "右栏（aside，可选）：谁能看 / 谁能改",
  ],
  states: [
    "选项重名标红；删除正在用的选项先问「24 条客户会变空」",
    "还不能用的类型虚线、不能选，悬停写原因",
    "已有数据的字段可锁定类型（typeLocked）并写原因",
    "提交失败：弹框不关，显示原因",
  ],
  dos: [
    "按类型换设置：给 settings 传当前类型需要的控件，不要把所有设置一次摆出来。",
    "编辑已有字段时传 optionUsage 和 recordNoun，删除前的提问才说得清楚。",
    "给类型格子补 keywords（拼音、英文、同义词），搜索更好找。",
    "选项颜色用组件自带的色板，不要自己传十六进制颜色。",
  ],
  donts: [
    "不要把几十个类型平铺，「还不能用」的混在中间。",
    "选了类型不要什么都不说：「关联 / 查找引用 / 汇总」的差别不该靠猜。",
    "选项一行不要放三样重复的东西（色块 + 输入框 + 又一个标签预览）。",
    "手机上不要让类型格子占满整屏，把其他设置挤到最底下。",
  ],
  a11y: [
    "类型格子是一组单选，方向键按屏幕位置移动，回车选择；搜索框过滤后焦点留在搜索框。",
    "色点按钮的名称写出当前颜色；拖柄可聚焦，用 ↑ ↓ 调整顺序。",
    "出错信息接在对应的框上（aria-invalid + aria-describedby）。",
  ],
  demos: [
    { id: "inputs/field-dialog", title: "新建字段弹框", description: "打开后切到「货币」看类型设置，把名称改成「阶段」看重名提示。", height: 160 },
    { id: "inputs/field-type-options", title: "类型选择与选项编辑", description: "删除「普通」会先问 61 条客户怎么办。", height: 460 },
  ],
};

const conditionEditor: ComponentDoc = {
  slug: "condition-editor",
  title: "条件编辑器",
  subtitle: "ConditionTreeEditor · ConditionSummary · describeConditionTree",
  group: "inputs",
  importFrom: ROOT,
  summary: "字段 / 条件 / 值三格一行，值按字段类型换；连接词「且 / 或」可切换，可以加一层条件组；顶上一句话读出当前条件。",
  keywords: "condition filter rule tree editor summary 条件 筛选 规则 且 或 条件组 一句话",
  when: [
    "表格筛选、自动化规则、权限规则、表单显示条件 —— 需要「满足这些条件」的地方。",
    "只读展示条件（规则列表、卡片）用 ConditionSummary；要一句纯文字（通知、日志）用 describeConditionTree。",
  ],
  anatomy: [
    "一句话摘要（summary）：「阶段 是 方案报价、商务谈判 且 负责人 是 我 且（…）」",
    "条件行：字段（28px 下拉）· 条件 · 值 · ×",
    "连接词：行间「且 / 或」，点击切换",
    "条件组：浅底，自己的「全部满足 / 任一满足」",
    "底部：「添加条件」「添加条件组」",
  ],
  states: [
    "没填完的条件灰着写「还没填值，这条先不生效」",
    "值不合法：这一行红色，下面写原因（errors）",
    "到达数量 / 嵌套上限时添加按钮禁用并说明",
    "没有条件时显示 empty 内容（常用字段的快捷按钮）",
  ],
  dos: [
    "值按字段类型换：选项字段点选标签，人员字段带「我」，金额带币种。",
    "用 isComplete 告诉编辑器哪些行还不生效，而不是悄悄忽略。",
    "工具栏上写条件条数（「筛选 3」），面板顶上放一句话摘要。",
    "条件树是纯数据（condition-core），同一棵树可以拿去求值、转 SQL、做缓存键。",
  ],
  donts: [
    "不要让值永远是一个文本框：选项字段不能点选、人员没有「我」、日期没有「过去 7 天」。",
    "不要用垃圾桶删除筛选条件，那不是删数据；用 ×。",
    "条件里的下拉不要和别处的小号下拉长得不一样。",
    "不要只在面板外写「筛选」两个字，看不出有几条、是什么。",
  ],
  a11y: [
    "每一行有名称（「条件 2」），字段、条件、值各自带「条件 2 · 字段」这样的名称。",
    "连接词按钮读出当前关系并提示点击切换；条件组是带名称的 group（「条件组（任一满足）」）。",
    "ConditionSummary 整体用一句 aria-label 读出，不逐个读标签。",
  ],
  demos: [
    { id: "inputs/condition-editor", title: "编辑条件", description: "改一个值，看顶上的一句话跟着变；第 4 行还没填值，先不生效。", height: 380 },
    { id: "inputs/condition-summary", title: "只读摘要", height: 260 },
  ],
};

const formBuilder: ComponentDoc = {
  slug: "form-builder",
  title: "表单搭建器与公开填写页",
  subtitle: "FormBuilder · PublicForm · FormSuccess",
  group: "inputs",
  importFrom: `${ROOT}/form-builder`,
  summary: "用表格的字段拼一张对外收集的表单：搭建器所见即所得；填写页不用登录、手机友好；提交成功页给摘要。填写页单独从 /forms-public 引入。",
  keywords: "form builder public form success 表单搭建 表单设计 公开表单 填写页 问卷 收集 提交成功",
  when: [
    "让业务人员自己搭一张收集表（预约、报名、反馈），每份提交变成表里的一条记录。",
    "对外的填写页和成功页：从 `@adminui/react/forms-public` 引入 PublicForm / FormSuccess，只加载这一部分。",
  ],
  anatomy: [
    "搭建器左栏：已添加 / 可以加 / 不能放进表单 三组字段",
    "搭建器中间：所见即所得的题目（真实控件）；选中的题浮出上移 / 下移 / 移除，下面必填 · 说明 · 显示条件",
    "搭建器右栏：提交次数、谁能填、通知谁、停止收集",
    "填写页：品牌头 + 吸顶进度「已填 2 / 6」+ 题目 + 人机验证位 + 纯色提交按钮",
    "成功页：打勾 + 一句话 + 摘要（手机号打码）+ 再填一份",
  ],
  states: [
    "显示条件：前面的答案满足时才出现这道题",
    "提交出错：顶部汇总 + 每题标红 + 滚到第一个错",
    "提交失败（网络）：保留已填内容并说明原因",
    "停止收集：链接打不开；预览模式：一切可点但不发送",
  ],
  dos: [
    "电话题的默认区号传本公司所在地（defaultCountry），搭建器和填写页传同一个值。",
    "上传题接你自己的存储适配器（upload），失败可重试。",
    "人机验证放在 captcha 插槽，通过后把 captchaDone 设为 true。",
    "主字段放进 pinned，避免被移出表单。",
  ],
  donts: [
    "画布顶上不要留一块空的封面位；封面按需添加。",
    "搭建器里的题目控件不要和填写页长得不一样。",
    "手机吸顶条不要把标题再写一遍，挡住「带 * 的是必填」。",
    "提交按钮不要用渐变色；多选不要丢掉选项颜色。",
  ],
  a11y: [
    "填写页控件 44px 高，满足触控尺寸；每道题的标题就是控件的标签。",
    "提交出错时焦点到第一道错题，错误汇总可点击跳转。",
    "吸顶进度用文字写出「已填 2 / 6」，不只靠细条。",
    "成功页用一级标题写结果，摘要逐行列出已提交的内容。",
  ],
  demos: [
    { id: "inputs/form-builder", title: "表单搭建器", description: "点中间的题目编辑；顶上切到「填写预览」看填写页。", height: 620, bleed: true },
    { id: "inputs/public-form", title: "公开填写页与提交成功", description: "不填直接提交看出错；填好后点模拟验证再提交，看成功页。", height: 620, bleed: true },
  ],
};

export const inputsDocs: readonly ComponentDoc[] = [
  inputSearch,
  numberInput,
  password,
  ratingSlider,
  form,
  upload,
  markdownEditor,
  fieldConfig,
  conditionEditor,
  formBuilder,
];
