import type { ComponentDoc } from "./types";

const adminShell: ComponentDoc = {
  slug: "admin-shell",
  title: "应用外壳与侧栏",
  subtitle: "AdminShell · NavItem · CompanySwitcher · AccountMenu · AppearanceButton",
  group: "navigation",
  depth: "deep",
  importFrom: "@adminui/react",
  summary: "后台的整页外框：侧栏 232（折叠 64）、顶栏 48、胶囊工作标签。左上是产品和「当前公司」，左下一行头像管「我自己」，手机上侧栏变抽屉。",
  keywords: "admin-shell shell sidebar layout nav-item company-switcher workspace-switcher account-menu appearance 外壳 侧栏 菜单 折叠 抽屉 切换公司 账号菜单 头像 退出登录 外观 门户 portal",
  when: [
    "员工用的管理后台、运营后台：一个侧栏菜单 + 多个同时打开的工作页面。",
    "客户自助中心（账单、席位、工单）：用 variant=\"portal\"，没有工作标签和面包屑，手机有底栏。",
    "一个账号能进多家公司 / 多个工作区：传 company，切换入口放在左上品牌下面。",
  ],
  whenNot: [
    "模块内部的「图标栏 + 目录树」工作区（多维表格、知识库）—— 用 RailShell。",
    "登录页、对外公开的表单 —— 用 AuthLayout / PublicPageLayout，不套外壳。",
  ],
  anatomy: [
    "左上：标志方块（logo）+ 产品名（brand）；下面一条「当前公司」按钮，点开切换（company）",
    "菜单：行高 34、图标 18、圆角 6；可分组（group），分组标题不可点；数量灰胶囊（badge），要处理的异常色实心（badgeTone: \"danger\"）；没开通灰掉 + 锁（locked）",
    "左下：头像 + 名字 + 岗位一行 → 账号菜单：我的资料 / API 令牌 / 管理后台 ↗ / 外观（浅 · 深 · 跟随系统）/ 退出登录",
    "顶栏 48：⇤ 收起侧栏 · 面包屑 · 弹性空白 · headerActions（搜索、通知、外观）",
    "工作标签条（见「顶栏与工作标签」）+ 内容区；打开过的页面都挂着，切回来状态还在",
  ],
  states: [
    "当前菜单：浅一档的块 + 加粗，不加竖条",
    "折叠 64px：只剩标志方块、公司图标、菜单图标、头像；分组标题变一条细线；悬停出名字气泡，数字挂在图标角上，公司 / 账号菜单向右弹出",
    "没开通（locked）：灰色 + 锁，不能点；locked 是字符串时悬停说明原因",
    "手机：顶栏 = ≡ + 当前页名 + 操作 + 页签数；抽屉 min(304px, 84vw)、44px 一行、右上 ×，点遮罩或 Esc 关",
    "深色：侧栏右边一条线和画布分开",
  ],
  dos: [
    "「切换公司」只放左上品牌下面（company）；账号区只管「我自己」。",
    "管理后台这类另一个应用的入口放进账号菜单，href + external，新标签页打开并带 ↗。",
    "菜单数量用 badge，真正要处理的（待办、逾期）才用 badgeTone: \"danger\"。",
    "没开通的功能留在菜单里用 locked 写原因，让人知道去哪开通。",
    "外观放顶栏 AppearanceButton（浅 / 深 / 跟随系统 + 色卡 + 字号），一个按钮管全部。",
    "关闭多个标签时实现 onCloseTabs(ids)，一次更新状态；有没保存改动的标签由宿主拦下确认。",
  ],
  donts: [
    "不要在侧栏底部堆一排散按钮（切换公司、令牌、后台、退出）—— 收进左上公司按钮和左下头像菜单。",
    "不要让折叠后的侧栏丢掉账号区和品牌位：折叠了也要能退出、能切公司。",
    "品牌位不要只写一行字；给一个标志方块，折叠后只剩它。",
    "不要在页面顶部自己再写一条「工作空间 /」之类的固定前缀，面包屑由外壳生成真实的上一级。",
    "不要另放明暗开关、单独的色卡按钮或字号按钮。",
    "深色下不要让侧栏和画布同色、分不出边界。",
  ],
  a11y: [
    "侧栏是 nav（aria-label「主导航」），当前项 aria-current=\"page\"；分组是 role=\"group\" 并带组名。",
    "折叠后菜单按钮用 aria-label 读出名字；locked 项用 aria-disabled，仍可聚焦，锁图标读出原因。",
    "手机抽屉：Esc 和遮罩都能关，× 按钮有「关闭菜单」名字；抽屉里一行 44px，满足触屏尺寸。",
    "账号菜单、公司菜单是弹层：Esc 关闭并把焦点还给触发按钮；外链菜单项读作「（新标签页打开）」。",
  ],
  demos: [
    {
      id: "navigation/admin-shell-playground",
      title: "在线调试",
      description: "点菜单打开页面，⇤ 收起侧栏，点左上公司 / 左下头像看菜单；切到手机宽度看抽屉。",
      height: 600,
      bleed: true,
      controls: [
        { name: "company", label: "当前公司 company", type: "boolean", default: true },
        { name: "account", label: "头像行 account", type: "boolean", default: true },
        { name: "badges", label: "数量与未开通 badge / locked", type: "boolean", default: true },
        { name: "crumbRoot", label: "面包屑第一级 crumbRoot", type: "text", default: "" },
      ],
    },
    {
      id: "navigation/admin-shell-portal",
      title: "客户自助中心（portal）",
      description: "没有工作标签和面包屑，只挂当前页；手机上底部一条导航，第 5 格是「更多」。",
      height: 560,
      bleed: true,
    },
  ],
  props: [
    {
      component: "AdminShell",
      rows: [
        { name: "brand", type: "ReactNode", description: "产品名，放在左上标志方块后面" },
        { name: "logo", type: "ReactNode", description: "标志方块内容；折叠后只剩它。不传时取 brand 字符串的第一个字" },
        { name: "navigation", type: "readonly NavItem[]", description: "菜单：id / title / icon，可选 group、badge、badgeTone、locked、keywords" },
        { name: "tabs", type: "readonly WorkspaceItem[]", description: "打开着的页面：id / title / icon / content，可选 pinned、dirty、closable、crumbs" },
        { name: "activeId", type: "string", description: "当前页面 id（受控）" },
        { name: "onNavigate", type: "(id: string) => void", description: "点菜单 / 标签 / 命令时调用，宿主负责把页面加进 tabs" },
        { name: "onCloseTab", type: "(id: string) => void", description: "关一个标签；有没保存的改动时由宿主先确认" },
        { name: "onCloseTabs", type: "(ids: readonly string[]) => void", description: "「关闭其他 / 关闭右侧」一次关多个；不传则逐个调用 onCloseTab" },
        { name: "headerActions", type: "ReactNode", description: "顶栏右侧：CommandPalette、通知、AppearanceButton" },
        { name: "company", type: "CompanySwitcherProps", description: "品牌下的「当前公司」：value + options + onSwitch，或 onOpen 打开宿主自己的选择页" },
        { name: "account", type: "ShellAccount", description: "左下头像行：name、role（第二行）、detail（菜单头部）" },
        { name: "accountMenu", type: "readonly AccountMenuItem[]", description: "账号菜单行：label、icon、onSelect 或 href + external（↗ 新标签页）" },
        { name: "onSignOut", type: "() => void", description: "账号菜单最后一行「退出登录」" },
        { name: "crumbRoot", type: "ShellCrumb | string", description: "每页面包屑的第一级（如「管理后台」）" },
        { name: "variant", type: '"workbench" | "portal"', default: '"workbench"', description: "portal = 客户自助中心：没有工作标签和面包屑，只挂当前页" },
        { name: "mobileNav", type: "readonly string[]", description: "portal 专用：手机底栏最多 4 个菜单 id，第 5 格是「更多」" },
      ],
    },
    {
      component: "NavItem",
      rows: [
        { name: "id / title / icon", type: "string / string / LucideIcon", description: "必填；icon 传组件本身（Users），不是元素" },
        { name: "group", type: "string", description: "分组标题；同组的项要相邻" },
        { name: "badge", type: "number | string", description: "右侧数量（千分位）；折叠时挂在图标角上" },
        { name: "badgeTone", type: '"neutral" | "danger"', default: '"neutral"', description: "danger = 要处理的事，异常色实心" },
        { name: "locked", type: "boolean | string", description: "没开通：灰色 + 锁、不能点；字符串是原因" },
        { name: "keywords", type: "string", description: "给命令面板搜的同义词、旧名字，不显示" },
        { name: "shortTitle", type: "string", description: "portal 手机底栏用的短名（≤ 4 个字）" },
      ],
    },
  ],
};

const workTabs: ComponentDoc = {
  slug: "work-tabs",
  title: "顶栏与工作标签",
  subtitle: "AdminShell · WorkspaceItem · Breadcrumbs · CommandPalette · AppearanceButton",
  group: "navigation",
  importFrom: "@adminui/react",
  summary: "顶栏 48：真实面包屑 + 搜索框 + 通知 + 外观。下面一排胶囊工作标签，表示「已打开的页面」，和页内的下划线标签分开。",
  keywords: "work-tabs workspace-tabs topbar header breadcrumbs command-palette search appearance 顶栏 工作标签 页签 多标签 面包屑 搜索 命令面板 关闭其他 关闭右侧 外观",
  when: [
    "员工后台同时开着多个页面来回切（客户、合同、某个客户详情）。",
    "记录页、文档页要说明「在哪一层」：外壳顶栏自动出面包屑；页面里面的层级用 Breadcrumbs。",
  ],
  anatomy: [
    "顶栏：⇤ · 面包屑（crumbRoot → 标签的 crumbs 或菜单分组 → 当前页）· 空白 · 搜索框（Ctrl/⌘ K）· 通知 · 外观",
    "工作标签：胶囊 30px；工作台固定最左只有图标（pinned）",
    "放不下：两头渐隐 + 滚轮横滚；右端「N ⌄」列出全部（可搜），带「关闭其他 / 关闭右侧」",
    "手机：没有工作标签条和面包屑，顶栏右边一个页签数按钮，点开「已打开的页面」",
  ],
  states: [
    "当前标签：白底 + 细边 + 加粗，图标主色",
    "× 只在当前和悬停时出现；中键关闭",
    "没保存（dirty）：琥珀圆点，悬停变 ×",
    "右键标签：关闭 / 关闭其他 / 关闭右侧",
  ],
  dos: [
    "给记录页标签传 crumbs，让面包屑写出真实的上一级（「客户」可点）。",
    "顶栏放一个 CommandPalette：菜单用 navCommands 直接变成可搜的命令。",
    "有没保存改动的标签在 onCloseTab / onCloseTabs 里拦下来确认，不要直接丢。",
    "工作台标签设 pinned，永远在最左、不能关。",
  ],
  donts: [
    "不要把工作标签画成和页内标签一样的「彩色字 + 下划线」，一眼分不出已打开的页面和页面分区。",
    "不要给每个标签常驻 ×；不要让左右滚动箭头压住标签文字。",
    "不要在面包屑开头固定写「工作空间 /」这类不能点、没有意义的前缀。",
    "不要把搜索做成比旁边图标按钮更高、更重的带框按钮。",
    "手机上不要自己再挤一条工作标签。",
  ],
  a11y: [
    "工作标签每个是 role=\"tab\"（aria-selected），内容区 role=\"tabpanel\" 并 aria-labelledby 对应标签；没保存的圆点读作「未保存」。",
    "面包屑是 nav（aria-label「面包屑」），当前页 aria-current=\"page\"，不可点。",
    "Ctrl/⌘ K 打开搜索面板，Esc 关闭并回到原焦点；输入框里打字不会触发全局快捷键。",
    "「N ⌄」列表里可以搜索和关闭标签（「关闭客户」），键盘用户不依赖右键和中键。",
  ],
  demos: [
    {
      id: "navigation/work-tabs-shell",
      title: "顶栏 + 10 个工作标签",
      description: "当前是一个客户详情：面包屑「北辰云 › 业务 › 客户 › 远航精密制造」，「客户」可点。「合同」没保存，关不掉。",
      height: 560,
      bleed: true,
    },
    { id: "navigation/breadcrumbs", title: "页面里的面包屑", description: "第二条有 5 级，中间收成「…」。", height: 180 },
  ],
};

const railShell: ComponentDoc = {
  slug: "rail-shell",
  title: "模块工作区",
  subtitle: "RailShell · NavTree · WorkspaceTitleBar · ScopePill",
  group: "navigation",
  importFrom: "@adminui/react",
  summary: "一个模块自己的工作区：左边 60px 图标栏换模块，目录树选表，标题栏放名字、范围胶囊、协作者和分享。整页不滚，只有内容区滚。",
  keywords: "rail-shell nav-tree tree sidebar title-bar scope-pill workspace icon-rail module 图标栏 目录树 标题栏 业务线 范围 收藏 正在看 工作区 多维表格",
  when: [
    "多维表格、知识库、看板这类「一个空间里有很多张表 / 文档」的模块。",
    "需要在标题栏切换范围（业务线、部门、项目）并看到谁也在看。",
  ],
  whenNot: ["普通管理页面（列表、设置、详情）—— 放在 AdminShell 里。"],
  anatomy: [
    "图标栏 60：48×48 格子、20 图标 + 11px 字；底部 通知 / 设置 / 头像；数字是异常色小胶囊挂在右上角",
    "目录树 232（浅灰底）：头部 图标块 + 名字 + 小字 + ⋯；搜索；文件夹 ⌄ + 名字 + 灰色数量；底部「+ 新建」菜单",
    "标题栏 48：名字 · ? · ☆ · 范围胶囊（图标 + 名字 · 类型 ⌄）· 正在看的人 · 工具图标 · 主按钮 · ⋯",
    "下面依次是视图标签（下划线，36px）、工具栏、内容；最后一块占满剩余高度",
  ],
  states: [
    "图标栏当前模块：浅一档的块",
    "目录当前表：白块 + 细边（目录本身是浅灰底，所以不用主色浅底），比悬停明显",
    "搜不到：「没有找到「xx」 清除」",
    "收起目录：标题栏左边出「展开目录」",
    "手机：图标栏变底栏（4 个 + 更多），目录从左边拉出；标题栏只留名字、☆、胶囊名字、分享、⋯",
  ],
  dos: [
    "目录数量统一放在右侧灰字，文件夹和表一样的写法。",
    "范围胶囊传 icon，用「层」这类一看就是切换范围的图标；kind 写清是什么范围（默认「业务线」）。",
    "标题栏最多一个实心主按钮（分享）；评论、自动化、权限放 tools 图标按钮，手机上收进 ⋯。",
    "正在看的人用 presence（每人一种底色，超过的 +N）。",
  ],
  donts: [
    "不要在文件夹名里写「资料（1）」这种括号数量，和右侧数量两种写法混用。",
    "目录当前行不要只是浅灰底，和悬停分不出。",
    "范围切换不要用看不出意思的「滑块」图标；手机上胶囊至少留下名字。",
    "正在看的人不要都画成同一个颜色的圆叠在一起。",
    "一个模块里不要同时有 AdminShell 侧栏和自己画的左栏两套外壳。",
  ],
  a11y: [
    "图标栏是 nav（aria-label「模块」），每格有名字，带数字时读作「通知（12）」；当前模块 aria-current。",
    "目录树用方向键上下移动，→ / ← 展开收起文件夹；当前表 aria-current。",
    "☆ 是开关按钮（aria-pressed），范围胶囊的名字读作「当前业务线：中小企业，点一下切换」。",
    "手机目录抽屉 Esc 关闭。",
  ],
  demos: [
    {
      id: "navigation/rail-shell-workspace",
      title: "图标栏 + 目录 + 标题栏",
      description: "点目录换表、点胶囊切业务线、点 ☆ 收藏；手机宽度下图标栏变底栏。",
      height: 600,
      bleed: true,
    },
  ],
};

const tabs: ComponentDoc = {
  slug: "tabs",
  title: "页内标签与分区页",
  subtitle: "Tabs · TabbedPage · ScrollStrip",
  group: "navigation",
  importFrom: "@adminui/react",
  summary: "页面 / 记录里的分区只用下划线标签：选中深主色字 + 加粗 + 2px 线，没有浅底块。放不下时两头渐隐，右端「更多 ⌄」。",
  keywords: "tabs tab tabbed-page scroll-strip underline sections overflow 标签 页签 分区 下划线 更多 数量 分区页",
  when: [
    "一条记录的分区（资料 / 跟进 / 商机 / 附件）。",
    "一个页面分成几块各自独立的内容（成员 / 部门 / 邀请）：用 TabbedPage。",
    "栏或卡片里的视图切换：Tabs size=\"sm\"（36px）。",
  ],
  whenNot: [
    "在 2–5 个筛选值里选一个（进行中 / 已完成）—— 用 SegmentedControl。",
    "已经打开的页面 —— 那是外壳的工作标签（胶囊），不是 Tabs。",
  ],
  anatomy: [
    "标签：40px（栏里 36），字间距 24；下划线和字等宽、2px",
    "数量：灰色小胶囊；选中时主色浅底；countTone 为 attention / danger 时用注意 / 异常色",
    "图标可选，默认不放；放就整排都放",
    "ScrollStrip：Tabs 和工作标签底下共用的横向滚动条带，负责渐隐、滚轮横滚、把选中项滚进视野",
  ],
  states: [
    "选中：深主色字 + 加粗 + 下划线",
    "悬停：灰色下划线",
    "禁用：淡字，不能选",
    "键盘聚焦：字外一圈主色框",
    "放不下：两头渐隐，「更多 ⌄」菜单列出全部",
  ],
  dos: [
    "TabbedPage 的分区值放进 URL 或宿主状态，刷新后回到同一分区。",
    "要处理的数量（逾期、未填）才用 countTone，其余保持灰色。",
    "分区里有轮询 / 实时刷新时，用 render 的 active 参数在看不见时暂停。",
    "下划线标签、胶囊、分段控件各管一件事：分区 / 换个看法 / 选筛选值。",
  ],
  donts: [
    "不要给选中标签同时加「浅底块 + 下划线」两样。",
    "同一个组件不要在不同宽度下变成三种长相（卡片导航 → 胶囊 → 下划线）。",
    "不要用压在标签文字上的左右圆箭头，看不出后面还有几个。",
    "不要每个标签都配一个风格各异的图标，图标读起来比字还慢。",
    "数量徽标不要用四五种颜色区分状态。",
  ],
  a11y: [
    "role=\"tablist\" / \"tab\" / \"tabpanel\"，选中 aria-selected，label 是标签组的名字（必填）。",
    "漫游 tabindex：Tab 进入选中项，← → 切换，Home / End 到首尾，跳过禁用项。",
    "自己渲染面板时传 panelId 和 idBase，让面板 aria-labelledby 对应标签。",
    "数量写在标签名里一起读出（「跟进 28」）。",
  ],
  demos: [
    { id: "navigation/tabs-basic", title: "下划线标签：数量、要处理、禁用", height: 160 },
    { id: "navigation/tabs-overflow", title: "放不下：渐隐 +「更多 ⌄」", height: 200 },
    { id: "navigation/tabbed-page", title: "分区页 TabbedPage", height: 260 },
  ],
};

const splitWorkspace: ComponentDoc = {
  slug: "split-workspace",
  title: "分栏工作区",
  subtitle: "WorkspaceLayout · Pane · PaneSection · SplitLayout · ListDetailLayout",
  group: "navigation",
  importFrom: "@adminui/react",
  summary: "列表 + 详情 + 右栏的工具页：贴着工作标签和窗口边，栏间一条线，栏头都是 48px，每栏自己滚。窄屏统一「先列表，点进详情」两步走。",
  keywords: "workspace-layout pane pane-section split-layout list-detail master-detail columns 分栏 三栏 两栏 列表详情 工作区 栏头 侧栏 右栏",
  when: [
    "左边选一项、中间看 / 改它的工具页：角色与权限、会话、模板。",
    "整页高度固定、每栏各自滚动的工作区：WorkspaceLayout。",
    "一张卡片里的列表 + 详情：ListDetailLayout；主栏 + 右侧小卡片：SplitLayout。",
  ],
  whenNot: ["单栏阅读页（文档、文章）—— 不用分栏，也不走两步。"],
  anatomy: [
    "WorkspaceLayout：left（默认 240）· 中间 · right（默认 280）；宽屏贴边、栏间一条线",
    "Pane：栏头 48（图标块 + 标题 + 灰数量 + 小字 + ? + 右侧 ghost 图标按钮）· notice · 自己滚的 body · footer",
    "PaneSection：栏 / 卡片里的分组小标题（数量 + 操作）；flush 时标题在浅色带上、内容贴边",
    "SplitLayout：主栏 + 右侧 340 小卡片栏，1100px 以下叠成一列",
  ],
  states: [
    "列表选中行：主色浅底 + 加粗 + 图标变主色；两行内容 52px",
    "栏里的空 / 加载 / 出错都在栏正中，栏头照样在",
    "1100px 以下几栏叠成一张圆角卡，页面正常滚动（narrow=\"flush\" 不要卡片边框）",
    "窄屏（≤ 760）narrow=\"steps\"：先列表，点一行进详情，左上「← 返回」；右栏跟在详情下面",
  ],
  dos: [
    "每个栏头同高，横着看成一条线；数量灰色跟在标题后面。",
    "栏头操作用 ghost 图标按钮；分组小标题和行文字左对齐。",
    "列表 + 详情传 onBack + detailOpen（WorkspaceLayout 再加 narrow=\"steps\"），手机上自动两步走。",
    "列表、表格放进 Pane 时 padding 用默认 \"none\"，内容自己贴边；表单、文字用 \"md\"。",
  ],
  donts: [
    "不要让左栏搜索行、中间标题行、标签行各自一个高度。",
    "选中行不要只是浅灰底（和悬停一样）。",
    "栏里的动作不要用彩色链接字，用和别处一样的按钮。",
    "手机上不要做「换一个」按钮，也不要把几栏上下叠成一张长卡。",
  ],
  a11y: [
    "每个 Pane 是 section，名字取 title（不是字符串时传 label）。",
    "列表行是按钮，选中 aria-current；窄屏返回条的按钮读出「返回列表」之类的目的地。",
    "每栏自己滚动时，焦点移动会把聚焦项滚进视野；不要给栏加 overflow: hidden 截断焦点光圈。",
  ],
  demos: [
    {
      id: "navigation/workspace-layout",
      title: "三栏工作区（窄屏两步走）",
      description: "宽于 1100px 时三栏并排（点预览右上角在新窗口打开看）；761–1100 叠成一张卡；窄到 390 先看列表，点一行进详情。",
      height: 560,
      bleed: true,
    },
    { id: "navigation/list-detail", title: "卡片里的列表 + 详情", height: 400 },
    { id: "navigation/split-layout", title: "主栏 + 右侧小卡片", height: 300 },
  ],
};

const settingsNav: ComponentDoc = {
  slug: "settings-nav",
  title: "设置侧导航",
  subtitle: "SideNavLayout · SaveBar · SettingsSheet",
  group: "navigation",
  importFrom: "@adminui/react",
  summary: "设置页左边 200 一列分节导航，直接在画布上；改过的节琥珀圆点、出错的节红叹号；整页只有一条吸底保存条。抽屉里的设置用 SettingsSheet。",
  keywords: "side-nav-layout settings save-bar settings-sheet section-nav sticky 设置 侧导航 分节 保存条 未保存 表设置 抽屉",
  when: [
    "个人资料、公司设置这类分节多、要一起保存的设置页：SideNavLayout + SaveBar。",
    "从一张表 / 一个对象打开的设置（表设置、看板设置）：SettingsSheet 抽屉。",
  ],
  whenNot: ["只有 3–5 个字段的设置 —— 一张卡片 + 一条 SaveBar 就够了，不要分节。"],
  anatomy: [
    "左 200：分组小标题 + 34px 行（图标 + 名字）；吸顶，往下滚自动跟着亮",
    "行尾：没保存的节琥珀圆点，出错的节红色叹号",
    "SaveBar：「改了 2 项还没保存（哪几项）· 放弃 · 保存」，吸在底部中间；没改动就不显示",
    "SettingsSheet：880 宽，头部「标题 · 对象名」+ ×；左 184 分节；右边一次一节；底部固定「改了 N 处 · 取消 · 保存」",
  ],
  states: [
    "当前节：主色浅底 + 加粗",
    "保存中：保存按钮转圈；onSave 抛错时保存条留着并显示原因",
    "有错误时（errors > 0）保存条说明有几处要改",
    "1100px 以下：分节导航变成一排胶囊，横着滑；手机上 SettingsSheet 铺满一屏、分节在上",
  ],
  dos: [
    "改过的字段用 FormField changed 标「已改」，用 useChangeTracker 算出 count 和 summary。",
    "整页只用一条 SaveBar；放弃 = 回到上次保存的值。",
    "分节的 dirty / error 跟着表单状态走，让人在左边就能看到哪节有问题。",
    "立即生效的开关不计入改动数。",
  ],
  donts: [
    "不要把左导航包进一张比内容卡还显眼的白卡片。",
    "不要每张卡片各放一个「保存」按钮。",
    "设置抽屉不要做成一长串卡片让人一直往下滚找。",
    "出错的分节不要只在内容里提示，左边导航上也要能看出来。",
  ],
  a11y: [
    "分节导航是 nav（label 必填，如「我的资料分节」），当前节 aria-current。",
    "琥珀点和红叹号都有读屏名字（「有未保存的改动」、出错原因），不只靠颜色。",
    "SaveBar 是一个 aria-live 区域，改动数变化会被播报。",
    "SettingsSheet 打开时焦点进入抽屉，关闭后回到触发按钮；有改动时关闭会先确认。",
  ],
  demos: [
    { id: "navigation/side-nav-layout", title: "设置页 + 吸底保存条", description: "改姓名看琥珀圆点和保存条；把时区改成「8」看红叹号。预览框不到 1100px，导航显示为胶囊；在新窗口打开看左侧导航。", height: 460 },
    { id: "navigation/settings-sheet", title: "表设置抽屉 SettingsSheet", height: 160 },
  ],
};

const pageHeader: ComponentDoc = {
  slug: "page-header",
  title: "页面头 · 区块标题 · 面包屑",
  subtitle: "PageHeader · HelpTip · Breadcrumbs · PageBody · Panel · ResourcePanel",
  group: "navigation",
  importFrom: "@adminui/react",
  summary: "页面一进来就是按钮和内容：列表页不写大标题，PageHeader 的按钮和「?」并进第一张卡的标题行。区块标题分三级，面包屑灰色、当前页加粗。",
  keywords: "page-header page-body panel resource-panel help-tip breadcrumbs section-title card-title record-header 页面头 标题 卡片标题 区块 分组 说明 问号 面包屑",
  when: [
    "每个后台页面的开头：PageHeader（按钮 + 页面说明）+ PageBody（统一的块间距）。",
    "一块内容一张卡：Panel；列表 / 资源（带数量、筛选、反馈）：ResourcePanel。",
    "标题旁边的一段解释：HelpTip「?」，不写成一段介绍文字。",
  ],
  anatomy: [
    "列表页：PageHeader 不显示大标题（只给读屏），按钮并进第一张卡的标题行，右侧最多一个主按钮",
    "记录页：面包屑一行 → 头像块 + 名字 + 状态 + 一行灰字（负责人 · 地区 · 更新时间）+ 右侧按钮 → 下划线分区标签",
    "卡片标题 48：标题 + 灰数量 + ? + 右侧操作；卡片里分组 32（PaneSection）；贴边色带（PaneSection flush）",
    "面包屑：13px 灰色、小箭头分隔，当前页深色加粗；太深中间收成 …",
  ],
  states: [
    "面包屑悬停：变深 + 浅底；当前页不可点",
    "HelpTip：悬停 / 聚焦打开，点击钉住，点外面或 Esc 关；手机点一下",
    "ResourcePanel 第一次加载：数量写「—」，不写 0",
    "手机：面包屑只留「← 上一级」",
  ],
  dos: [
    "页面说明写进 PageHeader / Panel 的 description，自动收成「?」。",
    "数量用 count（ResourcePanel 加 unit 读作「客户 24 个」），不要写在括号里。",
    "没有外壳的页面（客户门户、独立工具）才用 showTitle 显示大标题。",
    "面包屑只在记录页、文档页这类有层级的地方用；列表页的位置由外壳顶栏说明。",
  ],
  donts: [
    "不要在列表页顶部再写一遍大标题和一段介绍。",
    "面包屑不要用绿色链接字和斜杠分隔；绿色只留给真正的链接和主操作。",
    "卡片标题行不要有的 48 有的 50、数量一会儿括号一会儿灰字、「?」位置不一。",
    "记录页面包屑下面不要直接是标签，缺了名字和状态。",
    "卡片里的分组标题不要自己画，用 PaneSection 统一字号。",
  ],
  a11y: [
    "PageHeader 的 title 始终是 h1（不显示时仅读屏可见），页面只有一个 h1。",
    "HelpTip 的「?」是按钮，名字默认「说明」，建议写成「客户页说明」；卡片可被键盘打开和关闭。",
    "面包屑 nav 的当前页 aria-current=\"page\"；折叠的「…」是菜单按钮。",
    "「?」图标 16px，点击区 24px。",
  ],
  demos: [
    { id: "navigation/page-header-list", title: "列表页：按钮并进第一张卡", height: 380 },
    { id: "navigation/page-header-record", title: "记录页头部", height: 220 },
    { id: "navigation/section-titles", title: "区块标题三级 + HelpTip", height: 300 },
  ],
};

const pagination: ComponentDoc = {
  slug: "pagination",
  title: "分页与加载更多",
  subtitle: "DataTable · LoadMore",
  group: "navigation",
  importFrom: "@adminui/react",
  summary: "表格用页码（DataTable 的 pagination），时间线 / 动态 / 评论用「加载更多」。总数和范围写清楚，当前页是主色浅底 + 加粗，不是实心块。",
  keywords: "pagination pager page cursor load-more infinite 分页 页码 游标 每页条数 加载更多 到底 重试",
  when: [
    "服务端分页的表格：pagination={{ mode: \"page\" }}；服务端不给总数：mode: \"cursor\"。",
    "一次全部加载的短表（十几行配置）：mode: \"all\"，只写共几条。",
    "时间线、动态、评论这类往下读的流：LoadMore。",
  ],
  anatomy: [
    "左：「共 1,284 条 · 第 41–60 条」（千分位）",
    "右：每页条数（28px 下拉）· ‹ 1 … 32 33 34 … 65 ›",
    "游标：「第 2 页」+ 两个箭头",
    "LoadMore：一整行「加载更多 · 已显示 50 / 共 128 条」",
  ],
  states: [
    "翻页中：旧行留着变淡（refreshing），页码不能连点",
    "只有一页：不出页码，只写共几条",
    "手机 / 窄卡：「‹ 3 / 65 ›」，每页条数藏起来",
    "LoadMore 加载中转圈；失败 = 异常色说明 +「重试」；到底 =「已经到底了 · 共 128 条」",
  ],
  dos: [
    "总数不准时别硬写，用 cursor 模式（类型上禁止给 cursor 传 total）。",
    "翻页用 refreshing 保留旧行，第一次加载才用 loading 骨架。",
    "LoadMore 传 total 让人知道还剩多少；失败时 error 写人话原因。",
  ],
  donts: [
    "不要只写「第 1 页」而不写一共多少条。",
    "页码按钮不要每个带框、当前页不要用实心主色块，一排下来太重。",
    "不要把「共 1,284 条」和「第 3 / 65 页」两种说法重复摆在一起；数字要有千分位。",
    "「加载更多」不要做成一个小胶囊按钮，也不要缺加载中 / 失败 / 到底三种样子。",
    "手机上不要让「每页条数、上一页、下一页」挤成两三行。",
  ],
  a11y: [
    "页码按钮读作「第 3 页」，当前页 aria-current=\"page\"；上一页 / 下一页在首尾禁用。",
    "每页条数下拉有名字「每页条数」。",
    "LoadMore 的进度用 role=\"status\" 播报，失败说明用 role=\"alert\"；「重试」是普通按钮，键盘可达。",
  ],
  demos: [
    { id: "navigation/pagination-page", title: "页码分页", description: "翻页时旧行变淡；窄到 390 看简洁版。", height: 520 },
    { id: "navigation/pagination-cursor", title: "游标分页（没有总数）", height: 240 },
    { id: "navigation/load-more", title: "加载更多：加载中 / 失败 / 到底", description: "连点几次：第二次故意失败，重试后继续，最后到底。", height: 300 },
  ],
};

const steps: ComponentDoc = {
  slug: "steps",
  title: "步骤与向导",
  subtitle: "Steps · WizardLayout",
  group: "navigation",
  importFrom: "@adminui/react",
  summary: "24px 圆的步骤条：做完是浅主色底 + 勾，当前实心主色，等别人用注意色，出错用异常色 ×。WizardLayout 给多步操作一个统一外框。",
  keywords: "steps stepper wizard progress process import 步骤 步骤条 向导 进度 流程 导入 审批 下一步",
  when: [
    "多步操作：导入、开通、初始化 —— WizardLayout。",
    "展示一个流程走到哪了：报价审批、开通进度、工单处理 —— Steps。",
    "窄栏、卡片里的长流程：orientation=\"vertical\"。",
  ],
  anatomy: [
    "圆 24px + 名字 + 一行说明（谁、什么时候）",
    "线段自动铺满剩下的宽度（stretch）；做完的线是主色",
    "WizardLayout：头部标题 + 说明 + × · 步骤条 · 一次一步的内容 · 底部「原因 + 上一步 / 下一步」",
  ],
  states: [
    "做完：浅主色底 + 勾，字是正文色",
    "当前：实心主色 + 一圈浅光 + 加粗",
    "等别人（status: \"waiting\"）：注意色",
    "出错（status: \"error\"）：异常色 ×",
    "没到：细边灰圈 + 数字",
    "手机：横排只留圆和当前步的字；或用竖排",
  ],
  dos: [
    "每步写一行说明：「等林晓确认 · 已等 2 天」比单靠颜色清楚。",
    "允许返回修改时传 onStepClick，做完的步骤变成可点。",
    "下一步不能点时用 nextDisabledReason 写原因，显示在按钮旁边。",
    "最后一步把「下一步」改成具体的动作（「完成导入」）。",
  ],
  donts: [
    "做完的步骤不要用灰字，看起来像禁用。",
    "不要把步骤挤在左边、线段固定长，或在同一产品里混用两种节奏。",
    "「出错」「等别人」不要只靠颜色表达，要有图标和说明。",
    "手机上横排步骤不要被直接截掉。",
  ],
  a11y: [
    "步骤条是 ol（aria-label 如「导入步骤」），当前步 aria-current=\"step\"。",
    "做完、出错、等待这些状态有文字读出，不只靠圆的颜色。",
    "可点的做完步骤是按钮，键盘可达。",
  ],
  demos: [
    { id: "navigation/steps-states", title: "五种状态、说明行、竖排", description: "第一条可以点做完的步骤回去。", height: 460 },
    { id: "navigation/wizard-layout", title: "导入向导 WizardLayout", height: 380 },
  ],
};

const publicLayout: ComponentDoc = {
  slug: "public-layout",
  title: "公开页外框",
  subtitle: "PublicPageLayout · PublicResult · AuthLayout · LoginForm",
  group: "navigation",
  importFrom: "@adminui/react",
  summary: "不在后台外壳里的页面：登录页、对外表单、提交结果。白色品牌带 + 居中一栏；登录按钮永远能点，点了再说缺什么。",
  keywords: "public-page-layout public-result auth-layout login-form login sign-in public form result 登录 登录页 公开表单 结果页 提交成功 链接失效 品牌带",
  when: [
    "登录 / 选择账号：AuthLayout + LoginForm。",
    "发给外部的人填的表单、申请页：PublicPageLayout。",
    "提交成功、链接失效、已撤回：PublicResult。",
  ],
  anatomy: [
    "登录：居中 420 一栏；卡片里 标志方块 +「登录 产品名」+ 一行说明；账号 / 密码带图标、密码可显示；「7 天内自动登录」+「忘记密码」",
    "公开表单：白色品牌带（标志 + 名字 + 小字）+ 右上「已填 2 / 5 题」+ 带底细进度线；标题 22px",
    "结果页：大圆图标 + 标题 + 一句下一步 + 灰色时间 + 按钮",
  ],
  states: [
    "登录空着点：每个字段下面一行异常色说明",
    "密码错：卡片顶上一条异常提示（还能试几次、找谁重置）",
    "登录中：按钮转圈",
    "结果页 tone：success / info / warning / danger（失效页）",
    "手机：卡片铺满、品牌带吸顶，能点的都是 44px",
  ],
  dos: [
    "LoginForm 的 onSubmit 失败时 throw Error(人话原因)，卡片顶上原样显示。",
    "公开表单传 progress，让填写的人知道还剩几题。",
    "结果页说清下一步会发生什么、什么时候（「1 个工作日内联系你」）。",
    "页面底部 footer 写一句隐私说明或求助方式。",
  ],
  donts: [
    "不要在字段没填时把登录按钮置灰（淡色主按钮像坏了）；永远能点，点了再提示。",
    "登录页不要只有一张写着「登录」的光卡片，没有标志、没有说明。",
    "公开页的主按钮不要用渐变；平面纯色。",
    "手机上不要四周留大块空白、输入框小于触屏尺寸。",
    "密码错误的提示不要藏在不显眼的位置。",
  ],
  a11y: [
    "登录卡片 aria-labelledby 标题；空着提交时缺的字段标 aria-invalid、下面写原因，并聚焦第一个缺的字段。",
    "密码框的眼睛按钮有名字（「显示密码」），切换后焦点不丢；登录失败是卡片顶上一条提示。",
    "可点区域在手机上 44px（--aui-control-height-touch）。",
    "结果页的状态图标不是唯一信息：标题文字说明结果。",
  ],
  demos: [
    { id: "navigation/login", title: "登录页", description: "直接点「登录」看字段提示；密码少于 8 位看卡片顶上的错误。", height: 600, bleed: true },
    { id: "navigation/public-form", title: "公开表单 → 提交结果", description: "边填边看右上进度；提交后换成结果页。", height: 640, bleed: true },
    { id: "navigation/public-result", title: "结果页四种语气", height: 340 },
  ],
};

export const navigationDocs: readonly ComponentDoc[] = [
  adminShell,
  workTabs,
  railShell,
  tabs,
  splitWorkspace,
  settingsNav,
  pageHeader,
  pagination,
  steps,
  publicLayout,
];
