import type { ComponentDoc } from "./types";

const IMPORT = "@adminui/react/views";

const viewTabs: ComponentDoc = {
  slug: "view-tabs",
  title: "视图标签与视图管理",
  subtitle: "ViewTabs · ViewManager · ViewLockNotice",
  group: "views",
  importFrom: IMPORT,
  summary: "数据表上方的一行视图标签：类型图标 + 名字 + 档位记号（标准 / 共享 / 我的），放不下的进「更多」；右侧「视图」打开视图管理，「+」新建视图。",
  keywords: "view tabs view manager 视图 标签 视图管理 新建视图 标准视图 共享视图 我的视图 更多",
  when: [
    "同一张表有表格、看板、日历、甘特等多个视图，用户要在它们之间切换。",
    "视图分三档：管理员维护的标准视图、一组人共享的视图、只有自己看得到的视图。",
    "用户要排序、隐藏、改名、复制、删除自己的视图。",
  ],
  whenNot: ["页面级导航（客户 / 订单 / 报表）—— 用侧栏或 Tabs。", "快捷筛选（公海、我负责的、停滞）—— 放到工具栏右边做胶囊，不占标签行。"],
  anatomy: [
    "视图标签：类型图标 + 名字 + 档位记号（标准 = 小锁，共享 = 两个人，我的 = 不加）",
    "当前标签：加粗 + 2px 主色下划线 + ⋯（和右键 / Shift+F10 是同一个菜单）",
    "「更多 N」：放不下的标签，按 标准 / 共享 / 我的 分组，最下面「管理视图…」",
    "「+」新建视图：6 张类型卡（图标 + 一句用途）+ 名字 + 给谁看",
    "右侧「视图」按钮：打开 ViewManager；宿主的 trailing（如仪表盘组）在它右边",
  ],
  states: [
    "改了标准 / 共享视图（modified）：标签上一个注意色小点，标签下一行提示只对自己生效",
    "隐藏的视图不进标签栏；必看视图（mustSee）总在，眼睛禁用并写原因",
    "视图管理里隐藏的行变灰划线；眼睛悬停才出现",
    "手机（≤ 760px）：标签一行横滑、两边渐隐、当前标签滚到中间；视图管理和新建视图是底部弹层",
  ],
  dos: [
    "标签按 标准 → 共享 → 我的 排，当前视图永远留在标签栏里。",
    "用 viewActions(view, policy) 决定菜单里哪些能点，不能点的写 disabledReason；服务端照样校验。",
    "视图管理的 tierNotes 写清每档谁维护：「管理员维护」「华东组 · 组长维护」「只有你看得到」。",
    "普通成员改标准视图的筛选时提示只对自己生效，并给「复制为我的视图」（ViewLockNotice）。",
    "createAudiences 只在用户有共享权限时加 \"shared\"。",
  ],
  donts: [
    "不要把快捷筛选挤进标签行 —— 宽屏也只剩一个标签，其余全进「更多」。",
    "不要让仪表盘组在手机上盖住视图标签；手机上它收进「视图」面板。",
    "「更多」菜单不要不分档；两个同名视图要能分清是谁的。",
    "档位不要用带边框的文字标签；用小图标记号。",
    "删除确认框不要被视图管理弹层压在下面。",
    "改了标准视图不要静默只对自己生效，要有小点和一行提示。",
  ],
  a11y: [
    "标签栏是 tablist，←/→ 在标签间移动，Enter 打开；当前标签 aria-selected。",
    "当前标签的菜单：⋯ 按钮、右键、Shift+F10 三个入口；双击或 F2 就地改名。",
    "视图管理里 Alt+↑/↓ 在本档内排序；搜索时不能拖动。",
    "档位记号有读屏文字（「标准视图」「共享视图」），不只靠图标。",
  ],
  demos: [
    { id: "views/view-tabs-manager", title: "标签 + 视图管理 + 新建视图", description: "点「+」新建，点右侧「视图」排序、隐藏、改名、删除；双击「我负责的」改名。", height: 220 },
    { id: "views/view-tabs-modified", title: "改了标准视图", description: "注意色小点 + 锁定提示，提供「复制为我的视图」。", height: 220 },
  ],
};

const kanban: ComponentDoc = {
  slug: "kanban",
  title: "看板",
  subtitle: "KanbanBoard",
  group: "views",
  depth: "deep",
  importFrom: IMPORT,
  summary: "按一个单选字段（如「阶段」）把记录排成列，拖卡片换列。先显示后保存：保存失败卡片放回原处；成功后可撤销。",
  keywords: "kanban board pipeline 看板 泳道 阶段 拖拽 drag drop 销售漏斗 列 合计 撤销",
  when: [
    "记录有一个流程性的单选字段（线索 → 赢单），用户按阶段推进。",
    "要一眼看到每个阶段有多少条、多少金额。",
    "卡片上只放每天要看的几样信息：金额、城市、负责人、下次跟进。",
  ],
  whenNot: ["要对比大量字段、批量编辑 —— 用表格（BitableGrid）。", "按日期排的工作 —— 用日历或甘特。"],
  anatomy: [
    "列：宽 280、圆角 12、浅底无边框；每列自己滚动",
    "列头：10 色软标签 + 条数 + 金额合计；＋ 和 ⋯ 悬停才出",
    "卡片：RecordCard 五个固定位（标签 · 关键数 · 底栏），默认不显示字段名",
    "「未设置」列：值为空或不在选项里的记录；没有记录就不显示",
    "列底：「还有 N 条 · 滚到底自动加载」/ 骨架卡；空列写「拖卡片到这里，或点 + 新建」",
    "底部居中提示条：拖动时「阶段：方案报价 → 商务谈判 · Esc 取消」",
  ],
  states: [
    "拖动中：卡片微倾 + 深阴影，原位置 35% 透明；落点虚线框写「松开放到「商务谈判」」",
    "保存中：卡片已在新列；Promise reject → 放回原处并播报原因",
    "放下后：提示「阶段：线索 → 方案报价」带「撤销」",
    "锁住（canMove 返回 false）：标题右边小锁，按住时提示条写 lockReason",
    "列收起：44px 竖条；隐藏的列从「隐藏的列」恢复",
    "手机：顶部列切换胶囊（带条数），一列 86% 宽横滑吸附",
  ],
  dos: [
    "records 用 useMemo 保持引用；每次渲染新建数组会让刚拖过去的卡片闪回。",
    "onMove 返回 Promise：失败就 reject，组件负责放回原处。",
    "服务端分页时用 columnMeta[key].total / summary 给整列条数和合计，不要按已加载的卡片算。",
    "按阶段分组时，卡片标签行不要再放阶段（cardSlots.tags 去掉分组字段）。",
    "有些记录不能挪（赢单只有主管能改）就给 canMove + lockReason，让用户知道原因。",
  ],
  donts: [
    "不要在卡片上把每个字段都列一行带字段名，空值也不要画「—」：一列一屏只剩 4 张。",
    "列头不要用带边框的旧标签或实底白字；用 10 色软标签。",
    "列、卡片不要同时加边框和阴影，三层线显得乱。",
    "「未设置」0 条时不要常驻一列。",
    "拖动提示不要压在卡片上挡住落点；放到底部居中。",
    "不要给列写任意 CSS 颜色；列颜色只用选项 10 色。",
  ],
  a11y: [
    "卡片可聚焦：Alt+←/→ 换列，Alt+↑/↓ 列内移动，Shift+F10 打开「移到…」菜单。",
    "拖动中 Esc 取消；移动结果和失败原因通过 live region 播报。",
    "label 是整个看板的读屏名称（「商机阶段看板」）。",
    "列多于屏幕时边缘渐隐 + ‹ › 翻页按钮，键盘也能翻；滚到底自动加载，同时保留按钮给键盘用户。",
  ],
  demos: [
    {
      id: "views/kanban-playground",
      title: "在线调试",
      description: "拖卡片换阶段；打开「模拟保存失败」后再拖，卡片会放回原处。",
      height: 540,
      controls: [
        { name: "density", label: "密度 density", type: "select", options: ["normal", "compact"], default: "normal" },
        { name: "sumTotals", label: "列头合计 sumField", type: "boolean", default: true },
        { name: "showLabels", label: "显示字段名 showLabels", type: "boolean", default: false },
        { name: "cover", label: "封面 cardAttachments", type: "boolean", default: false },
        { name: "lockWon", label: "锁住赢单 canMove", type: "boolean", default: true },
        { name: "undo", label: "放下后可撤销 undo", type: "boolean", default: true },
        { name: "failSave", label: "模拟保存失败（onMove reject）", type: "boolean", default: false },
      ],
    },
    { id: "views/kanban-rollback", title: "保存失败放回原处", description: "onMove reject：卡片回到原位，读屏播报原因。", height: 560 },
    { id: "views/kanban-load-more", title: "服务端分页、列合计与列菜单", description: "「线索」列共 128 条，滚到底加载下一页；列 ⋯ 收起 / 隐藏 / 换颜色。", height: 540 },
  ],
  props: [
    {
      component: "KanbanBoard",
      rows: [
        { name: "records", type: "readonly T[]", description: "已筛好、排好的记录；用 useMemo 保持引用" },
        { name: "recordId", type: "(record: T) => string", description: "记录的唯一 id" },
        { name: "groupField", type: "GridField<T>", description: "分列的单选字段：列 = 它的 options 和色调" },
        { name: "cardTitle", type: "(record: T) => string", description: "卡片标题（主字段文字）" },
        { name: "label", type: "string", description: "必填：看板的读屏名称" },
        { name: "cardSlots", type: "RecordCardSlots<T>", description: "卡片五个固定位：tags · keyline · owner · due · comments" },
        { name: "onMove", type: "(recordId, toValue, beforeId) => void | Promise<void>", description: "先显示后保存；reject 放回原处。toValue 为 null = 「未设置」；beforeId = 落点下面那张（null = 列尾）" },
        { name: "undo", type: "boolean", default: "true", description: "放下后出「阶段：A → B · 撤销」（需要 NotificationProvider）" },
        { name: "canMove / lockReason", type: "(record: T) => boolean / string", description: "锁住个别记录：标题旁小锁，按住时提示原因" },
        { name: "sumField", type: "GridField<T>", description: "按已加载卡片求和显示在列头；整列合计用 columnMeta.summary" },
        { name: "columnMeta", type: "Record<string, { total?, hasMore?, loading?, summary? }>", description: "按列（选项值或 KANBAN_UNSET）给服务端条数、分页、加载中、合计" },
        { name: "onLoadMore", type: "(value: string | null) => void", description: "某列滚到底时加载下一页" },
        { name: "columnState / onColumnStateChange", type: "KanbanColumnState", description: "收起 / 隐藏的列和列颜色；受控保存" },
        { name: "density / showLabels", type: '"compact" | "normal" / boolean', default: '"normal" / false', description: "卡片密度、是否显示字段名" },
        { name: "selectedId", type: "string | null", description: "右侧抽屉里正打开的那张卡片高亮" },
        { name: "onOpen / onAdd", type: "(record) => void / (value) => void", description: "点卡片打开记录；列头 ＋ / 列底「新建记录」" },
      ],
    },
  ],
};

const recordCard: ComponentDoc = {
  slug: "record-card",
  title: "记录卡片",
  subtitle: "RecordCard",
  group: "views",
  importFrom: IMPORT,
  summary: "看板、画册里同一张卡片：封面 → 标题 → 标签行 → 关键数行 → 底栏，五个固定位。没填的字段不占行。",
  keywords: "record card 卡片 记录卡片 封面 标签 负责人 下次跟进 逾期 slots",
  when: [
    "在看板、画册或自定义列表里把一条记录画成卡片。",
    "每天要看的信息（负责人、下次跟进）需要固定位置，不随字段顺序跑。",
  ],
  whenNot: ["要看全部字段 —— 打开记录展开框。", "统计数字卡片 —— 用仪表盘的 KPI 卡。"],
  anatomy: [
    "封面（可选，16:10；紧凑 4:3）：没图 = 中性底 + 图标；右下角「图 N」或圆点",
    "标题：14px 加粗，最多两行；锁住时右边小锁",
    "标签行：单选 / 多选值 = 10 色软标签 20px，最多 3 个 +「+N」",
    "关键数行：金额加粗等宽 · 其余用「 · 」接上，一行省略",
    "底栏：负责人头像 + 名字 | 评论数 + 下次跟进（今天 = 注意色，逾期 = 异常色）",
  ],
  states: [
    "平时只有 1px 线；悬停边加深 + 轻阴影 + 右上角「展开」",
    "键盘聚焦 / 选中：主色边 + 3px 光圈（和输入框同一个）",
    "拖动中 dragging：微倾 + 深阴影；原位置 ghost：35% 透明",
    "锁住 locked：标题右边小锁，字符串 = 悬停原因",
    "加载 loading：骨架卡",
  ],
  dos: [
    "视图把同一套 cardSlots 传给每张卡；看板和画册共用一份。",
    "默认不显示字段名；用户在卡片设置里打开「显示字段名」才变两列对齐。",
    "点封面开大图（onOpenCover），点卡片别处开详情（onOpen）。",
    "today + timeZone 一起传，「今天 / 明天 / 逾期 N 天」才算得对。",
  ],
  donts: [
    "不要默认给卡片加阴影；满屏都是阴影。",
    "空字段不要画「—」占一行。",
    "没有附件不要画 150px 高的灰块 +「没有附件」；也不要画插画。",
    "不要把手机号、编号放进窄的两列标签布局里，会折行或被省略。",
    "悬停、选中、键盘聚焦不要各用一套样式；锁住的记录要有标记。",
  ],
  a11y: [
    "整张卡是一个点击目标（onOpen），Enter / 空格打开；封面是单独的按钮。",
    "选中状态用 aria-selected / aria-current，不只靠边框颜色。",
    "锁的原因在悬停和聚焦时都能看到。",
    "「逾期 N 天」用文字表达，不只靠异常色。",
  ],
  demos: [
    { id: "views/record-card-slots", title: "五个固定位", description: "切换密度、字段名和封面；点卡片看选中态。", height: 460 },
    { id: "views/record-card-states", title: "状态", height: 520 },
  ],
};

const gallery: ComponentDoc = {
  slug: "gallery",
  title: "画册",
  subtitle: "GalleryView",
  group: "views",
  importFrom: IMPORT,
  summary: "带封面的卡片墙：顶部一行控制（条数 · 封面字段 · 密度 · 字段名），网格自动列宽；点封面开大图，点卡片开记录。",
  keywords: "gallery card grid 画册 相册 卡片墙 封面 图片 lightbox",
  when: ["记录有照片、附件，看图比看字段更快（现场照片、商品、案例）。", "想以卡片浏览少量关键信息。"],
  whenNot: ["表里根本没有图片字段又要比较数字 —— 用表格。"],
  anatomy: [
    "顶部一行：条数 · 排序说明 | 封面字段下拉（含「不显示封面」）| 紧凑 / 常规 | 字段名开关",
    "网格：自动列宽，最小 236（紧凑 184），间距 16",
    "卡片：RecordCard 带封面",
    "末尾：骨架卡 +「已显示 12 / 18」，滚到底自动加载",
  ],
  states: [
    "筛选无结果：空状态写当前筛选 +「清空筛选」",
    "没有图片字段：默认不显示封面；有图片字段但这条没图：中性底 + 图标",
    "手机 2 列：不写字段名，负责人只留头像",
  ],
  dos: [
    "coverFields 传表里的图片 / 附件字段；为空时自动不显示封面。",
    "点封面开 MediaLightbox（lightbox 传下载、新窗口回调），或用 onOpenCover 换成自己的查看器。",
    "服务端分页：total + hasMore + onLoadMore。",
  ],
  donts: [
    "不要在没有照片的表上默认用附件做封面，整版都是灰块。",
    "封面选择、密度不要放在内容区右上另起一行，和条数挤开。",
    "深色模式下封面占位不要和卡片同色，要看得出是封面区。",
  ],
  a11y: [
    "网格是列表语义，每张卡可 Tab 聚焦，Enter 打开。",
    "大图里 ←/→ 切换，Esc 关，焦点回到封面。",
    "label 是画册的读屏名称。",
  ],
  demos: [
    { id: "views/gallery-basic", title: "画册", description: "切换封面字段、密度、字段名；滚到底加载更多。", height: 540 },
    { id: "views/gallery-empty", title: "没有封面字段 · 筛选无结果", height: 300 },
  ],
};

const calendar: ComponentDoc = {
  slug: "calendar",
  title: "日历",
  subtitle: "CalendarMonth · CalendarWeek",
  group: "views",
  importFrom: IMPORT,
  summary: "月 / 周 / 日日历：事件按选项色着色，节假日由宿主传入；拖事件改日期或时间，从「无日期」抽屉拖到某天就设上日期。",
  keywords: "calendar month week day 日历 月历 周视图 日程 节假日 调休 拖拽改期 无日期 agenda",
  when: [
    "记录有日期 / 时间字段（下次跟进、会议、实施期），要按时间看分布。",
    "要拖动改期、在某天就地新建。",
  ],
  whenNot: ["要看工期长短、先后关系 —— 用甘特。"],
  anatomy: [
    "工具栏：今天 · ‹ › · 标题 · 日 / 周 / 月 · 右上角图例「按「阶段」着色」",
    "全天 / 跨天事件：选项软底条，跨周拆段，续段前面带「‹」",
    "定时事件：色点 + 时间 + 标题，不铺底",
    "月格：最多 3 行 +「+N 更多」；周末和假日浅底，假日写「休 国庆日」，补班写「班」",
    "周 / 日：全天栏最多 2 行 + 展开；定时块软底 + 同色细边，重叠的并排；「现在」= 主色线 + 时间牌",
    "无日期抽屉 300 宽：搜索 + 40px 行（拖柄 · 名字 · 阶段标签）",
  ],
  states: [
    "点事件：事件卡（标签 · 时间 · 字段行；「打开详情」+「清除日期」）；双击直接开详情",
    "拖动：虚线预览写日期 / 时间；保存失败放回原处",
    "今天：主色圆底数字",
    "手机（窄于 agendaBelow 560）：月历缩成小格 + 彩点，下面是选中那天的日程；没有周 / 日视图",
  ],
  dos: [
    "全天事件用日期键（\"2026-10-13\"，end 含当天），定时事件用 ISO 瞬间并传 timeZone。",
    "节假日 / 调休由宿主按地区从服务端取，合成 workCalendar 传入；组件不带任何地区的日历。",
    "事件颜色跟单选字段选项的 tone；给 legend 说明按什么着色。",
    "events 用 useMemo 保持引用。",
  ],
  donts: [
    "不要所有事件同一种底色、没有图例；定时和全天事件不要长一个样。",
    "「现在」线和今天不要用两套强调色；都用主色，不用异常红。",
    "周视图全天事件后面不要再重复写日期，全天栏不要无限长压住时间刻度。",
    "「+N 更多」的列表里不要每条都重复一块「全天」。",
    "手机上不要硬塞 7 列周视图，名字会挤成「郭..」。",
  ],
  a11y: [
    "日子格方向键移动，Enter 新建（onCreate）；事件 Alt+←/→ 移一天、Alt+↑/↓ 移一周（周视图里是 30 分钟）。",
    "事件右键 / Shift+F10 菜单：打开详情 · 提前 / 推后 · 清除日期 + eventMenu。",
    "无日期抽屉里的记录可用菜单「放到今天 / 选中的那天」，不必拖动。",
    "标题区 aria-live，翻月后读出新月份。",
  ],
  demos: [
    { id: "views/calendar-month", title: "跟进日历（月 / 周 / 日）", description: "拖事件改日期；点右上「无日期」打开抽屉，把记录拖到某一天。", height: 620 },
    { id: "views/calendar-week", title: "周视图", description: "上下拖改时间、左右拖换天、拉底边改时长。", height: 580 },
  ],
};

const gantt: ComponentDoc = {
  slug: "gantt",
  title: "甘特",
  subtitle: "GanttView",
  group: "views",
  importFrom: IMPORT,
  summary: "左侧字段列表 + 右侧时间轴的排期视图：条形用选项软底，今天是主色线；拖条形改起止，可只算工作日。",
  keywords: "gantt timeline schedule 甘特 排期 时间轴 工期 工作日 里程碑 分组",
  when: ["记录有开始 / 结束（或工期），要看先后、重叠和进度：实施排期、项目计划、安装。", "要按负责人或小组分组看工作量。"],
  whenNot: ["只有一个日期字段的提醒 —— 用日历。"],
  anatomy: [
    "左侧：客户 / 负责人 / 开始 / 结束 / 工期等字段，和右侧行悬停同步；分组行可收起",
    "时间轴：默认「两周」刻度显示 15 天，今天在第 3 列；刻度 周 / 两周 / 季 / 年",
    "条形：选项色软底 + 同色细边 + 深色字（标题加粗）；放不下的字挪到条形右边",
    "今天：主色 2px 线 + 表头主色日期圆牌；周末浅底，假日斜纹 + 表头「休」",
    "里程碑：虚线 + 小牌；窗口外的记录在行边缘放「09-28 → 10-02」小牌",
  ],
  states: [
    "选中一条：两端出拖柄；拖动时提示「10-12 → 10-15 · 3 个工作日（含 1 天休息日不计）」",
    "不可编辑（canEdit 返回 false）：不能拖",
    "手机（窄于 listBelow 640）：按分组的列表 + 带今天线的进度小轨道",
  ],
  dos: [
    "分组由宿主做好（≤ 2 级 GanttGroup），视图只负责画。",
    "endMode 按数据选：field（结束日期字段）/ duration（工期天数）/ fixed（固定天数）。",
    "workdaysOnly 时工期跳过周末和宿主节假日，补班日照常算。",
    "保持默认的「两周」分栏；不要为了多看几天写死 listWidth。",
  ],
  donts: [
    "条形不要用主色实底白字，又粗又重。",
    "条外的文字不要压在今天线上。",
    "今天线不要用异常红。",
    "窗口外的记录不要在左边排一长串胶囊，看起来像一列按钮。",
  ],
  a11y: [
    "条形可聚焦：←/→ 移动一天，Shift+←/→ 改结束，Alt+←/→ 改开始，Enter 打开。",
    "分隔条可用 ←/→ 调宽，双击复原；« 收起左侧。",
    "label 是甘特的读屏名称；改期结果会播报。",
  ],
  demos: [{ id: "views/gantt-basic", title: "实施排期", description: "按负责人分组；拖条形改期，点选后拖两端改起止。", height: 500 }],
};

const viewSettings: ComponentDoc = {
  slug: "view-settings",
  title: "视图设置面板",
  subtitle: "CardSettings · CalendarSettings · GanttSettings · FieldOrderPicker · ViewSettingsFooter",
  group: "views",
  importFrom: IMPORT,
  summary: "看板 / 画册的卡片设置、日历设置、甘特设置共用一个骨架：标题写视图名和档位，分节，左标签右控件，底栏说明改动只对你生效。",
  keywords: "view settings card settings calendar settings gantt settings field order 视图设置 卡片设置 字段顺序 恢复 保存给所有人",
  when: ["工具栏上的「卡片设置」「日历设置」「甘特设置」按钮。", "让用户挑卡片上显示哪些字段、排什么顺序。"],
  anatomy: [
    "标题行：面板名 · 视图名 +（标准视图 / 共享视图）",
    "分节小标题 → 左 96px 标签、右控件（下拉、分段、开关、可删胶囊）",
    "卡片设置：实时预览卡 → 卡片（封面 · 密度 · 显示字段名）→ 卡片上的字段",
    "字段列表 FieldOrderPicker：拖柄 + 类型图标 + 名字 + 眼睛，主字段锁在第一个",
    "底栏 ViewSettingsFooter：左「改了只对你生效」/「已改 N 处」；右 恢复 · 另存为新视图 · 保存给所有人",
  ],
  states: [
    "没改：「恢复」禁用；改了：注意色小点「已改 1 处，只对你生效」",
    "没有维护权限：不出现「保存给所有人」",
    "手机：底部弹层 88% 高，底栏固定",
  ],
  dos: [
    "放进工具栏按钮下的 PopoverPanel 并给 sheet，手机自动变底部弹层。",
    "changes 用 countSettingChanges(shared, mine) 算。",
    "卡片设置给 preview：宿主用当前设置画一张 RecordCard。",
    "节假日日历、补班日由宿主合成 WorkCalendar 再传给日历 / 甘特。",
  ],
  donts: [
    "底栏不要压住字段列表最后一行。",
    "一个面板里不要上下排、左右排两种布局混用。",
    "眼睛不要一列绿一列灰；显示 / 隐藏用中性色和划线区分。",
    "没改动时不要让「恢复」可点；不要只在底栏小字里写作用范围。",
    "提示文字不要被截断；放不下就换行。",
  ],
  a11y: [
    "面板有标题（PopoverPanel title），Esc 关闭并把焦点还给按钮。",
    "字段列表 Alt+↑/↓ 排序，眼睛按钮有「显示 / 隐藏 某字段」的读屏名称。",
    "锁住的主字段写明「固定在第一个，不能移动或隐藏」。",
  ],
  demos: [
    { id: "views/view-settings-card", title: "卡片设置（带实时预览）", description: "点按钮打开；改密度或字段，预览卡和底栏「已改 N 处」同步变。", height: 160 },
    { id: "views/view-settings-gantt", title: "甘特设置 · 日历设置", height: 160 },
    { id: "views/field-order-picker", title: "字段列表", height: 520 },
  ],
};

const recordExpand: ComponentDoc = {
  slug: "record-expand",
  title: "记录展开框",
  subtitle: "RecordDetailDialog · RecordFrameBar",
  group: "views",
  importFrom: "@adminui/react",
  summary: "从看板、画册、日历、甘特打开一条记录：默认右侧抽屉，不挡视图；↑ ↓ 换上一条 / 下一条；抽屉、居中弹框、整页三档随时切。",
  keywords: "record expand drawer dialog detail 记录展开 抽屉 详情 弹框 整页 上一条 下一条 frame",
  when: ["在视图里点卡片 / 事件 / 条形，查看或编辑这条记录，同时还想看着视图。", "要连续浏览一列记录（逐条跟进）。"],
  whenNot: ["表格里点「展开」—— 仍可用居中弹框（frame=\"dialog\"）。", "简单的确认或表单 —— 用 Dialog。"],
  anatomy: [
    "外框标题栏：左 ↑ ↓ +「8 / 13 · 阶段看板」，右 复制链接 · ⋯ | 三档 | ×",
    "抽屉：640 宽、贴右铺满高、没有遮罩也不模糊，左边视图照样能点",
    "居中弹框：遮罩只用 overlay 半透明色，不模糊",
    "内容：记录详情分区（标题、徽标、关键数、分区字段）；抽屉里自动单栏",
  ],
  states: [
    "点别的卡片：抽屉直接换人，被打开的卡片在看板里高亮（selectedId）",
    "切换记录：骨架加载",
    "手机：全屏从下面滑入，顶栏 ‹ 标题 ⋯（44px 点击区）",
  ],
  dos: [
    "从视图打开记录默认 frame=\"drawer\"；给 onFrameChange 让用户切三档，\"page\" 由宿主跳到记录自己的地址。",
    "nav 给 index / total / label，标题栏写清在哪个列表里第几条。",
    "外框只放外框的事；关注、记跟进这些业务按钮放进详情头部。",
    "把打开的记录 id 传给视图的 selectedId，让用户知道在看哪张卡。",
  ],
  donts: [
    "不要从看板直接弹 1000+ 宽的大弹框、背后整页毛玻璃模糊。",
    "不要让用户先关掉再打开下一条。",
    "标题栏不要一排没分组的按钮，也不要用主色实底按钮做「关注」抢主操作。",
    "不要自己拿 SideSheet 拼详情抽屉。",
  ],
  a11y: [
    "Esc 关闭，焦点回到打开它的卡片；换过记录再关时回到最后那条。",
    "焦点在外框或标题栏时 ↑ / ↓ 换记录；任何位置 Alt+↑/↓ 或 J / K。",
    "抽屉是非模态的：视图仍可用 Tab 到达。",
  ],
  demos: [{ id: "views/record-expand-drawer", title: "从看板打开记录", description: "点任意卡片打开右侧抽屉；再点别的卡片直接换人，标题栏 ↑ ↓ 翻页、右侧切弹框。", height: 540 }],
};

export const viewsDocs: readonly ComponentDoc[] = [viewTabs, kanban, recordCard, gallery, calendar, gantt, viewSettings, recordExpand];
